Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2018-09, with the labels that each got.

#1286 Fixes #1275 - Holyhead CTA extension
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Holyhead CTA.txt
  Misc/Freetext_Airspace Bases.txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: airac, ready

#1298 Fixes #1276 - extended Irish Sea CTA
  .github/CHANGELOG.md
  ARTCC/High/Irish Sea CTA.txt
Labels: airac

#1260 Fixes #1273 - add EGTF airfield data and ground map
  .github/CHANGELOG.md
  Airports/EGTF/Basic.txt
  Airports/EGTF/Runway.txt
  Airports/EGTF/SMR/Geo.txt
  Airports/EGTF/SMR/Labels.txt
  Airports/EGTF/SMR/Regions.txt
  UK.rwy
  _data/SMR Files/EGTF/EGTF.kmz
Labels: enhancement

#1323 Fixes #1278 coventry squawk code
  .github/CHANGELOG.md
  Airports/EGBE/Positions.txt
Labels: airac, ready

#1303 Fixes #1139 - Add goodwood smr
  .github/CHANGELOG.md
  Airports/EGHR/Basic.txt
  Airports/EGHR/Ground Map/Regions.txt
  Airports/EGHR/Runway.txt
  UK.rwy
Labels: enhancement

#1325 Fixes #1322 - New Copenhagen Sectors
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Copenhagen.txt
  Sectors/Lines - External FIR.txt
Labels: airac, enhancement

#1357 Fixes #1338 - (U)P2 now RNAV airways
  .github/CHANGELOG.md
  Airways/Lower/P2.txt
  Airways/RNAV/P2.txt
  Airways/RNAV/UP2.txt
  Airways/Upper/UP2.txt
Labels: airac

#1331 Fixes #1176 - EGCN SMR update
  .github/CHANGELOG.md
  Airports/EGCN/SMR/Geo.txt
  Airports/EGCN/SMR/Labels.txt
  Airports/EGCN/SMR/Regions.txt
  _data/SMR Files/EGCN/Doncaster SMR.kmz
Labels: airac, enhancement

#1328 Fixes #1326 - EGBB squawk code range, mentor positions
  .github/CHANGELOG.md
  Airports/EGBB/Positions_Mentor.txt
Labels: bug

#1360 Fixes #1339 Fixes #1341 - EGNC APP withdrawn; ARP updated
  .github/CHANGELOG.md
  Airports/EGNC/Basic.txt
  Airports/EGNC/Ownership.txt
  Airports/EGNC/Positions.txt
  Airports/EGNC/Positions_Mentor.txt
  Airports/EGNC/Sector.txt
Labels: airac

#1327 Fixes #1149 - EGPN runway track update
  .github/CHANGELOG.md
  Airports/EGPN/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#1371 Fixes #1345 - EGBJ runway track updated
  .github/CHANGELOG.md
  Airports/EGBJ/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#1368 Fixes #1355 - EGPB freq doc file entry corrected
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: bug

#1367 Fixes #1354 - EGPO frequency updated
  .github/CHANGELOG.md
  Airports/EGPO/Positions.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1372 Fixes #1356 - Farnborough LARS position defined
  .github/CHANGELOG.md
  Airports/EGLF/Positions.txt
Labels: enhancement

#1365 Fixes #1348 Fixes #1350 Fixes #1351 Fixes #1352 - 8.33 doc file freq changes GD/LL/PA/PN
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac
