Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2018-08, with the labels that each got.

#1235 Fixes #1234 - removed EGLL old DVR SIDs
  .github/CHANGELOG.md
  Airports/EGLL/Sids.txt
Labels: enhancement

#1233 Fixes #1232 - remove old EGSS DVR SIDs
  .github/CHANGELOG.md
  Airports/EGSS/Sids.txt
Labels: enhancement

#1223 Fixes #1222 - removed dupe Manchester TMA in Sids
  .github/CHANGELOG.md
  Misc/SID_Manchester TMA.txt
Labels: enhancement

#1231 Fixes #1045 - EGHI 8.33 frequencies added to doc file
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1230 Fixes #1229 - removed old EGPH SIDs
  .github/CHANGELOG.md
  Airports/EGPH/Sids.txt
Labels: enhancement

#1228 Fixes #1227 - removed old EGWU SIDs
  .github/CHANGELOG.md
  Airports/EGWU/Sids.txt
Labels: enhancement

#1208 Fixes #1203 - removed old EGCC SIDs
  .github/CHANGELOG.md
  Airports/EGCC/Sids.txt
  Navaids/FIXES_General RNAV.txt
Labels: enhancement

#1210 Fixes #1198 - removed old EGNX SIDs
  .github/CHANGELOG.md
  Airports/EGNX/Sids.txt
  Navaids/FIXES_General RNAV.txt
Labels: enhancement

#1211 Fixes #1199 - removed old EGNM SIDs
  .github/CHANGELOG.md
  Airports/EGNM/Sids.txt
  Navaids/FIXES_General RNAV.txt
  Navaids/FIXES_UK.txt
Labels: enhancement

#1217 Fixes #1168 - NITON CTA Established
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/NITON CTA.txt
  Misc/Freetext_Airspace Bases.txt
Labels: airac

#1263 Fixes #1142 - New East Midlands Inbound Agreements
  .github/CHANGELOG.md
  Agreements/Internal/MAW_MAE.txt
  Airports/EGLK/SMR/Region.txt
Labels: airac

#1288 Fixes #1281 - Truncate N601 at Detling
  .github/CHANGELOG.md
  Airways/Lower/N601.txt
Labels: airac, ready

#1287 Fixes #1279 - Designated L9 between Compton and Strumble to Q63
  .github/CHANGELOG.md
  Airways/RNAV/L9.txt
  Airways/RNAV/Q63.txt
Labels: airac, ready

#1285 Fixes #1274 - Berry Head CTA extension
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Berry Head CTA.txt
  Misc/Freetext_Airspace Bases.txt
Labels: airac, ready

#1295 Fixes #1283 - EG D201 and EG D202 changes
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D201.txt
  ARTCC/Danger Areas/EG D202.txt
Labels: airac, ready

#1289 Fixes #1280 - EG D510 changes
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D510.txt
Labels: airac, ready

#1294 Fixes #1291 - egpd frequency update
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac, ready

#1302 Fixes #1300 - EGMD frequency update
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1301 Fixes #1299 - EGTC frequency update
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac
