Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2018-11, with the labels that each got.

#1380 #1378 EGMC Freq Updates
  .github/CHANGELOG.md
  Airports/EGMC/Positions.txt
Labels: enhancement, ready

#1449 Fixes #1448 - Adds missing label to Regions.txt
  Airports/EGKK/SMR/Regions.txt
Labels: bug, ready

#1435 Fixes #1397 - L980 and UL980 merged; L980 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/L980.txt
  Airways/RNAV/UL980.txt
Labels: ready

#1434 Fixes #1396 - UL620 and L620 merged; L620 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/L620.txt
  Airways/RNAV/UL620.txt
Labels: ready

#1433 Fixes #1395 - L608 airway rerouted
  .github/CHANGELOG.md
  Airways/RNAV/L608.txt
Labels: ready

#1432 Fixes #1394 - L602 airway rerouted
  .github/CHANGELOG.md
  Airways/RNAV/L602.txt
Labels: ready

#1431 Fixes #1393 - UL179 and L179 merged and rerouted
  .github/CHANGELOG.md
  Airways/RNAV/L179.txt
  Airways/RNAV/UL179.txt
Labels: ready

#1430 Fixes #1392 - UM197 redesignated M197, re-routed and now RNAV
  .github/CHANGELOG.md
  Airways/RNAV/M197.txt
  Airways/Upper/UM197.txt
Labels: ready

#1429 Fixes #1391 - withdraw UM84
  .github/CHANGELOG.md
  Airways/Upper/UM84.txt
Labels: ready

#1428 Fixes #1390 - M84 and M189 airways to RNAV and rerouted
  .github/CHANGELOG.md
  Airways/RNAV/M189.txt
  Airways/RNAV/M84.txt
Labels: ready

#1481 Resolves #1419 - EGBE Cement Works VRP renamed
  .github/CHANGELOG.md
  Airports/EGBE/VRPs.txt
Labels: ready

#1480 Resolves #1417 - UL610 and L610 airways merged
  .github/CHANGELOG.md
  Airways/RNAV/UL610.txt
Labels: ready

#1479 Resolves #1416 - UL18 rerouted
  .github/CHANGELOG.md
  Airways/Upper/UL18.txt
Labels: ready

#1478 Resolves #1415 - N866 airway rerouted
  .github/CHANGELOG.md
  Airways/RNAV/N866.txt
Labels: ready

#1477 Resolves #1414 - Z291 withdrawn
  .github/CHANGELOG.md
  Airways/RNAV/Z291.txt
Labels: ready

#1476 Resolves #1413 - Z171 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/Z171.txt
Labels: ready

#1475 Resolves #1412 - Y803 truncated
  .github/CHANGELOG.md
  Airways/RNAV/Y803.txt
Labels: ready

#1474 Resolves #1411 - Y113 airway removed
  .github/CHANGELOG.md
  Airways/RNAV/Y113.txt
Labels: ready

#1473 Resolves #1410 - Y110 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/Y110.txt
Labels: ready

#1472 Resolves #1409 - Y70 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/Y70.txt
Labels: ready

#1471 Resolves #1408 - Y4 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/Y4.txt
Labels: ready

#1470 Fixes #1406 - Q63 airway rerouted
  .github/CHANGELOG.md
  Airways/RNAV/Q63.txt
Labels: ready

#1467 Fixes #1404 - P144 airway rerouted
  .github/CHANGELOG.md
  Airways/RNAV/P144.txt
Labels: ready

#1466 Fixes #1403 - P49 airway extended
  .github/CHANGELOG.md
  Airways/RNAV/P49.txt
Labels: ready

#1465 Fixes #1402 - P44 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/P44.txt
Labels: ready

#1464 Fixes #1401 - M604 rerouted
  .github/CHANGELOG.md
  Airways/RNAV/M604.txt
Labels: ready

#1463 Fixes #1400 - UM185/M185 airways rerouted
  .github/CHANGELOG.md
  Airways/RNAV/M185.txt
  Airways/RNAV/UM185.txt
Labels: ready

#1462 Fixes #1398 - M20 withdrawn; M40 to replace
  .github/CHANGELOG.md
  Airways/RNAV/M20.txt
  Airways/RNAV/M40.txt
Labels: ready

#1460 Fixes #1426 - EGJJ ORIST SIDs added
  .github/CHANGELOG.md
  Airports/EGJJ/Fixes.txt
  Airports/EGJJ/Sids.txt
Labels: airac

#1457 Fixes #1384 - added missing MANW->DUBN agreement
  .github/CHANGELOG.md
  Agreements/External/MAW_DUBN.txt
Labels: bug

#1456 Fixes #1439 - EGKK CLN RNAV SIDs truncated
  .github/CHANGELOG.md
  Airports/EGKK/Fixes.txt
  Airports/EGKK/Sids.txt
Labels: airac

#1455 Fixes #1442 - EGLL/WU LAM3A redesignated
  .github/CHANGELOG.md
  Airports/EGLL/Stars.txt
  Airports/EGWU/Stars.txt
Labels: airac

#1451 Fixes #1450 - added missing fix to EGKK IMVUR1Z SID
  .github/CHANGELOG.md
  Airports/EGKK/Fixes.txt
  Airports/EGKK/Sids.txt
Labels: bug
