Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2018-12, with the labels that each got.

#1461 Fixes #1424 - EGJB ORIST/LERAK SIDs added
  .github/CHANGELOG.md
  Airports/EGJB/Fixes.txt
  Airports/EGJB/Sids.txt
Labels: airac

#1454 Fixes #1443 - redesignated EGSS/GW/SC STARs
  .github/CHANGELOG.md
  Airports/EGGW/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
Labels: airac, enhancement

#1453 Fixes #1444 - EGMC 8.33kHz frequencies doc file
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1452 Fixes #1445 - EGMC STAR redesignation
  .github/CHANGELOG.md
  Airports/EGMC/Stars.txt
Labels: airac

#1458 Fixes #1436 - amended LAKEY MAN TMA arrival agreement
  .github/CHANGELOG.md
  Agreements/Internal/Gal_Nor.txt
Labels: airac

#1427 Fixes #1389 - adds new 2018/13 fixes
  .github/CHANGELOG.md
  Navaids/FIXES_Old.txt
  Navaids/FIXES_UK.txt
Labels: ready

#1333 Fixes #1332 - fixed unclosed EKDK border lines
  .github/CHANGELOG.md
  Ownership/Non-UK/Copenhagen.txt
  Ownership/ScAC - East/Moray.txt
  Sectors/Lines - PACC.txt
Labels: bug

#1491 Fixes #1441 - EGLL SMR Update
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Labels.txt
  Airports/EGLL/SMR/Regions.txt
Labels: airac

#1487 Fixes #1421 - EGHI/HH SAM1B-> UMBUR1S
  .github/CHANGELOG.md
  Airports/EGHH/Stars.txt
  Airports/EGHI/Stars.txt
Labels: airac

#1488 Fixes #1446 - EGAA runway tracks updated
  .github/CHANGELOG.md
  Airports/EGAA/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#1486 Fixes #1438 - EGLC/KB XAMAN/SUMUM STARs redesignated
  .github/CHANGELOG.md
  Airports/EGKB/Stars.txt
  Airports/EGLC/Stars.txt
Labels: airac

#1485 Fixes #1440 - EGKK WILLO STAR changes
  .github/CHANGELOG.md
  Airports/EGKK/Stars.txt
Labels: airac

#1484 Fixes #1318 - EGPB RNAV approach fixes
  .github/CHANGELOG.md
  Airports/EGPB/Fixes.txt
Labels: airac

#1489 Fixes #1423 - EGSU basic info updated
  .github/CHANGELOG.md
  Airports/EGSU/Basic.txt
  Airports/EGSU/Positions.txt
  Airports/EGSU/Runway.txt
  UK.rwy
Labels: airac, bug

#1492 Fixes #1385 - EGSS SID fixes corrected
  .github/CHANGELOG.md
  Airports/EGSS/Sids.txt
Labels: bug

#1493 Fixes #1420 - EGPE 8.33 freqs added to doc
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1494 Fixes #1297 - EGCC SMR background colour
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Regions.txt
Labels: enhancement

#1498 Fixes #1497 - Virtual_Fixes.txt file extension
  .github/CHANGELOG.md
  Navaids/FIXES_Virtual.txt
Labels: bug

#1501 Fixes #1496 - added SASKI airspace to ARTCC High
  .github/CHANGELOG.md
  ARTCC/High/SASKI Delegated Airspace.txt
Labels: bug, enhancement

#1500 Fixes #1499 - removed EGBE airspace/SMAA data
  .github/CHANGELOG.md
  Airports/EGBE/Airspace.txt
  Airports/EGBE/SMAA.txt
Labels: enhancement

#1504 Fixes #1503 - TCNW guest ownership improved (KK WILLO3B)
  .github/CHANGELOG.md
  Ownership/TC - LTC/London TC NW.txt
Labels: enhancement

#1505 Fixes #1502 - S23->TCNW Essex agreement text changed
  .github/CHANGELOG.md
  Agreements/Internal/23_TCNW.txt
Labels: bug

#1506 Fixes #1270 - NM inbound agreements from MAE
  .github/CHANGELOG.md
  Agreements/Airport/East_NM.txt
  Agreements/Airport/MAW_NM.txt
  Agreements/Airport/Nor_NM.txt
Labels: bug, enhancement

#1510 Fixes #1508 - TOSVA fix coordinate corrected
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: bug

#1511 Fixes #1509 - Midlands MAW->MAE agreements
  .github/CHANGELOG.md
  Agreements/Internal/MAW_MAE.txt
Labels: bug

#1513 Fixes #1459 - Jersey Zone outbounds via ORIST agreement
  .github/CHANGELOG.md
  Agreements/Airport/JJ_S.txt
Labels: airac

#1516 Fixes #1515 - LUGIS/ODREP KK/Essex RRhigh_S agreements
  .github/CHANGELOG.md
  Agreements/External/RRhigh_S.txt
Labels: bug

#1518 Fixes #1517 - Add Heathrow Link Freetext
  .github/CHANGELOG.md
  Airports/EGLL/Freetext.txt
Labels: enhancement

#1495 Fixes #1388 - REFSO->IBNOS area
  .github/CHANGELOG.md
  ARTCC/High/IBNOS Delegated Airspace.txt
  ARTCC/High/REFSO Delegated Airspace.txt
  Ownership/AC - Central/Clacton.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/TC - LTC/London TC East.txt
  Sectors/Lines - LACC.txt
Labels: airac
