Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-10, with the labels that each got.

#1970 Fixes #1969 - Fixed duplicate position identifier (SCO_N/EISN)
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Dublin L18.txt
  Ownership/Non-UK/Dublin.txt
  Ownership/Non-UK/Shannon.txt
Labels: bug, ready

#1966 Fixes #1942 - Updated various London AC and TC frequencies
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK.txt
  Misc/Positions_Area Positions 3 UK.txt
Labels: enhancement, ready

#1965 Fixes #1958 - Updated Cranfield (EGTC) SMR (1911)
  .github/CHANGELOG.md
  Airports/EGTC/SMR/Geo.txt
  Airports/EGTC/SMR/Labels.txt
Labels: airac, ready

#1964 Fixes #1959 - Updated Edinburgh (EGPH) SMR - Turnhouse Apron (1911)
  .github/CHANGELOG.md
  Airports/EGPH/SMR/Labels.txt
  Airports/EGPH/SMR/Regions.txt
  _data/SMR Files/EGPH/Edinburgh - EGPH SMR.kmz
Labels: airac, ready

#1963 Fixes #1960 - Updated Gatwick (EGKK) SMR - Stand 103 (1911)
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Labels.txt
  Airports/EGKK/SMR/Regions.txt
  _data/SMR Files/EGKK/Gatwick SMR.kmz
Labels: airac, ready

#1962 Fixes #1961 - EBxx Danger Area Update
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EB R08.txt
  ARTCC/Danger Areas/EB R17.txt
  ARTCC/Danger Areas/EB R21.txt
  ARTCC/Danger Areas/EB R24.txt
  ARTCC/Danger Areas/EB R25.txt
  ARTCC/Danger Areas/EB R31.txt
  ARTCC/Danger Areas/EB R56.txt
  ARTCC/Danger Areas/EBD31.txt
  ARTCC/Danger Areas/EBD7.txt
  ARTCC/Danger Areas/EBD9.txt
  ARTCC/Danger Areas/EBR24.txt
  ARTCC/Danger Areas/EBR25.txt
Labels: enhancement

#1954 Fixes #1949 - LFxx Danger Area Update
  .github/CHANGELOG.md
  ARTCC/Danger Areas/(LFP)M10.txt
  ARTCC/Danger Areas/(LFP)M90.txt
  ARTCC/Danger Areas/(LFP307).txt
  ARTCC/Danger Areas/(LFP324).txt
  ARTCC/Danger Areas/(LFP331).txt
  ARTCC/Danger Areas/(LFP332).txt
  ARTCC/Danger Areas/(LFP335).txt
  ARTCC/Danger Areas/(LFP336).txt
  ARTCC/Danger Areas/LF D82.txt
  ARTCC/Danger Areas/LF P26.txt
  ARTCC/Danger Areas/LF P27.txt
  ARTCC/Danger Areas/LF P28.txt
  ARTCC/Danger Areas/LF P32.txt
  ARTCC/Danger Areas/LF P33.txt
  ARTCC/Danger Areas/LF P6-1.txt
  ARTCC/Danger Areas/LF P6-2.txt
  ARTCC/Danger Areas/LF P7.txt
  ARTCC/Danger Areas/LF P81.txt
  ARTCC/Danger Areas/LF R10.txt
Labels: enhancement

#1953 Fixes #1951 - Added EGAA/EGAC Departure Level Agreements
  .github/CHANGELOG.md
  Agreements/Airport/AA_Antrim
Labels: enhancement, ready

#1950 Fixes #1932 - Renamed sector lines from REF to IBNOS
  .github/CHANGELOG.md
  Ownership/AC - Central/Clacton.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC JACKO.txt
  Ownership/TC - LTC/London TC REDFA.txt
  Ownership/TC - LTC/London TC SABER.txt
  Ownership/TC - LTC/London TC VATON.txt
  Sectors/Lines - LACC.txt
  Sectors/Static/LON/Clacton.txt
  Sectors/Static/LTC/East.txt
Labels: enhancement, ready

#1896 Fixes #1853 - Southend Radar Ownership
  .github/CHANGELOG.md
  Airports/EGLC/Ownership.txt
  Airports/EGMC/Ownership.txt
  Airports/EGMC/Sector.txt
Labels: enhancement, ready

#1907 Fixes #1905 - Adds Observing LON_SC_CTR sector ownership
  .github/CHANGELOG.md
  Airports/EGBB/Ownership.txt
  Airports/EGGW/Ownership.txt
  Airports/EGHH/Ownership.txt
  Airports/EGHI/Ownership.txt
  Airports/EGKA/Ownership.txt
  Airports/EGKB/Ownership.txt
  Airports/EGKK/Ownership.txt
  Airports/EGLC/Ownership.txt
  Airports/EGLF/Ownership.txt
  Airports/EGLL/Ownership.txt
  Airports/EGMC/Ownership.txt
  Airports/EGMD/Ownership.txt
  Airports/EGNX/Ownership.txt
  Airports/EGSC/Ownership.txt
  Airports/EGSS/Ownership.txt
  Airports/EGTC/Ownership.txt
  Airports/EGTK/Ownership.txt
  Airports/EGWU/Ownership.txt
  Ownership/AC - Central/Clacton.txt
  Ownership/AC - Central/Daventry.txt
  Ownership/AC - South/Dover.txt
  Ownership/AC - South/Worthing.txt
  Ownership/Alternate/Airports - LON/Central.txt
  Ownership/Alternate/Airports - LON/South.txt
  Ownership/Alternate/Airports - LTC/E.txt
  Ownership/Alternate/Airports - LTC/NE.txt
  Ownership/Alternate/Airports - LTC/NW.txt
  Ownership/Alternate/Airports - LTC/SE.txt
  Ownership/Alternate/Airports - LTC/SW.txt
  Ownership/TC - LTC/ABBOT.txt
  Ownership/TC - LTC/London TC CPT.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC JACKO.txt
  Ownership/TC - LTC/London TC NE.txt
  Ownership/TC - LTC/London TC NW.txt
  Ownership/TC - LTC/London TC REDFA.txt
  Ownership/TC - LTC/London TC SABER.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC SW.txt
  Ownership/TC - LTC/London TC VATON.txt
Labels: enhancement, ready

#1911 Fixes #1893 - Extended Irish Sea CTA 1 and Strangford CTA
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Irish Sea CTA.txt
  ARTCC/High/Strangford CTA.txt
  Airports/EGAA/Sector.txt
  Airports/EGPK/Sector.txt
  Misc/Regions_Uncontrolled airspace.txt
  Sectors/Lines - PACC.txt
Labels: airac

#1926 Fixes #1925 - Agreement arrows FROM ScAC East sectors, and airports
  .github/CHANGELOG.md
  Agreements/Airport/Mon_PD.txt
  Agreements/Airport/Mor_PB.txt
  Agreements/Airport/PB_Mor.txt
  Agreements/Airport/PD_Mon.txt
  Agreements/Airport/PD_Mor.txt
  Agreements/Airport/PE_Mon.txt
  Agreements/Airport/PE_Mor.txt
  Agreements/Internal/Mon_Dcs.txt
  Agreements/Internal/Mon_Tal.txt
Labels: enhancement

#2054 Fixes #1999 - Update Airway N40
  .github/CHANGELOG.md
  Airways/RNAV/Upper/N40.txt
Labels: airac, ready

#2053 Fixes #1998 - Update Airway N19
  .github/CHANGELOG.md
  Airways/RNAV/Upper/N19.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2050 Fixes #1995 - Updated Airway L180
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L180.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2051 Fixes #1996- Amended airway L620
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L620.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2046 Fixes #1993 - Reroute L22
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L22.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2038 Fixes #2011 - Added EGBB STAR
  .github/CHANGELOG.md
  Airports/EGBB/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2048 Fixes #1990 - West CTA Amended
  .github/CHANGELOG.md
  ARTCC/High/West CTA.txt
Labels: airac, ready

#2055 Fixes #2000 - Remove Airway N54
  .github/CHANGELOG.md
  Airways/RNAV/Upper/N54.txt
Labels: airac, ready

#2034 Fixes #2009 - Y8 Reroute
  .github/CHANGELOG.md
  Airways/RNAV/Upper/Y8.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#1980 Fixes #1975 - Cardiff Inbound Agreement (Worthing->S23)
  .github/CHANGELOG.md
  Agreements/Internal/S_23.txt
Labels: enhancement, ready

#2043 Fixes #1968 - Removal of Church Fenton
  .github/CHANGELOG.md
  Airports/Other/EGXG.txt
Labels: bug, ready

#2021 Fixes #1991- Updates N862
  .github/CHANGELOG.md
  Airways/Conventional/Lower/N864.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2042 Fixes #1967 - Tilstock (EGCT) name/position/frequency corrected
  .github/CHANGELOG.md
  Airports/Other/EGCT.txt
Labels: bug, ready

#1984 Fixes #1983 - Corrected UNURO waypoint spelling on N864
  .github/CHANGELOG.md
  Airways/Conventional/Lower/N864.txt
Labels: bug, ready

#1981 Fixes #1716 - Delete duplicate airways
  .github/CHANGELOG.md
  Airways/Conventional/Lower/M140.txt
  Airways/Conventional/Lower/M733.txt
  Airways/Conventional/Lower/N14.txt
  Airways/Conventional/Lower/N16.txt
  Airways/Conventional/Lower/N20.txt
  Airways/Conventional/Lower/N34.txt
  Airways/Conventional/Lower/N42.txt
Labels: bug, ready

#1979 Fixes #1971 - Add EGLL GOGSI/GASGU agreements
  .github/CHANGELOG.md
  Agreements/Internal/TCSW_S.txt
Labels: bug, ready

#1978 Fixes #1974 - TCSE->Dover Agreements
  .github/CHANGELOG.md
  Agreements/Internal/TCNW_C.txt
  Agreements/Internal/TCSE_D.txt
Labels: bug, ready
