Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-01, with the labels that each got.

#1547 Fixes #1546 - added SITKU (missing fix)
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: bug

#1544 Fixes #1540 - L9 airway formatting corrected
  .github/CHANGELOG.md
  Airways/RNAV/L9.txt
Labels: bug

#1539 Fixes #1538 - Fix Goodwood (EGHR) runway definition for 14/32
  .github/CHANGELOG.md
  Airports/EGHR/Runway.txt
Labels: bug

#1536 Fixes #1533 - Add missing GALSO fix
  .github/CHANGELOG.md
  Navaids/FIXES_Non-UK.txt
Labels: bug

#1532 Fixes #1529 - EGLC/KB SUMUM/XAMAN STAR ordering
  .github/CHANGELOG.md
  Airports/EGKB/Stars.txt
  Airports/EGLC/Stars.txt
Labels: bug

#1531 Fixes #1528 - EGJB SID formatting
  .github/CHANGELOG.md
  Airports/EGJB/Sids.txt
Labels: bug, ready

#1526 Fixes #1441 - Update EGLL SMR
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
Labels: airac, on-hold

#1527 Fixes #1422 - Add hold N to EGSC SMR
  .github/CHANGELOG.md
  Airports/EGSC/SMR/Geo.txt
  Airports/EGSC/SMR/Labels.txt
Labels: airac

#1525 Fixes #1523 - Add EGCC RNAV fixes
  .github/CHANGELOG.md
  Airports/EGCC/Fixes.txt
  Navaids/FIXES_UK.txt
Labels: airac

#1524 Fixes #1522 - Correct UNSAD coordinates
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: bug

#1555 Fixes #1551 Fixes #1552 Fixes #1553 - Frequency Updates for 1901
  .github/CHANGELOG.md
  Airports/EGBP/Basic.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1558 Fixes #1542 - Updated EGFF SMR
  .github/CHANGELOG.md
  Airports/EGFF/SMR/Geo.txt
  Airports/EGFF/SMR/Labels.txt
Labels: airac

#1554 Fixes #1550 - EGGP Coordinates Updated
  .github/CHANGELOG.md
  Airports/EGGP/Runway.txt
Labels: airac

#1545 Fixes #1541 - TCNE->TCE agreements for post-1813 routings
  .github/CHANGELOG.md
  Agreements/Internal/TCNE_TCE.txt
Labels: bug, enhancement

#1537 Fixes #1530 - Update VATRY-10 to LEMGU in EIDW S8-DUBS agreement
  .github/CHANGELOG.md
  Agreements/External/8_DUBS.txt
Labels: enhancement

#1562 Fixes #1559 - More EGLL SMR updates
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
  Airports/EGLL/SMR/Regions.txt
Labels: airac
