Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-05, with the labels that each got.

#1746 Fixes #1739 Enhancement - Birmingham (EGBB) descent/director lines
  .github/CHANGELOG.md
  Airports/EGBB/RMA.txt
Labels: enhancement

#1784 Fixes #1729 EGLL Easterly CPT SIDs Routedraw
  .github/CHANGELOG.md
  Airports/EGLL/Sids.txt
  Navaids/FIXES_Virtual.txt
Labels: bug

#1781 Fixes #1780 - EGHH EGHI Agreements
  .github/CHANGELOG.md
  Agreements/Internal/C_TCNW.txt
Labels: airac

#1771 Fixes #1759 - EGNT STARs Added
  .github/CHANGELOG.md
  Airports/EGNT/Fixes.txt
  Airports/EGNT/Starts.txt
Labels: airac

#1768 Fixes #1749 Solent Frequency Update
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1767 Fixes #1750 EGCN Frequency Update
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1766 Fixes #1753 - EGEF Frequency Update
  .github/CHANGELOG.md
  Airports/Other/EGEF.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1765 Fixes #1764 - EGLW Frequency Update
  .github/CHANGELOG.md
  Airports/EGLW/Basic.txt
  Airports/EGLW/Positions.txt
  Airports/EGLW/Positions_Mentor.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1772 Fixes #1757 Essex Clutch Stars
  .github/CHANGELOG.md
  Airports/EGGW/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
Labels: airac

#1785 Fixes #1742 Lower Airways to RNAV
  .github/CHANGELOG.md
  Airways/Conventional/Lower/Y8.txt
  Airways/RNAV/Lower/N859.txt
  Airways/RNAV/Upper/Y8.txt
Labels: airac

#1752 Fixes #1747 - EGBB SID Update
  .github/CHANGELOG.md
  Airports/EGBB/Fixes.txt
  Airports/EGBB/Sids.txt
Labels: airac

#1798 Fixes #1793 Drop TCNE -> TCE and TCE -> LONE agreements on handoff
  .github/CHANGELOG.md
  Agreements/Internal/TCE_E.txt
  Agreements/Internal/TCNE_TCE.txt
Labels: bug

#1797 Fixes #1792 Drop KKAPP -> TCSW agreement on handoff
  .github/CHANGELOG.md
  Agreements/Airport/KK_TCSW.txt
Labels: bug

#1782 Fixes #1754 - EGLC/EGKB STARs Update
  .github/CHANGELOG.md
  Airports/EGKB/Stars.txt
  Airports/EGLC/Stars.txt
Labels: airac

#1776 Fixes #1760 - EGNT Level Agreements
  .github/CHANGELOG.md
  Agreements/Airport/MAE_NT.txt
  Agreements/Internal/10_MAE.txt
  Agreements/Internal/5_MAW.txt
  Agreements/Internal/C_MAE.txt
  Agreements/Internal/MAW_MAE.txt
Labels: airac

#1769 Fixes #1762 - Newtownards (EGAD) Frequency Update
  .github/CHANGELOG.md
  Airports/EGAD/Basic.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#1774 Fixes #1605 - EGPH SMR Update
  .github/CHANGELOG.md
  Airports/EGPH/SMR/Geo.txt
  Airports/EGPH/SMR/Labels.txt
  Airports/EGPH/SMR/Regions.txt
  _data/SMR Files/EGPH/Edinburgh - EGPH SMR.kmz
Labels: airac

#1770 Fixes #1763 EGMC STARs redesignated
  .github/CHANGELOG.md
  Airports/EGMC/Stars.txt
Labels: airac

#1676 Fixes #1026 - previously unavailable 136. frequencies
  .github/CHANGELOG.md
  Airports/EGGD/Positions.txt
  Airports/EGKK/Positions.txt
  Airports/EGLC/Positions.txt
  Airports/EGMC/Positions.txt
  Airports/EGSS/Positions.txt
  Doc/UK VATSIM frequencies.txt
Labels: enhancement

#1725 Fixes #1715 - reinstated Heathrow (EGLL) N1 holding point on SMR
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
  Airports/EGLL/SMR/Regions.txt
Labels: enhancement, on-hold

#1659 Fixes #838 - MAN E and MAN W static boundaries
  .github/CHANGELOG.md
  Sectors/Static/MTC/MAN E.txt
  Sectors/Static/MTC/MAN W.txt
Labels: enhancement

#1655 Fixes #1646 - agreement arrows FROM AC South
  .github/CHANGELOG.md
  Agreements/External/D_BUhigh.txt
  Agreements/External/S_FFhighW.txt
  Agreements/External/S_RRlow.txt
  Agreements/Internal/D_E.txt
  Agreements/Internal/S_23.txt
  Agreements/Internal/S_6.txt
  Agreements/Internal/S_C.txt
  Agreements/Internal/S_D.txt
Labels: enhancement
