Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-02, with the labels that each got.

#1521 Fixes #1520 - Update ENSV CTR Frequencies
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
Labels: bug, ready

#1586 Fixes#1585 Bristol VRP Update
  .github/CHANGELOG.md
  Airports/EGGD/VRPs.txt
Labels: bug, good first issue

#1588 Resolves #1587 - 1903 Airways Update
  .github/CHANGELOG.md
  Airways/RNAV/L46.txt
  Airways/RNAV/L602.txt
  Airways/RNAV/L7.txt
  Airways/RNAV/N110.txt
  Airways/RNAV/N44.txt
  Airways/RNAV/N66.txt
  Airways/RNAV/N97.txt
  Airways/RNAV/P58.txt
  Airways/RNAV/Y70.txt
  Airways/Upper/UL975.txt
  Airways/Upper/UP18.txt
  Airways/Upper/UP59.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready
