Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-11, with the labels that each got.

#2061 Fixes #2005 - Reroutes UL9 and adds new fixes
  .github/CHANGELOG.md
  Airways/RNAV/Upper/UL9.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#1982 Fixes #1956 - Removed Conventional Upper Airways Remnants
  .github/CHANGELOG.md
  Airways/Conventional/Upper/UM140.txt
  Airways/Conventional/Upper/UM142.txt
  Airways/Conventional/Upper/UM189.txt
  Airways/Conventional/Upper/UM733.txt
  Airways/Conventional/Upper/UN14.txt
  Airways/Conventional/Upper/UN16.txt
  Airways/Conventional/Upper/UN18.txt
  Airways/Conventional/Upper/UN20.txt
  Airways/Conventional/Upper/UN21.txt
  Airways/Conventional/Upper/UN22.txt
  Airways/Conventional/Upper/UN26.txt
  Airways/Conventional/Upper/UN32.txt
  Airways/Conventional/Upper/UN34.txt
  Airways/Conventional/Upper/UN38.txt
  Airways/Conventional/Upper/UN42.txt
  Airways/Conventional/Upper/UN472.txt
  Airways/Conventional/Upper/UN484.txt
  Airways/Conventional/Upper/UN552.txt
  Airways/Conventional/Upper/UQ220.txt
  Airways/Conventional/Upper/UT191.txt
  Airways/Conventional/Upper/UT220.txt
  Airways/Conventional/Upper/UT225.txt
  Airways/Conventional/Upper/UT260.txt
  Airways/Conventional/Upper/UT422.txt
  Airways/Conventional/Upper/UT423.txt
  Airways/Conventional/Upper/UT426.txt
  Airways/Conventional/Upper/UY111.txt
  Airways/Conventional/Upper/UY29.txt
  Airways/Conventional/Upper/UY376.txt
  Airways/Conventional/Upper/UY76.txt
  Airways/Conventional/Upper/UY9.txt
  Airways/Conventional/Upper/UZ273.txt
Labels: bug

#1985 Fixes #1812 - Upper Airways to RNAV
  .github/CHANGELOG.md
  Airways/RNAV/Upper/UL975.txt
  Airways/RNAV/Upper/UM869.txt
  Airways/RNAV/Upper/UN160.txt
  Airways/RNAV/Upper/UN537.txt
  Airways/RNAV/Upper/UN562.txt
  Airways/RNAV/Upper/UN57.txt
  Airways/RNAV/Upper/UN581.txt
  Airways/RNAV/Upper/UN583.txt
  Airways/RNAV/Upper/UN584.txt
  Airways/RNAV/Upper/UN590.txt
  Airways/RNAV/Upper/UN591.txt
  Airways/RNAV/Upper/UN593.txt
  Airways/RNAV/Upper/UN601.txt
  Airways/RNAV/Upper/UN603.txt
  Airways/RNAV/Upper/UN614.txt
  Airways/RNAV/Upper/UN859.txt
  Airways/RNAV/Upper/UN864.txt
  Airways/RNAV/Upper/UP6.txt
Labels: airac

#1986 Fixes #1955 - Moved Airways to RNAV
  .github/CHANGELOG.md
  Airways/RNAV/Lower/Y311.txt
  Airways/RNAV/Lower/Y312.txt
  Airways/RNAV/Upper/UY311.txt
  Airways/RNAV/Upper/UY312.txt
Labels: airac

#2026 Fixed #2025 - Show ATZ ring to LCTWR when LCR is top-down by London
  .github/CHANGELOG.md
  Airports/EGLC/Sector.txt
Labels: bug

#2056 Fixes #1976 - Scottish TMA inbound agreement update
  .github/CHANGELOG.md
  Agreements/Internal/Mon_Tal.txt
Labels: enhancement, ready

#2059 Fixes #2024 - Removes dupe use of LAC BBX frequency
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 3 UK.txt
Labels: bug, ready

#2066 Fixes #1987 - Birmingham CTA 10 added
  .github/CHANGELOG.md
  Airports/EGBB/Airspace.txt
  Airports/EGBB/Airspace_Bases.txt
Labels: airac

#2065 Fixes #1977 - LFP6-1 unclosed area closed
  .github/CHANGELOG.md
  ARTCC/Danger Areas/LF P6-1.txt
Labels: bug

#2062 Fixes #2003 - N546 reroute
  .github/CHANGELOG.md
  Airways/RNAV/Upper/N546.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2047 Fixes #2044 - Updated Heathrow (EGLL) link labels L35 and L36
  .github/CHANGELOG.md
  Airports/EGLL/Freetext.txt
Labels: bug

#2036 Fixes #2015 - Updated Gatwick (EGKK) STARs (1912)
  .github/CHANGELOG.md
  Airports/EGKK/Stars.txt
Labels: airac

#2037 Fixes #2014 - Redesignated EGLC/KB STARs (1912)
  .github/CHANGELOG.md
  Airports/EGKB/Stars.txt
  Airports/EGLC/Stars.txt
Labels: airac

#2049 Fixes #1994 - Update Airway L179
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L179.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2031 Fixes #2019 - EGLL/EGWU FITBO1H Inbound Agreement
  .github/CHANGELOG.md
  Agreements/Internal/8_C.txt
Labels: airac

#2068 Fixes #1989 - Daventry CTA 23-24 added
  .github/CHANGELOG.md
  ARTCC/High/Daventry CTA.txt
  Misc/Freetext_Airspace Bases.txt
Labels: airac

#2067 Fixes #1988 - Cotswold CTA 15-18 added
  .github/CHANGELOG.md
  ARTCC/High/Cotswold CTA.txt
  Misc/Freetext_Airspace Bases.txt
Labels: airac

#2052 Fixes #1997 - Update Airway N17
  .github/CHANGELOG.md
  Airways/RNAV/Upper/N17.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2039 Fixes #2007 UN864 Added
  .github/CHANGELOG.md
  Airways/RNAV/Upper/UN864.txt
Labels: airac

#2075 Fixes #2029 - TC SW to AC Worthing agreement fix
  .github/CHANGELOG.md
  Agreements/Internal/TCSW_S.txt
Labels: bug, ready

#2074 Fixes #1972 - Agreements IoM->DUBN for EIDW inbounds
  .github/CHANGELOG.md
  Agreements/External/IoM_DUBN.txt
Labels: enhancement, ready

#2073 Fixes 1939 - New agreements STAFA-AC DTY for EGGP outbounds
  .github/CHANGELOG.md
  Agreements/Internal/Sta_C.txt
Labels: bug, ready

#2089 Fixes #2088 - Fixed N862 Airway
  .github/CHANGELOG.md
  Airways/RNAV/Lower/N862.txt
Labels: bug

#2040 Fixes #1535 - RNAV fixes wrong location
  .github/CHANGELOG.md
  Airports/EGAA/Fixes.txt
  Airports/EGAE/Fixes.txt
  Airports/EGBB/Fixes.txt
  Airports/EGBJ/Fixes.txt
  Airports/EGCC/Fixes.txt
  Airports/EGGD/Fixes.txt
  Airports/EGGW/Fixes.txt
  Airports/EGHE/Fixes.txt
  Airports/EGHG/Fixes.txt
  Airports/EGHI/Fixes.txt
  Airports/EGJA/Fixes.txt
  Airports/EGJB/Fixes.txt
  Airports/EGJJ/Fixes.txt
  Airports/EGKB/Fixes.txt
  Airports/EGKK/Fixes.txt
  Airports/EGLC/Fixes.txt
  Airports/EGLF/Fixes.txt
  Airports/EGLL/Fixes.txt
  Airports/EGMC/Fixes.txt
  Airports/EGMD/Fixes.txt
  Airports/EGNH/Fixes.txt
  Airports/EGNJ/Fixes.txt
  Airports/EGNL/Fixes.txt
  Airports/EGNS/Fixes.txt
  Airports/EGNX/Fixes.txt
  Airports/EGPB/Fixes.txt
  Airports/EGPD/Fixes.txt
  Airports/EGPF/Fixes.txt
  Airports/EGPH/Fixes.txt
  Airports/EGPM/Fixes.txt
  Airports/EGSC/Fixes.txt
  Airports/EGSS/Fixes.txt
  Airports/EGTE/Fixes.txt
  Airports/EGTK/Fixes.txt
  Airports/EGWU/Fixes.txt
  Navaids/FIXES_CICZ.txt
  Navaids/FIXES_Non-UK.txt
  Navaids/FIXES_Old.txt
  Navaids/FIXES_SIDS-STARS.txt
  Navaids/FIXES_UK.txt
Labels: airac, bug

#1952 Fixes #1909 - Updated Gatwick (EGKK) Non RNAV SID fixes
  .github/CHANGELOG.md
  Airports/EGKK/Sids.txt
  Airports/EGPF/Sids.txt
  Navaids/FIXES_Old.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: airac, enhancement
