Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-04, with the labels that each got.

#1727 Fixes #1722 - EGBB ATIS Frequency Update
  .github/CHANGELOG.md
  Airports/EGBB/Positions.txt
Labels: enhancement, ready

#1724 Fixes #1719 - EGNV Frequency Update
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: ready

#1723 Fixes #1720 - EGPH Frequency Updates
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: ready

#1701 Fixes #1700 - Remove Elksham VRP, Bristol (EGGD)
  .github/CHANGELOG.md
  Airports/EGGD/VRPs.txt
Labels: bug, ready

#1699 Fixes #1689 - Updated Coningsby (EGXC) Squawk Range
  .github/CHANGELOG.md
  Airports/EGXC/Positions.txt
Labels: airac, ready

#1683 Fixes #1682 - Corrected Birmingham (EGBB) squawk range
  .github/CHANGELOG.md
  Airports/EGBB/Positions.txt
  Airports/EGBB/Positions_Mentor.txt
Labels: bug, ready

#1674 Fixes #1672 - Runway Definition Formatting
  .github/CHANGELOG.md
  Airports/EGHE/Runway.txt
  Airports/EGHO/Runway.txt
  Airports/EGHR/Runway.txt
  Airports/EGNO/Runway.txt
  Airports/EGPR/Runway.txt
Labels: enhancement, ready

#1621 Fixes #1591 - EGD323 updates
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D323.txt
Labels: airac, ready

#1709 Fixes #1706 - Heathrow (EGLL) stands 517 & 581 removed
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Labels.txt
Labels: airac

#1658 Fixes #1425 - EGPE runway track updated
  .github/CHANGELOG.md
  Airports/EGPE/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#1734 Fixes #1733 - M184 airway formatting
  Airways/RNAV/Lower/M184.txt
Labels: bug

#1730 Fixes #1681 - Updated Heathrow (EGLL) stand labels
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Labels.txt
Labels: enhancement, ready

#1704 Fixes #1694 - Added Biggin (EGKB) holding points (E and F3)
  .github/CHANGELOG.md
  Airports/EGKB/SMR/Geo.txt
  Airports/EGKB/SMR/Labels.txt
Labels: airac, ready

#1698 Fixes #1697 - Updated Cardiff (EGFF) VRPs
  .github/CHANGELOG.md
  Airports/EGFF/VRPs.txt
Labels: bug, ready

#1696 Fixes #1583 - Updated Bournemouth (EGHH) VRPs
  .github/CHANGELOG.md
  Airports/EGHH/VRPs.txt
Labels: bug, ready

#1703 Fixes #1702 - Remove defunct Dundee (EGPN) VRPs
  .github/CHANGELOG.md
  Airports/EGPN/VRPs.txt
Labels: bug

#1728 Fixes #1721 - Updated Hawarden (EGNR) VRPs (1905)
  .github/CHANGELOG.md
  Airports/EGNR/VRPs.txt
Labels: airac

#1662 Fixes #1663 - DW arrivals Dcs/Rat/Ant agreement change
  .github/CHANGELOG.md
  Agreements/Internal/Dcs_Ant.txt
  Agreements/Internal/Rat_Ant.txt
Labels: enhancement

#1711 Fixes #1690 - Danger Area EG D403 updated
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D403.txt
Labels: airac

#1713 Fixes #1692 - Danger Area EG D512 updated
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D512.txt
Labels: airac

#1714 Fixes #1693 - Danger Area EG D513 updated
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D513.txt
Labels: airac

#1710 Fixes #1707 - Luton (EGGW) hold F1 redesignated J1
  .github/CHANGELOG.md
  Airports/EGGW/SMR/Geo.txt
  Airports/EGGW/SMR/Labels.txt
Labels: airac

#1688 Fixes #1687 - updated JJCTR line display
  .github/CHANGELOG.md
  Airports/EGJJ/Positions.txt
  Airports/EGJJ/Sector.txt
Labels: bug

#1686 Fixes #1685 - agreement arrows FROM AC West
  .github/CHANGELOG.md
  Agreements/Airport/23_GD.txt
  Agreements/Internal/23_S.txt
Labels: enhancement

#1675 Fixes #1673 #1731 - Moved SSFIN line; Updated SSAPP line display
  .github/CHANGELOG.md
  Airports/EGSS/Ownership.txt
  Airports/EGSS/Sector.txt
Labels: bug

#1667 Fixes #1566 - ENSV_N and ENSV split added
  .github/CHANGELOG.md
  Ownership/Non-UK/Stavanger.txt
  Ownership/ScAC - East/Moray.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - PACC.txt
Labels: bug, enhancement

#1632 Fixes #1629 - updated BIRD sectors
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Reykjavik.txt
Labels: enhancement

#1680 Fixes #1679 - adjustments to Gatwick (EGKK) SMR
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Labels.txt
  Airports/EGKK/SMR/Regions.txt
  _data/SMR Files/EGKK/Gatwick SMR.kmz
Labels: enhancement

#1712 Fixes #1691 - Danger Area EG D406 updated
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D406.txt
Labels: airac

#1708 Fixes #1705 - Updated Heathrow (EGLL) runway track and threshold coordinates
  .github/CHANGELOG.md
  Airports/EGLL/Runway.txt
  Doc/Runway track changes.txt
Labels: airac
