Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-08, with the labels that each got.

#1884 Fix #1814 - Biggin Hill (EGKB) hold AB removed (SMR)
  .github/CHANGELOG.md
  Airports/EGKB/SMR/Geo.txt
  Airports/EGKB/SMR/Labels.txt
Labels: airac, ready

#1879 Fixes #1840 - Added agreement TCNW->ACS for SS tfc via M183
  .github/CHANGELOG.md
  Agreements/Internal/TCNW_S.txt
Labels: bug, ready

#1873 Fixes #1872 - Fixed Stavanger Ownership
  .github/CHANGELOG.md
  Ownership/Non-UK/Stavanger.txt
Labels: bug

#1732 Fixes #1565 - EGAC covered top-down by EGAA_APP (125.8)
  .github/CHANGELOG.md
  Agreements/Airport/AA_AC.txt
  Airports/EGAA/Ownership.txt
  Airports/EGAA/Positions.txt
  Airports/EGAA/Positions_Mentor.txt
  Airports/EGAA/Sector.txt
  Airports/EGAC/Ownership.txt
  Airports/EGAC/Positions_Mentor.txt
  Airports/EGAC/Sector.txt
Labels: enhancement

#1886 Fixes #1660 - PC West Split
  .github/CHANGELOG.md
  Agreements/Internal/IoM_Wal.txt
  Agreements/Internal/Wal_IoM.txt
  Airports/EGBB/Ownership.txt
  Airports/EGCC/Ownership.txt
  Airports/EGGP/Ownership.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/TC - MAN/Wallasey.txt
Labels: enhancement
