Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2019-03, with the labels that each got.

#1618 Fixes #1611 - Update EGAE frequency
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac, ready

#1619 Fixes #1602 - Danger Zones Redesignated
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D006.txt
  ARTCC/Danger Areas/EG D007.txt
  ARTCC/Danger Areas/EG D008.txt
  ARTCC/Danger Areas/EG D009.txt
  ARTCC/Danger Areas/EG D133.txt
  ARTCC/Danger Areas/EG D138.txt
Labels: airac, ready

#1620 Fixes #1584- EGPD Meldrum VRP Coordinate update
  .github/CHANGELOG.md
  Airports/EGPD/VRPs.txt
Labels: bug, ready

#1622 Fixes #1613 and #1604 - EGPK and EGNX Frequency Updates
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac, ready

#1623 Fixes #1608 - EGKH frequency
  .github/CHANGELOG.md
  Airports/EGKH/Basic.txt
Labels: airac, ready

#1631 Fixes #1630 - added Gander Oceanic frequency
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Shanwick.txt
Labels: enhancement

#1626 Fixes #1571 - additional agreements Rat->S7 added for AA/AC outbounds
  .github/CHANGELOG.md
  Agreements/Internal/Rat_7.txt
Labels: bug

#1634 Fixes #1625 - Updated EGKK Pier 5 stand labels
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Labels.txt
Labels: enhancement, up-for-grabs

#1637 Fixes #1635 - Added EGKK Z1 holding point
  .github/CHANGELOG.md
  Airports/EGKK/Ground Map/Geo.txt
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Labels.txt
Labels: airac

#1651 Fixes #1592 - Update EGLK SMR
  .github/CHANGELOG.md
  Airports/EGLK/SMR/Geo.txt
  Airports/EGLK/SMR/Labels.txt
  Airports/EGLK/SMR/Region.txt
  Airports/EGLK/SMR/Regions.txt
Labels: airac

#1649 Fixes #1607 - DET2Z Withdrawn
  .github/CHANGELOG.md
  Airports/EGLL/Sids.txt
Labels: airac, ready

#1628 Fixes #1603 - RNAV airway redesignation
  .github/CHANGELOG.md
  Airways/RNAV/L18.txt
  Airways/RNAV/L613.txt
  Airways/RNAV/M8.txt
  Airways/RNAV/M85.txt
  Airways/RNAV/M87.txt
  Airways/RNAV/UL18.txt
  Airways/RNAV/UL607.txt
  Airways/RNAV/UL613.txt
  Airways/RNAV/UL619.txt
  Airways/RNAV/UL722.txt
  Airways/RNAV/UL739.txt
  Airways/RNAV/UM125.txt
  Airways/RNAV/UM25.txt
  Airways/RNAV/UM30.txt
  Airways/RNAV/UM65.txt
  Airways/RNAV/UM8.txt
  Airways/RNAV/UM82.txt
  Airways/RNAV/UM86.txt
  Airways/RNAV/UM89.txt
  Airways/RNAV/UY53.txt
  Airways/RNAV/Y53.txt
Labels: airac

#1627 Fixes #1596 - Added EGPK RNAV approach fixes
  .github/CHANGELOG.md
  Airports/EGPK/Fixes.txt
Labels: airac

#1652 Fixes #1606 - EGLF VRPs
  .github/CHANGELOG.md
  Airports/EGLF/VRPs.txt
Labels: airac, ready

#1648 Fixes #1610 - EGLL SMR Update
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
  Airports/EGLL/SMR/Regions.txt
Labels: airac, ready

#1647 Fixes #1614 - EGPK Runway Heading Update
  .github/CHANGELOG.md
  Airports/EGPK/Runway.txt
  Doc/Runway track changes.txt
Labels: airac, ready
