Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-09, with the labels that each got.

#2834 Fixes #2825 - EGTE 8.33 kHZ Frequencies
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#2842 Fixes #2412 - Updated EGNR Outbound IoM->Rathlin Agreements (Finished the Issue)
  .github/CHANGELOG.md
  Agreements/Internal/IoM_Rat.txt
Labels: procedure-change, ready

#2843 Fixes #2813 - Added further PC West splitting functionality
  .github/CHANGELOG.md
  Airports/EGGP/Ownership.txt
  Airports/EGNH/Ownership.txt
  Airports/EGNS/Ownership.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/Alternate/Airports - MPC/Isle of Man.txt
  Ownership/Alternate/Airports - MPC/Wallasey.txt
  Ownership/TC - MPC/IoM.txt
  Ownership/TC - MPC/S29.txt
  Ownership/TC - MPC/Wallasey.txt
Labels: enhancement

#2844 Fixes #2748 - LS -> S6 Agreement Update
  .github/CHANGELOG.md
  Agreements/Internal/S_6.txt
Labels: procedure-change, ready

#2846 Fixes #2845 - Fixed EGPO ground map geo
  .github/CHANGELOG.md
  Airports/EGPO/Ground Map/Geo.txt
Labels: bug

#2849 Fixes #2830 - Updated Gatwick (EGKK) Non-RNAV SID fixes
  .github/CHANGELOG.md
  Airports/EGKK/Sids.txt
  Doc/Runway track changes.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: airac

#2856 Fixes #2851 - Updated PC Wallasey->Liverpool APC Agreements
  .github/CHANGELOG.md
  Agreements/Airport/Wal_GP.txt
Labels: enhancement, ready

#2861 Fixes #2853 - Added AC Worthing/TC SW->Solent Inbound Agreements
  .github/CHANGELOG.md
  Agreements/Airport/S_Solent.txt
  Agreements/Airport/TCSW_Solent.txt
Labels: enhancement

#2857 Fixes #2852 - Updated PC Trent/Daventry->NXAPP inbound agreements
  .github/CHANGELOG.md
  Agreements/Airport/TCWEL_NX.txt
  Agreements/Airport/Trent_NX.txt
Labels: enhancement, ready

#2860 Fixes #2859 - Reorder of GP STARs
  .github/CHANGELOG.md
  Airports/EGGP/Stars.txt
Labels: enhancement

#2862 Fixes #2855 - Updated S29 -> Stafa BB inbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/S29_Sta.txt
Labels: enhancement, ready

#2866 Fixes #2865 - Added AC W -> PC S29 Severn Group dep agreement
  .github/CHANGELOG.md
  Agreements/Internal/5_S29.txt
Labels: enhancement, ready

#2873 Fixes #2870 - Inverness Radar Delegated Airspace
  .github/CHANGELOG.md
  Airports/EGPE/Ownership.txt
  Airports/EGPE/Positions.txt
  Airports/EGPE/Positions_Mentor.txt
  Airports/EGPE/Sector.txt
Labels: procedure-change, ready

#2875 Fixes #2850 - Added AC West -> GD 'offline' agreements (and improved LW->FF COPX)
  .github/CHANGELOG.md
  Agreements/Airport/5_FF.txt
  Agreements/Airport/5_GD.txt
  Agreements/Airport/6_FF.txt
  Agreements/Airport/6_GD.txt
  Agreements/Airport/8_FF.txt
  Agreements/Airport/8_GD.txt
Labels: procedure-change

#2880 Fixes #2877 - Add Newquay (EGHQ) SMAA Overlay
  .github/CHANGELOG.md
  Airports/EGHQ/SMAA.txt
Labels: enhancement, ready

#2885 Fixes #2884 - EGBB VRP Removed
  .github/CHANGELOG.md
  Airports/EGBB/VRPs.txt
Labels: airac, ready

#2886 Fixes #2881 - Tresco Heliport added to AIP
  .github/CHANGELOG.md
  Airports/Other/EGHT.txt
Labels: airac, ready

#2891 Fixes #2889 - Changed Wick (EGPO) ATIS frequency to avoid conflicts with the WIK VOR
  .github/CHANGELOG.md
  Airports/EGPC/Positions.txt
  Doc/UK VATSIM frequencies.txt
Labels: bug

#2868 Fixes #2867 - Improved NIMAT-ROTEV Buffer
  .github/CHANGELOG.md
  Misc/STAR_NIMAT-ROTEV Buffer.txt
  Misc/STAR_ROTEV-NIMAT Buffer.txt
Labels: enhancement

#2893 Fixes #2892 - PH FIN not showing for PH INT when online
  .github/CHANGELOG.md
  Airports/EGPH/Ownership.txt
Labels: bug

#2897 Fixes #2896 - Add EGXP Scampton
  .github/CHANGELOG.md
  Airports/EGXP/Active_Runway.txt
  Airports/EGXP/Airspace.txt
  Airports/EGXP/Basic.txt
  Airports/EGXP/Positions.txt
  Airports/EGXP/Runway.txt
Labels: enhancement, ready

#2901 Fixes #2900 - Add Yeovil Westland (EGHG) Positions and Runways
  .github/CHANGELOG.md
  Airports/EGHG/Positions.txt
  Airports/EGHG/Runway.txt
  Doc/UK VATSIM frequencies.txt
Labels: enhancement, ready

#2902 Fixes #2854 - Changed Stornoway (EGPO) ATIS frequency to avoid conflicts with the STN VOR
  .github/CHANGELOG.md
  Airports/EGPO/Positions.txt
  Doc/UK VATSIM frequencies.txt
Labels: bug

#2905 Fixes #2904 - Add EGVP Middle Wallop
  .github/CHANGELOG.md
  Airports/EGVP/Airspace.txt
Labels: enhancement, ready

#2911 Fixes #2910 - Add EGYE Barkston Heath
  .github/CHANGELOG.md
  Airports/EGYE/Airspace.txt
  Airports/EGYE/Basic.txt
  Airports/EGYE/Positions.txt
  Airports/EGYE/Runway.txt
Labels: enhancement, ready

#2912 Fixes #2909 - Add EGXZ Topcliffe
  .github/CHANGELOG.md
  Airports/EGXZ/Airspace.txt
  Airports/EGXZ/Basic.txt
  Airports/EGXZ/Runway.txt
Labels: enhancement, ready

#2913 Fixes #2908 - Add EGXU Linton
  .github/CHANGELOG.md
  Airports/EGXU/Airspace.txt
  Airports/EGXU/Basic.txt
  Airports/EGXU/Runway.txt
Labels: enhancement, ready

#2914 Fixes #2907 - Add EGOQ Mona
  .github/CHANGELOG.md
  Airports/EGOQ/Airspace.txt
  Airports/EGOQ/Basic.txt
  Airports/EGOQ/Runway.txt
Labels: enhancement, ready

#2915 Fixes #2906 - Add EGOE Ternhill
  .github/CHANGELOG.md
  Airports/EGOE/Airspace.txt
  Airports/EGOE/Basic.txt
  Airports/EGOE/Runway.txt
Labels: enhancement, ready

#2921 Fixes #2920 - Update Lands End (EGHC) SMR
  .github/CHANGELOG.md
  Airports/EGHC/Ground Map/Geo.txt
  Airports/EGHC/SMR/GEO.txt
  Airports/EGHC/SMR/Labels.txt
  Airports/EGHC/SMR/Regions.txt
Labels: enhancement

#2923 Fixes #2922 - Updated Newquay (EGHQ) Positions
  .github/CHANGELOG.md
  Airports/EGHQ/Ownership.txt
  Airports/EGHQ/Positions.txt
Labels: enhancement, procedure-change
