Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-03, with the labels that each got.

#2289 Fixes #2288 - EGLL SID Designators
  .github/CHANGELOG.md
  Airports/EGLL/Sids.txt
Labels: airac, ready

#2292 Fixes #2291 - Typo in AC Worthing Agreements
  .github/CHANGELOG.md
  Agreements/Internal/Solent_S.txt
Labels: bug, ready

#2294 Fixes #2293 - Added Missing Taxiway line (EGGD)
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
Labels: bug, ready

#2298 Fixes #2297 - Add labels to Sumburgh (EGPB) SMR
  .github/CHANGELOG.md
  Airports/EGPB/Ground Map/Freetext.txt
  Airports/EGPB/Ground Map/Labels.txt
Labels: enhancement

#2296 Fixes #2295 - Improve Kirkwall (EGPA) SMR
  .github/CHANGELOG.md
  Airports/EGPA/Ground Map/Geo.txt
  Airports/EGPA/SMR/Geo.txt
  Airports/EGPA/SMR/Labels.txt
  Airports/EGPA/SMR/Regions.txt
  _data/SMR Files/EGPA/Kirkwall SMR.kmz
Labels: enhancement

#2304 Fixes #2303 - Remove Cardiff Topdown Coverage of Bristol
  .github/CHANGELOG.md
  Airports/EGGD/Ownership.txt
Labels: enhancement

#2300 Fixes #2299 - Add Northolt SMAA
  .github/CHANGELOG.md
  Airports/EGWU/SMAA.txt
Labels: enhancement

#2306 Fixes #2305 - Added Kemble (EGPB) Airport Files
  .github/CHANGELOG.md
  Airports/EGBP/Positions.txt
  Airports/EGBP/Runway.txt
Labels: enhancement

#2302 Fixes #2301 - New EGBP SMR
  .github/CHANGELOG.md
  Airports/EGBP/SMR/GEO.txt
  Airports/EGBP/SMR/Labels.txt
  Airports/EGBP/SMR/Regions.txt
  Airports/EGBP/SMR/Runway.txt
Labels: enhancement

#2317 Fixes #2314 - EGBK RNAV Approaches Added
  .github/CHANGELOG.md
  Airports/EGBK/Active_Runway.txt
  Airports/EGBK/Basic.txt
  Airports/EGBK/Fixes.txt
  Airports/EGBK/Positions.txt
  Airports/EGBK/Runway.txt
Labels: airac
