Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-02, with the labels that each got.

#2219 Fixes #2207 - EGLF Squawk Range Update
  .github/CHANGELOG.md
  Airports/EGLF/Positions.txt
Labels: airac, api-change-needed, ready

#2223 Fixes #2216 - Re-route L603
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L603.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2233 Fixes #2224 - New EGLF SIDs
  .github/CHANGELOG.md
  Airports/EGLF/Fixes.txt
  Airports/EGLF/Sids.txt
Labels: airac, api-change-needed, ready

#2226 Fixes #2215 - Re-route L60
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L60.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2227 Fixes #2218 - Y803 Extended
  .github/CHANGELOG.md
  Airways/RNAV/Upper/Y803.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2236 Fixes #2221 - EGCN RNAV Approaches
  .github/CHANGELOG.md
  Airports/EGCN/Fixes.txt
  Navaids/NDB_All.txt
Labels: airac, ready

#2225 Fixes #2217 - Re-route U/M185
  .github/CHANGELOG.md
  Airways/RNAV/Lower/M185.txt
  Airways/RNAV/Upper/UM185.txt
  Navaids/FIXES_UK.txt
Labels: airac, ready

#2205 Fixes #2204 - EGKK SMR Update
  .github/CHANGELOG.md
  Airports/EGKK/Freetext.txt
  Airports/EGKK/SMR/Labels.txt
  Colours.txt
Labels: enhancement, ready

#2202 Fixes #2195 - EGKK SMR Update
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Labels.txt
  Airports/EGKK/SMR/Regions.txt
  _data/SMR Files/EGKK/Gatwick SMR.kmz
Labels: airac, ready

#2261 Fixes #2259 - Removed EGHI Ground
  .github/CHANGELOG.md
  Airports/EGHI/Ownership.txt
  Airports/EGHI/Positions.txt
  Airports/EGHI/Sector.txt
Labels: api-change-needed, bug

#2270 Fixes #2269 - Add London CTR local flying areas
  .github/CHANGELOG.md
  Airports/EGLD/Airspace.txt
  Airports/EGLM/Airspace.txt
  Airports/EGLM/Basic.txt
  Airports/EGLW/Airspace.txt
  Airports/EGTF/Airspace.txt
Labels: enhancement

#2272 Fixes #2271 - Update Northolt RMA
  .github/CHANGELOG.md
  Airports/EGWU/RMA.txt
  Airports/EGWU/Sector.txt
Labels: bug

#2274 Fixes #2273 - Improve London CTR & London/City CTR Helicopter Routes
  .github/CHANGELOG.md
  Airways/Conventional/Lower/H10.txt
  Airways/Conventional/Lower/H2.txt
  Airways/Conventional/Lower/H3.txt
  Airways/Conventional/Lower/H4.txt
  Airways/Conventional/Lower/H5.txt
  Airways/Conventional/Lower/H7.txt
  Airways/Conventional/Lower/H9.txt
Labels: enhancement

#2276 Issue #2275 - Improve Heathrow Inner CTA
  .github/CHANGELOG.md
  Airports/EGLL/RMA.txt
Labels: enhancement

#2238 Fixes #2229 - EGPF STARs revised
  .github/CHANGELOG.md
  Airports/EGPF/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2240 Fixes #2232 - EGPK STARs Updated
  .github/CHANGELOG.md
  Airports/EGPK/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2253 Fixes #2230 - EGLL SIDs
  .github/CHANGELOG.md
  Airports/EGLL/Sids.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: airac, api-change-needed

#2235 Fixes #2220 - New EGCN SIDs
  .github/CHANGELOG.md
  Airports/EGCN/Fixes.txt
  Airports/EGCN/Sids.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: airac, api-change-needed, ready

#2239 Fixes #2228 - New EGLF STARs
  .github/CHANGELOG.md
  Airports/EGLF/Fixes.txt
  Airports/EGLF/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac

#2237 Fixes #2222 - EGPH STAR Update
  .github/CHANGELOG.md
  Airports/EGPH/Stars.txt
Labels: airac, ready
