Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-08, with the labels that each got.

#1382 Fixes #1380 - GB Coast & Land Mapping Medium Detail
  .github/CHANGELOG.md
  Colours.txt
  Misc/Geo_GB_Coastline Medium Detail.txt
  Misc/Regions_GB Landmass Medium Detail.txt
Labels: enhancement, ready

#2838 Fixes #2827 - Updated EGJJ SMR
  .github/CHANGELOG.md
  Airports/EGJJ/SMR/Geo.txt
  _data/SMR Files/EGJJ/Jersey SMR 2009.kmz
Labels: airac

#2837 Fixes #2826 - Update EGPE Runway Headings
  .github/CHANGELOG.md
  Airports/EGPE/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#2836 Fixes #2828 - EGNM New runway Headings
  .github/CHANGELOG.md
  Airports/EGNM/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#2835 Fixes #2823 - EGHH Runway Heading Update
  .github/CHANGELOG.md
  Airports/EGHH/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#2833 Fixes #2821 - Update EGPD SMR
  .github/CHANGELOG.md
  Airports/EGPD/SMR/Geo.txt
  Airports/EGPD/SMR/Labels.txt
  Airports/EGPD/SMR/Regions.txt
  _data/SMR Files/EGPD/Aberdeen SMR 2009.kmz
Labels: airac

#2832 Fixes #2829 - EGLL Runway Heading Update
  .github/CHANGELOG.md
  Airports/EGLL/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#2831 Fixes #2822 - EGPD Runway Heading Update
  .github/CHANGELOG.md
  Airports/EGPD/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#2815 Fixes #2806 - Fixed AC Clacton static boundary
  .github/CHANGELOG.md
  Sectors/Static/LON/Clacton.txt
Labels: bug

#2810 Fixes #2803 - LC DIR handover prediction
  .github/CHANGELOG.md
  Agreements/Airport/THAMES_LC.txt
  Airports/EGLC/Ownership.txt
Labels: bug

#2809 Fixes #2807 - PC East -> S10 Agreement
  .github/CHANGELOG.md
  Agreements/Internal/East_10.txt
  Agreements/Internal/East_Hum.txt
Labels: procedure-change

#2808 Fixes #2495 - Updated Solent Outbound Agreements
  .github/CHANGELOG.md
  Agreements/Internal/Solent_TCSW.txt
Labels: enhancement

#2805 Fixes #2802 - EGTF New SMR
  .github/CHANGELOG.md
  Airports/EGTF/SMR/Geo.txt
  Airports/EGTF/SMR/Labels.txt
  Airports/EGTF/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGTF/Fairoaks New SMR.kmz
Labels: enhancement

#2801 Fixes #2494 - Slightly diverging lines at EGHH
  .github/CHANGELOG.md
  Airports/EGHH/Centreline.txt
Labels: enhancement

#2800 Fixes #2798 - EGLF Update SMR
  .github/CHANGELOG.md
  Airports/EGLF/Ground Map/Geo.txt
  Airports/EGLF/Ground Map/Labels.txt
Labels: airac

#2799 Fixes #2796 - EGLL Update SMR
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
Labels: airac

#2795 Fixes #2757 - Updated S13 -> LD Severn Group Inbound Agreements
  .github/CHANGELOG.md
  Agreements/Internal/13_D.txt
Labels: procedure-change

#2794 Fixes #2753 - Updated TC SABER->LD SS/GW Outbound Agreements
  .github/CHANGELOG.md
  Agreements/Internal/TCSAB_D.txt
Labels: procedure-change

#2582 Fixes #2419 - Add PC East Splits
  .github/CHANGELOG.md
  Airports/EGCC/Ownership.txt
  Airports/EGGP/Ownership.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/TC - MPC/North.txt
  Ownership/TC - MPC/SE Stafa.txt
  Ownership/TC - MPC/SE Trent.txt
  Sectors/Lines - MPC.txt
Labels: enhancement
