Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-11, with the labels that each got.

#2841 Fixes #2839 - Removed Duplicate Coastline Files
  .github/CHANGELOG.md
  Misc/Geo_Coastline Low Detail.txt
  Misc/Regions_Park Air MAN.txt
Labels: enhancement

#2876 Fixes #2872 - Added REMSI Buffer
  .github/CHANGELOG.md
  Misc/STAR_REMSI Buffer.txt
Labels: procedure-change, ready

#3076 Fixes #3075 - Restore INS VOR
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: bug, ready

#3063 Fixes #3062 - Add Channel Islands to Coastline Geo
  .github/CHANGELOG.md
  Misc/Geo_GB_Coastline Medium Detail.txt
Labels: enhancement, ready

#2903 Fixes #2871 - Added Talla-Galloway Buffer
  .github/CHANGELOG.md
  Misc/STAR_Talla-Galloway Buffer.txt
Labels: procedure-change, ready

#3046 Fixes #3038 - N864 Weekend Airspace Made Selectable
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Conditional - N864 (TLA-ASNUD).txt
Labels: compiler-config-change, enhancement, ready

#3045 Fixes #3037 - N601(D) Conditional Airspace Selectable
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Conditional - N601 (D) FL165-FL195.txt
Labels: compiler-config-change, enhancement, ready

#3044 Fixes #3014 - Added Newcastle (EGNT) SMAA
  .github/CHANGELOG.md
  Airports/EGNT/SMAA.txt
Labels: enhancement, ready

#3043 Fixes #3013 - Added Isle of Man (EGNS) SMAA
  .github/CHANGELOG.md
  Airports/EGNS/SMAA.txt
Labels: enhancement, ready

#3042 Fixes #3012 - Fixed Liverpool (EGGP) SMAA
  .github/CHANGELOG.md
  Airports/EGGP/SMAA.txt
Labels: bug, ready

#2988 Fixes #3003 - Remove duplicate lines from Daventry CTA
  .github/CHANGELOG.md
  ARTCC/High/Daventry CTA.txt
Labels: bug, ready

#2995 Fixes #2994 - EGSY - Update Basic Info
  .github/CHANGELOG.md
  Airports/EGSY/Basic.txt
Labels: bug, ready

#3040 Fixes #3035 - P18 between ADN-NATEB (CDR1) selectable on/off
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Conditional - P18 (ADN-NATEB) CDR1.txt
Labels: compiler-config-change, enhancement, ready

#2996 Fixes #2993 - Renamed Norway FIR to Polaris FIR
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
Labels: enhancement, ready

#3002 Fixes #3000 - Fixed Thames airspace line display
  .github/CHANGELOG.md
  Airports/EGLC/Ownership.txt
Labels: bug, ready

#2700 Fixes #2698 - Added RAMOX and DEXEN Buffers
  .github/CHANGELOG.md
  Misc/STAR_DEXEN Buffer.txt
  Misc/STAR_RAMOX Buffer.txt
Labels: enhancement, procedure-change

#2990 Fixes #2989 - Fixed AC West -> GD APP POMAX Agreement
  .github/CHANGELOG.md
  Agreements/Airport/23_GD.txt
Labels: bug, ready

#2949 Fixes #2947 - Updated PC agreements for Midlands in/outbounds
  .github/CHANGELOG.md
  Agreements/Internal/S29_Sta.txt
  Agreements/Internal/S29_Stafa.txt
  Agreements/Internal/Stafa_S29.txt
  Agreements/Internal/Trent_S29.txt
Labels: compiler-config-change, enhancement, procedure-change

#3066 Fixes #3015 - Fixed Inverness (EGPE) SMAA
  .github/CHANGELOG.md
  Airports/EGPE/SMAA.txt
Labels: bug

#2397 Fixes #2286 - Update Airspace/Line display LFAPP
  .github/CHANGELOG.md
  Airports/EGLF/Ownership.txt
  Airports/EGLF/RMA.txt
  Airports/EGLF/Sector.txt
Labels: enhancement, ready

#2992 Fixes #2991 - Update EGYM Marham to SMR
  .github/CHANGELOG.md
  Airports/EGYM/SMR/Geo.txt
  Airports/EGYM/SMR/Labels.txt
  Airports/EGYM/SMR/Regions.txt
  _data/SMR Files/EGYM/EGYM.kmz
Labels: enhancement

#3034 Fixes # 3033 - Provide notation on conditional airspace bases
  .github/CHANGELOG.md
  Misc/Freetext_Airspace Bases.txt
Labels: bug, ready

#3018 Fixes #3017 - Update EGOV Valley to SMR
  .github/CHANGELOG.md
  Airports/EGOV/SMR/Geo.txt
  Airports/EGOV/SMR/Regions.txt
  _data/SMR Files/EGOV/EGOV.kmz
Labels: enhancement, ready

#3022 Fixes #3021 - Add Waddington SMR
  .github/CHANGELOG.md
  Airports/EGXW/SMR/Geo.txt
  Airports/EGXW/SMR/Labels.txt
  Airports/EGXW/SMR/Regions.txt
  _data/SMR Files/EGXW/EGXW.kmz
Labels: enhancement

#3027 Fixes #3026 - Update EGQL Leuchars to SMR
  .github/CHANGELOG.md
  Airports/EGQL/SMAA.txt
  Airports/EGQL/SMR/Geo.txt
  Airports/EGQL/SMR/Labels.txt
  Airports/EGQL/SMR/Regions.txt
  _data/SMR Files/EGQL/EGQL.kmz
Labels: enhancement, ready

#3029 Fixes #3028 - Add Shawbury SMR
  .github/CHANGELOG.md
  Airports/EGOS/SMR/Geo.txt
  Airports/EGOS/SMR/Regions.txt
  _data/SMR Files/EGOS/EGOS.kmz
Labels: enhancement, ready

#3031 Fixes #3030 - Add Leeming SMR
  .github/CHANGELOG.md
  Airports/EGXE/SMR/Geo.txt
  Airports/EGXE/SMR/Regions.txt
  _data/SMR Files/EGXE/EGXE.kmz
Labels: enhancement, ready

#3041 Fixes #3007 - Fixed Manchester (EGCC) SMAA
  .github/CHANGELOG.md
  Airports/EGCC/SMAA.txt
Labels: bug

#3020 Fixes #3019 - Added new Northolt (EGWU) SMR
  .github/CHANGELOG.md
  Airports/EGWU/SMR/Geo.txt
  Airports/EGWU/SMR/Labels.txt
  Airports/EGWU/SMR/Regions.txt
  _data/SMR Files/EGWU/EGWU.kmz
Labels: enhancement, ready

#3051 Fixes #3050 - Added Culdrose (EGDR) SMR
  .github/CHANGELOG.md
  Airports/EGDR/SMR/GEO.txt
  Airports/EGDR/SMR/Labels.txt
  Airports/EGDR/SMR/Regions.txt
Labels: enhancement

#3049 Fixes #3008 - Corrected Cardiff (EGFF) SMAA
  .github/CHANGELOG.md
  Airports/EGFF/SMAA.txt
Labels: bug

#3054 Fixes #3053 - Added Bristol Radar Buffer Outline
  .github/CHANGELOG.md
  Misc/STAR_Bristol Buffer Zone
Labels: enhancement, ready

#3056 Fixes #3011 - Fixed Jersey (EGJJ) SMAA
  .github/CHANGELOG.md
  Airports/EGJJ/SMAA.txt
Labels: bug

#3059 Fixes #3001 - Updated Contributing Guide to remove references to Core and Slack
  .github/CHANGELOG.md
  .github/Contributing.md
Labels: bug

#3060 Fixes #3016 - Removed Blackpool (EGNH) SMAA
  .github/CHANGELOG.md
  Airports/EGNH/SMAA.txt
Labels: bug

#3061 Fixes #3055 - Moved ARTCC Low Miscellaneous Lines -> STARs
  .github/CHANGELOG.md
  ARTCC/Low/Misc.txt
  Misc/STAR_SHM-OCK Line.txt
  Misc/STAR_XY Line.txt
Labels: enhancement

#3064 Fixes #3009 - Added Bournemouth (EGHH) SMAA
  .github/CHANGELOG.md
  Airports/EGHH/SMAA.txt
Labels: enhancement

#3065 Fixes #3010 - Added Southampton (EGHI) SMAA
  .github/CHANGELOG.md
  Airports/EGHI/SMAA.txt
Labels: enhancement

#3074 Fixes #3073 - Removed EGPU (Tiree) Runway 17/35 (Disused)
  .github/CHANGELOG.md
  Airports/EGPU/Runway.txt
Labels: airac, ready

#3089 Fixes #3081 - EGMD Runway heading updated
  .github/CHANGELOG.md
  Airports/EGMD/Runway.txt
  Doc/Runway track changes.txt
Labels: airac, ready

#3091 Fixes #3077 - Removed EGKK Holding Point 'K'
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Labels.txt
Labels: airac, ready

#3088 Fixes #3084 - EGTB Runway Headings
  Airports/EGTB/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3090 Fixes #3086 - EGPU Runway heading changed
  .github/CHANGELOG.md
  Airports/EGMD/Runway.txt
  Airports/EGPU/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3092 Fixes #3078 - Updated EGAE Runway Heading
  .github/CHANGELOG.md
  Airports/EGAE/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3093 Fixes #3079 - Updated EGHC Runway Heading and Threshold Coordinates
  .github/CHANGELOG.md
  Airports/EGHC/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3095 Fixes #3087 - Updated EGPT Runway Heading
  .github/CHANGELOG.md
  Airports/EGPT/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3025 Fixes #3024 - Update EGYD Cranwell to SMR
  .github/CHANGELOG.md
  Airports/EGYD/SMR/Geo.txt
  Airports/EGYD/SMR/Labels.txt
  Airports/EGYD/SMR/Regions.txt
  _data/SMR Files/EGYD/EGYD.kmz
Labels: enhancement

#3058 Fixes #3005 - Fixed Belfast Aldergrove (EGAA) SMAA
  .github/CHANGELOG.md
  Airports/EGAA/SMAA.txt
Labels: bug

#2814 Fixes #2720 - Irish LOA updates
  .github/CHANGELOG.md
  Agreements/Airport/DUBN_NS.txt
  Agreements/External/8_DUBS.txt
  Agreements/External/8_SNE.txt
  Agreements/External/8_SNL.txt
  Agreements/External/Ant_DUBN.txt
  Agreements/External/DUBN_Ant.txt
  Agreements/External/DUBN_IoM.txt
  Agreements/External/DUBS_8.txt
  Agreements/External/DUBS_IoM.txt
  Agreements/External/IoM_DUBN.txt
  Agreements/External/IoM_SNE.txt
  Agreements/External/Rat_SNE.txt
  Agreements/External/SNE_8.txt
  Agreements/External/SNE_IoM.txt
  Agreements/External/SNE_Rat.txt
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Dublin L18.txt
  Ownership/Non-UK/Dublin.txt
  Ownership/Non-UK/Shannon.txt
  Sectors/Lines - Ireland.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - MPC.txt
  Sectors/Lines - Misc.txt
  Sectors/Lines - PACC.txt
Labels: procedure-change

#3106 Fixes #3052 - Adjust smrmil colour names
  .github/CHANGELOG.md
  Airports/EGDR/SMR/Regions.txt
  Airports/EGDY/SMR/Regions.txt
  Airports/EGOS/SMR/Regions.txt
  Airports/EGOV/SMR/Regions.txt
  Airports/EGQL/SMR/Regions.txt
  Airports/EGVA/SMR/Regions.txt
  Airports/EGVN/SMR/Regions.txt
  Airports/EGWU/SMR/Regions.txt
  Airports/EGXC/SMR/Regions.txt
  Airports/EGXE/SMR/Regions.txt
  Airports/EGXW/SMR/Regions.txt
  Airports/EGYD/SMR/Regions.txt
  Airports/EGYM/SMR/Regions.txt
  Colours.txt
Labels: bug

#3057 Fixes #3006 - Added Belfast City (EGAC) SMAA
  .github/CHANGELOG.md
  Airports/EGAC/SMAA.txt
Labels: enhancement

#3101 Fixes #3082 - EGMD Stand positions/numbering
  .github/CHANGELOG.md
  Airports/EGMD/SMR/Labels.txt
Labels: airac

#3102 Fixes #3099 - Changed STAR_Bristol Buffer Zone to .txt file
  Misc/STAR_Bristol Buffer Zone.txt
Labels: bug

#2283 Fixes #2241 - AC West Optimisation
  .github/CHANGELOG.md
  Agreements/Internal/23_5.txt
  Agreements/Internal/23_8.txt
  Agreements/Internal/35_5.txt
  Agreements/Internal/36_6.txt
  Agreements/Internal/5_23.txt
  Agreements/Internal/5_36.txt
  Agreements/Internal/9_8.txt
  Airports/EGBJ/Ownership.txt
  Airports/EGFF/Ownership.txt
  Airports/EGGD/Ownership.txt
  Airports/EGHQ/Ownership.txt
  Airports/EGJA/Ownership.txt
  Airports/EGJB/Ownership.txt
  Airports/EGJJ/Ownership.txt
  Airports/EGTE/Ownership.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/AC - West/23.txt
  Ownership/AC - West/35.txt
  Ownership/AC - West/36.txt
  Ownership/AC - West/5.txt
  Ownership/AC - West/6.txt
  Ownership/AC - West/8.txt
  Ownership/AC - West/9.txt
  Ownership/AC - West/UL18.txt
  Ownership/Alternate/Airports - LON/AC West.txt
Labels: enhancement

#3094 Fixes #3083 - Updated EGTB Positions and Frequencies (ATC -> AGCS)
  .github/CHANGELOG.md
  Airports/EGTB/Positions.txt
  Airports/EGTB/Positions_Mentor.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#3100 Fixes #3098 - Added EGLL AMAN Range Ring
  .github/CHANGELOG.md
  Misc/STAR_EGLL AMAN Range Ring.txt
Labels: enhancement

#3153 Fixes #3150 - EISN sector ID error
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
Labels: bug

#3151 Fixes #2980 - Fixed KB TWR online ring displaying erroneously
  .github/CHANGELOG.md
  Airports/EGKB/Ownership.txt
Labels: bug

#3105 Fixes #3104 - Removed Duplicate Aberporth File
  .github/CHANGELOG.md
  Airports/Other/EGUC.txt
Labels: bug

#3136 Fixes #3113 - EISN N Frequency Error
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
Labels: bug

#3110 Fixes #3103 - Corrected ownership within the Channel Islands
  .github/CHANGELOG.md
  Airports/EGJA/Ownership.txt
  Airports/EGJB/Ownership.txt
  Airports/EGJJ/Ownership.txt
Labels: bug

#3155 Fixes #3154 - Updated French (Paris, Brest & Reims) Sectors
  .github/CHANGELOG.md
  Agreements/External/6_RRhigh.txt
  Agreements/External/9_RRhigh.txt
  Agreements/External/9_RRhighN.txt
  Agreements/External/EEhighN_D.txt
  Agreements/External/FFhighE_D.txt
  Agreements/External/FFlowE_D.txt
  Agreements/External/FFlowE_TCSE.txt
  Agreements/External/FFlow_D.txt
  Agreements/External/FFlow_TCSE.txt
  Agreements/External/RRhighN_6.txt
  Agreements/External/RRhighN_S.txt
  Agreements/External/RRhigh_6.txt
  Agreements/External/RRhigh_S.txt
  Agreements/External/RRlowN_S.txt
  Agreements/External/RRlow_JJ.txt
  Agreements/External/RRlow_S.txt
  Agreements/External/S_FFhighW.txt
  Agreements/External/S_FFlow.txt
  Agreements/External/S_FFlowW.txt
  Agreements/External/S_RRhigh.txt
  Agreements/External/S_RRhighE.txt
  Agreements/External/S_RRhighN.txt
  Airports/EGJJ/Sector.txt
  Misc/Positions_Area Positions 2 External.txt
  Ownership/AC - South/Dover.txt
  Ownership/Non-UK/Brest.txt
  Ownership/Non-UK/Paris.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - LACC.txt
  Sectors/Static/LON/Dover.txt
Labels: bug, procedure-change

#3140 Fixes #3125 - EGBB STAR Changes
  .github/CHANGELOG.md
  Airports/EGBB/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac

#3122 Fixes #3117 - EGLC & EGKB new STARs added
  .github/CHANGELOG.md
  Airports/EGKB/Stars.txt
  Airports/EGLC/Stars.txt
Labels: airac

#3137 Fixes #3123 - Essex STAR Changes
  .github/CHANGELOG.md
  Airports/EGGW/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac

#3121 Fixes #3116 - EGMC STAR Updates
  .github/CHANGELOG.md
  Airports/EGMC/Stars.txt
Labels: airac

#3132 Fixes #3130 - EGGD new stand 7N
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
Labels: airac, api-change-needed

#3152 Fixes #3147 - Southend Director Frequency Change 132.450 -> 128.950
  .github/CHANGELOG.md
  Airports/EGMC/Positions.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#3144 Fixes #3143 - Changes to Fixes
  .github/CHANGELOG.md
  Navaids/FIXES_Old.txt
  Navaids/FIXES_UK.txt
Labels: airac

#3139 Fixes #3129 - EGFE A/G Frequency Change
  .github/CHANGELOG.md
  Airports/Other/EGFE.txt
Labels: airac

#3109 Fixes #3108 - Update to Scottish West + Deancross frequency
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK.txt
Labels: api-change-needed, procedure-change

#3131 Fixes #3124 - East Midlands STARs update
  .github/CHANGELOG.md
  Airports/EGNX/Stars.txt
Labels: airac

#2874 Fixes #2589 - Airspace in the Jersey Zone
  .github/CHANGELOG.md
  Agreements/Airport/6_JJ.txt
  Agreements/Airport/JJ_6.txt
  Agreements/Airport/JJ_S.txt
  Agreements/Airport/S_JJ.txt
  Agreements/External/RRlow_JJ.txt
  Airports/EGJJ/Ownership.txt
  Airports/EGJJ/Sector.txt
Labels: procedure-change

#3119 Fixes #3118 - Gatwick (EGKK) STAR changes
  .github/CHANGELOG.md
  Airports/EGKK/Fixes.txt
  Airports/EGKK/Stars.txt
Labels: airac

#3128 Fixes #3120 - Heathrow (EGLL) STAR changes
  .github/CHANGELOG.md
  Airports/EGLL/Fixes.txt
  Airports/EGLL/Stars.txt
  Airports/EGWU/Stars.txt
Labels: airac

#3169 Fixes #3168 - Separate Portsmouth CTA11/13
  .github/CHANGELOG.md
  ARTCC/High/Conditional -Portsmouth CTA.txt
  ARTCC/High/Portsmouth CTA.txt
Labels: compiler-config-change, enhancement

#3167 Fixes #3164 - NITON CTA 2 Made Selectable
  .github/CHANGELOG.md
  ARTCC/High/Conditional - NITON CTA 2.txt
  ARTCC/High/NITON CTA.txt
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: compiler-config-change, enhancement

#3166 Fixes #3165 - Portsmouth CTA 12 Airspace Base
  .github/CHANGELOG.md
  Misc/Freetext_Airspace Bases.txt
Labels: bug

#3162 Fixes #3161 - Added additional ScAC South split
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/Alternate/Airports - SCO/Tyne.txt
  Ownership/ScAC - East/Humber.txt
  Ownership/ScAC - East/Tyne.txt
Labels: enhancement

#3160 Fixes #3158 - Added 23 -> LS FF/FH/SY Outbound Agreement Missing Arrow
  .github/CHANGELOG.md
  Agreements/Internal/23_S.txt
Labels: bug

#3159 Fixes #3157 - Corrected 8 -> 23 BB Inbound Agreement Error
  .github/CHANGELOG.md
  Agreements/Internal/8_23.txt
Labels: bug

#3146 Fixes #3145 - Added Heathrow (EGLL) HAP to SMR
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
Labels: bug

#3142 Fixes #3141 - OCAS Regions Adjacent Berry Head CTA2/4 Inaccurate
  .github/CHANGELOG.md
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: bug

#3114 Fixes #2028 - MPC frequency reallocations and sector splits
  .github/CHANGELOG.md
  Airports/EGBB/Ownership.txt
  Airports/EGCC/Ownership.txt
  Airports/EGCN/Ownership.txt
  Airports/EGGP/Ownership.txt
  Airports/EGNH/Ownership.txt
  Airports/EGNJ/Ownership.txt
  Airports/EGNM/Ownership.txt
  Airports/EGNS/Ownership.txt
  Airports/EGNT/Ownership.txt
  Airports/EGNV/Ownership.txt
  Misc/Positions_Area Positions 1 UK.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/Alternate/Airports - MPC/Isle of Man.txt
  Ownership/Alternate/Airports - MPC/NorthEast.txt
  Ownership/Alternate/Airports - MPC/SouthEast.txt
  Ownership/Alternate/Airports - MPC/Wallasey.txt
  Ownership/TC - MPC/East.txt
  Ownership/TC - MPC/IoM.txt
  Ownership/TC - MPC/North.txt
  Ownership/TC - MPC/SE Trent.txt
  Ownership/TC - MPC/Wallasey.txt
Labels: api-change-needed, procedure-change

#3072 Fixes #2963 - Updated 7 -> IoM Midlands Group inbound agreements
  .github/CHANGELOG.md
  Agreements/Internal/7_IoM.txt
Labels: procedure-change

#3069 Fixes #2966 - Updated Stafa -> S29 Midlands outbound agreements
  .github/CHANGELOG.md
  Agreements/Internal/Stafa_S29.txt
Labels: procedure-change

#3070 Fixes #2968 - Updated S29 -> 7 EGNT NV outbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/S29_7.txt
Labels: procedure-change

#3067 Fixes #2964 - Updated S29 -> 7 Severn Group & TE outbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/S29_7.txt
Labels: procedure-change

#2869 Fixes #2818 - Changes to Scottish ownership in the area west of the TMA
  .github/CHANGELOG.md
  Agreements/Airport/Cen_PF.txt
  Agreements/Airport/Mon_PF.txt
  Ownership/Non-UK/Shanwick.txt
  Ownership/ScAC - East/Montrose.txt
  Ownership/ScAC - West/Central.txt
  Ownership/ScAC - West/Deancross.txt
  Ownership/ScAC - West/Rathlin.txt
  Ownership/TC - STC/Antrim.txt
  Ownership/TC - STC/Central.txt
  Ownership/TC - STC/Galloway.txt
  Ownership/TC - STC/Tay.txt
  Sectors/Lines - PACC.txt
  Sectors/Static/SCO/East.txt
  Sectors/Static/SCO/Rathlin.txt
  Sectors/Static/SCO/West.txt
  Sectors/Static/STC/Antrim.txt
  Sectors/Static/STC/Galloway.txt
  Sectors/Static/STC/TMA.txt
  Sectors/Static/STC/Talla.txt
Labels: procedure-change

#3174 Fixes #3173 - Sector ownership conflict with EGPC_TWR and PC SE Trent
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/TC - MPC/SE Trent.txt
Labels: bug

#3149 Fixes #2443 - Added EHAA high -> Humber agreement
  .github/CHANGELOG.md
  Agreements/External/AAhigh_Hum.txt
  Agreements/External/Hum_AAhigh.txt
Labels: enhancement

#3195 Fixes #3192 - Amended Shannon East Frequency
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
Labels: procedure-change

#3182 Fixes #3179 - S14 -> TC Saber KK inbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/14_TCSAB.txt
Labels: bug

#2998 Fixes #2997 - Improve Border with EHAA/EBBU
  .github/CHANGELOG.md
  ARTCC/High/ABNED Delegated Airspace.txt
  ARTCC/High/AMRIV Delegated Airspace.txt
  ARTCC/High/Clacton CTA.txt
  ARTCC/High/EBBU Brussels FIR.txt
  ARTCC/High/EGTT London FIR.txt
  ARTCC/High/EHAA Amsterdam FIR.txt
  ARTCC/High/IBNOS Delegated Airspace.txt
  ARTCC/High/SASKI Delegated Airspace.txt
  ARTCC/High/Southern CTA.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/Non-UK/Brussels.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - LACC.txt
Labels: bug, enhancement

#3198 Fixes #3196 - EGHO missing holding point
  .github/CHANGELOG.md
  Airports/EGHO/SMR/Geo.txt
  Airports/EGHO/SMR/Labels.txt
Labels: bug

#3208 Swanwick Fixes
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK.txt
  Ownership/Swanwick Mil/VV.txt
Labels: bug

#3183 Fixes #3181 - Updated S23 <-> BB agreement via FUA
  .github/CHANGELOG.md
  Agreements/Airport/23_BB.txt
  Agreements/Airport/BB_23.txt
Labels: procedure-change

#3188 Fixes #3185 - Updated TC WELIN -> BB APP HON inbound agreement
  .github/CHANGELOG.md
  Agreements/Airport/TCWEL_BB.txt
Labels: procedure-change

#3189 Fixes #3184 - Updated S7 -> IOM Midlands inbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/7_IoM.txt
Labels: procedure-change

#3190 Fixes #2804 - Updated EGBB APP airspace & sector ownership
  .github/CHANGELOG.md
  Agreements/Airport/BB_BB.txt
  Airports/EGBB/Ownership.txt
  Airports/EGBB/RMA.txt
  Airports/EGBB/Sector.txt
Labels: enhancement

#3199 Fixes #3180 - Added Rathlin -> PC IOM COPX level capping
  .github/CHANGELOG.md
  Agreements/Internal/Rat_IoM.txt
Labels: procedure-change

#3201 Fixes #3200 - Reformatted FF -> AC West Outbound Agreements
  .github/CHANGELOG.md
  Agreements/Airport/FF_23.txt
  Agreements/Airport/FF_5.txt
  Agreements/Airport/FF_6.txt
  Agreements/Airport/FF_8.txt
Labels: enhancement

#3213 Fixes #3212 - Reorder EGPE APP/RAD Positions
  .github/CHANGELOG.md
  Airports/EGPE/Positions.txt
Labels: bug

#3216 Fixes #3215 - Added Boscombe Down (EGDM) Runways
  .github/CHANGELOG.md
  Airports/EGDM/Runway.txt
Labels: bug

#3219 Fixes #3193 - Added Deancross -> S3 COPX Level Capping
  .github/CHANGELOG.md
  Agreements/Internal/Dcs_3.txt
Labels: procedure-change

#3223 Fixes #3217 - Further French sectorisation updates
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Brest.txt
  Ownership/Non-UK/Paris.txt
  Ownership/Non-UK/Reims.txt
Labels: procedure-change

#3225 Fixes #3224 - Fixed PEMAK Triangle ownership below FL245
  .github/CHANGELOG.md
  Ownership/AC - West/9.txt
Labels: bug

#3187 Fixes #3186 #3194 - Added EDYY Delta & Jever Sector Ownership; COPX changes
  .github/CHANGELOG.md
  Agreements/External/10_AA.txt
  Agreements/External/10_AAhigh.txt
  Agreements/External/10_AAlow.txt
  Agreements/External/10_YY-D.txt
  Agreements/External/12_AA.txt
  Agreements/External/AA_14.txt
  Agreements/External/AA_Hum.txt
  Agreements/External/AAhigh_13.txt
  Agreements/External/AAhigh_14.txt
  Agreements/External/AAhigh_Hum.txt
  Agreements/External/AAlow_14.txt
  Agreements/External/Hum_AA.txt
  Agreements/External/TCRED_AA.txt
  Agreements/External/TCRED_AAlow.txt
  Agreements/External/YY-D_13.txt
  Agreements/External/YY-D_14.txt
  Agreements/External/YY-D_Hum.txt
  Misc/Positions_Area Positions 2 External.txt
  Ownership/AC - Central/13.txt
  Ownership/AC - Central/14.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/Non-UK/Maastricht.txt
  Ownership/ScAC - East/Humber.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - PACC.txt
Labels: enhancement, procedure-change

#3203 Fixes 3202 - Added missing fix to EGGD ADVED1A STAR
  .github/CHANGELOG.md
  Airports/EGGD/Stars.txt
Labels: bug

#3210 Fixes #3209 - Removed Humber->East MTMA/Mids inbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/Hum_East.txt
Labels: procedure-change

#3112 Fixes #3107 - Added Edinburgh-Glasgow 3 NM buffer zone
  .github/CHANGELOG.md
  Misc/STAR_Edinburgh-Glasgow Buffer.txt
Labels: compiler-config-change, procedure-change

#3222 Fixes #3221 - Fixed JJ ownership to reflect new West splits
  .github/CHANGELOG.md
  Airports/EGJJ/Ownership.txt
Labels: bug

#3171 Fixes #3127 - New London City (EGLC) VRPs
  .github/CHANGELOG.md
  Airports/EGLC/VRPs.txt
Labels: airac

#3172 Fixes #3133 - New Heathrow (EGLL) VRPs
  .github/CHANGELOG.md
  Airports/EGLL/VRPs.txt
Labels: airac

#3176 Fixes #3134 - London Helicopter Route Changes
  .github/CHANGELOG.md
  Airports/EGLC/Freetext.txt
Labels: airac

#3206 Fixes #3205 - S10 -> East - Westbound Agreements
  .github/CHANGELOG.md
  Agreements/Internal/10_East.txt
Labels: procedure-change

#3191 Fixes #3170 - Added Sector 4 splitting functionality
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/AC - North/4.txt
Labels: enhancement

#2936 Fixes #2935 - TC Mids to cover TCNW top-down
  .github/CHANGELOG.md
  Airports/EGGW/Ownership.txt
  Airports/EGLL/Ownership.txt
  Airports/EGSC/Ownership.txt
  Airports/EGSS/Ownership.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/TC - LTC/London TC NW.txt
Labels: procedure-change

#3226 Fixes #2935 (Part 2) - Updated Adjacent airports TC NW to reflect TC M top-down of TC NW
  Ownership/Alternate/Airports - LTC/NW.txt
Labels: procedure-change

#3228 Fixes #3227 - Fixed formatting of EGFH runway file
  .github/CHANGELOG.md
  Airports/EGFH/Runway.txt
Labels: bug

#3211 Fixes #3197 - Fixed TC NE (LAM/LOREL) top-down ownership
  .github/CHANGELOG.md
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC LOREL.txt
Labels: bug

#3220 Fixes #3218 - Removed unused sectors from JJ
  .github/CHANGELOG.md
  Airports/EGJJ/Sector.txt
Labels: bug
