Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-05, with the labels that each got.

#2569 Fixes #2567 - Add EGMD Lydd VRPs
  .github/CHANGELOG.md
  Airports/EGMD/VRPs.txt
Labels: enhancement

#2568 Fixes #2566 - Update EGMD Lydd Tower Frequency
  .github/CHANGELOG.md
  Airports/EGMD/Positions.txt
Labels: bug

#2564 Fixes #2563 - Re-order SKERY and OYSTA SIDs from EGJJ
  .github/CHANGELOG.md
  Airports/EGJJ/Sids.txt
Labels: bug

#2565 Fixes #2504 TCWEL>S28 EGKK Agreement
  .github/CHANGELOG.md
  Agreements/Internal/TCWEL_28.txt
Labels: bug

#2562 Fixes #2552 - Update EGHH SMR
  .github/CHANGELOG.md
  Airports/EGHH/SMR/Geo.txt
  Airports/EGHH/SMR/Labels.txt
  Airports/EGHH/SMR/Regions.txt
Labels: bug

#2556 Fixes #2555 - Fixed TC Welin -> NXAPP COPX
  .github/CHANGELOG.md
  Agreements/Airport/TCWEL_NX.txt
Labels: bug, ready

#2549 Fixes #2548 - Amended Bristol Region Naming Error
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Regions.txt
Labels: bug, ready

#2497 Fixes #2496 - Fixed D->BU inbound agreements
  .github/CHANGELOG.md
  Agreements/External/D_BU.txt
  Agreements/External/D_BUhigh.txt
Labels: bug, ready

#2484 Fixes #2483 - Updated Brussels ownership with 'fallback' to EBBU_E
  .github/CHANGELOG.md
  Ownership/Non-UK/Brussels.txt
Labels: enhancement, ready

#2482 Fixes #2481 - Update EGTE Squawks
  .github/CHANGELOG.md
  Airports/EGTE/Positions.txt
  Airports/EGTE/Positions_Mentor.txt
Labels: bug, ready

#2501 Fixes #2500 - Incorrect colour definitions
  .github/CHANGELOG.md
  Airports/EGBP/SMR/Geo.txt
  Airports/EGLF/Fixes.txt
  Colours.txt
  Navaids/FIXES_General RNAV.txt
Labels: bug

#2540 Fixes #2517 - EGTE SMR Update
  .github/CHANGELOG.md
  Airports/EGTE/SMR/Labels.txt
Labels: airac, bug, ready

#2539 Fixes #2521 - EGLL SMR Update
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
Labels: airac, ready

#2529 Fixes #2522 - EGLL SMR - add WIP
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Regions.txt
Labels: ready

#2526 Fixes #2518 - Amended VRPs in NW England
  .github/CHANGELOG.md
  Airports/EGCB/VRPs.txt
  Airports/EGCC/VRPs.txt
  Airports/EGGP/VRPs.txt
Labels: airac

#2341 Fixes #2287 - Updated EGLL RMA
  .github/CHANGELOG.md
  Airports/EGLL/RMA.txt
  Airports/EGLL/Sector.txt
Labels: enhancement

#2449 Fixes #2448 - EGPD SMR Update
  .github/CHANGELOG.md
  Airports/EGPD/SMR/Geo.txt
  Airports/EGPD/SMR/Regions.txt
  _data/SMR Files/EGPD/Aberdeen SMR.kmz
Labels: enhancement

#2492 Fixed #2489 - Fixed categories for [GEO] entries
  .github/CHANGELOG.md
  Airports/EGWU/Ground Map/Geo.txt
  Airports/EGXC/Ground Map/Geo.txt
  Airports/EGYD/Ground Map/Geo.txt
  Airports/EGYM/Ground Map/Geo.txt
  Misc/Geo_City Transition Tracks.txt
  Misc/Geo_Coastline Low Detail.txt
  Misc/Geo_MSA.txt
  Misc/Geo_Merseyside Coastline.txt
  Misc/Geo_Motorways.txt
  Misc/Geo_Rivers.txt
Labels: bug

#2527 Fixes #2523 - EGGW Runway Designator Changed
  .github/CHANGELOG.md
  Agreements/Airport/GW_TCNW.txt
  Airports/EGGW/Active_Runway.txt
  Airports/EGGW/Centreline.txt
  Airports/EGGW/Runway.txt
  Airports/EGGW/SMR/Regions.txt
  Airports/EGGW/Sids.txt
  Airports/EGGW/Stars.txt
  UK.rwy
Labels: airac

#2446 Fixes #2444 - ScTMA agreements
  .github/CHANGELOG.md
  Agreements/Internal/Gal_Tal.txt
  Agreements/Internal/Tal_Gal.txt
Labels: enhancement, ready

#2477 Fixes #2379 - Removed Fairoaks NDB
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac, ready

#2491 Fixed #2490 - Removed definition of gate colour
  .github/CHANGELOG.md
  Colours.txt
  _data/Old/Closed Airfields/EGTG/Ground Map/Geo.txt
Labels: bug, ready

#2503 Fixes #2502 - Adds missing EGPK VRP
  .github/CHANGELOG.md
  Airports/EGPK/VRPs.txt
Labels: enhancement, ready

#2514 Fixes #2507 - EGBB SMR Stands
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Labels.txt
Labels: bug, ready

#2525 Fixes #2520 - Updated EGLC Threshold Coordinates
  .github/CHANGELOG.md
  Airports/EGLC/Runway.txt
Labels: airac, ready

#2533 Fixes #2510 - Enhanced TC Welin -> BB inbounds via HON
  .github/CHANGELOG.md
  Ownership/TC - LTC/London TC COWLY.txt
Labels: bug, ready

#2534 Fixes #2511 - Added TC Cowly -> BB GROVE 1B agreements
  .github/CHANGELOG.md
  Agreements/Airport/TCCOW_BB.txt
Labels: enhancement, ready

#2535 Fixes #2506 - Fixed TC Welin -> S28 LTMA outbound auto handoff
  .github/CHANGELOG.md
  Agreements/Internal/TCWEL_28.txt
Labels: bug, ready

#2537 Fixes #2532 - Removed EGTG and added EGSY agreements
  .github/CHANGELOG.md
  Agreements/Airport/23_GD.txt
  Agreements/Airport/5_FF.txt
  Agreements/Airport/6_FF.txt
  Agreements/Airport/8_FF.txt
  Agreements/Airport/FF_5.txt
  Agreements/Airport/FF_6.txt
  Agreements/Airport/FF_8.txt
  Agreements/Airport/GD_23.txt
  Agreements/External/RRhigh_6.txt
  Agreements/Internal/13_D.txt
  Agreements/Internal/23_S.txt
  Agreements/Internal/S_23.txt
Labels: enhancement, ready

#2541 Fixes #2513 - LD -> TC Welin Midlands inbound agreement
  .github/CHANGELOG.md
  Agreements/Internal/D_TCWEL.txt
Labels: enhancement, ready

#2554 Fixes #2553 - Add SOLENT Forest Gate
  .github/CHANGELOG.md
  Misc/STAR_SOLENT Forest Gate.txt
Labels: enhancement, ready

#2551 Fixes #2550 - Fixed BIRD line display to Scottish
  .github/CHANGELOG.md
  Sectors/Lines - PACC.txt
Labels: bug, ready

#2543 Fixes #2528 - Updated TC NE ownership
  .github/CHANGELOG.md
  Ownership/Alternate/Airports - LTC/NE.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC NE.txt
Labels: bug, ready

#2478 Fixes #2476 - Adds Southend PDR's
  .github/CHANGELOG.md
  Airports/EGMC/Sids.txt
Labels: enhancement, ready

#2578 Fixes #2577 - Antrim->Galloway ScTMA inbound agreements
  .github/CHANGELOG.md
  Agreements/Airport/Ant_PK.txt
  Agreements/Airport/Gal_PK.txt
  Agreements/Internal/Ant_Gal.txt
  Ownership/TC - STC/Galloway.txt
Labels: enhancement

#2575 Fixes #2574 - Added St Athan EGSY basic sector file requirements
  .github/CHANGELOG.md
  Airports/EGSY/Active_Runway.txt
  Airports/EGSY/Airspace.txt
  Airports/EGSY/Ownership.txt
  Airports/EGSY/Positions.txt
  Airports/EGSY/Runway.txt
  Airports/EGSY/Sector.txt
  Doc/UK VATSIM frequencies.txt
  Ownership/Alternate/Airports - LON/AC West.txt
  UK.rwy
Labels: enhancement

#2545 Fixes #2544 - Updated references to MAN --> PC
  .github/CHANGELOG.md
  Airports/EGBB/Ownership.txt
  Airports/EGCC/Ownership.txt
  Airports/EGCN/Ownership.txt
  Airports/EGGP/Ownership.txt
  Airports/EGNJ/Ownership.txt
  Airports/EGNM/Ownership.txt
  Airports/EGNS/Ownership.txt
  Airports/EGNT/Ownership.txt
  Airports/EGNV/Ownership.txt
  Misc/Positions_Area Positions 1 UK.txt
  Misc/Positions_Area Positions 3 UK.txt
  Ownership/Alternate/Airports - MAN/East.txt
  Ownership/Alternate/Airports - MAN/West.txt
  Ownership/Alternate/Airports - MPC/East.txt
  Ownership/Alternate/Airports - MPC/Isle of Man.txt
  Ownership/Alternate/Airports - MPC/Wallasey.txt
  Ownership/TC - MAN/East.txt
  Ownership/TC - MAN/IoM.txt
  Ownership/TC - MAN/North.txt
  Ownership/TC - MAN/S29.txt
  Ownership/TC - MAN/SE Stafa.txt
  Ownership/TC - MAN/SE Trent.txt
  Ownership/TC - MAN/Wallasey.txt
  Ownership/TC - MPC/East.txt
  Ownership/TC - MPC/IoM.txt
  Ownership/TC - MPC/North.txt
  Ownership/TC - MPC/S29.txt
  Ownership/TC - MPC/SE Stafa.txt
  Ownership/TC - MPC/SE Trent.txt
  Ownership/TC - MPC/Wallasey.txt
  Sectors/Lines - MPC.txt
  Sectors/Static/MPC/PC E.txt
  Sectors/Static/MPC/PC W.txt
Labels: enhancement, ready

#2516 Fixes #2505 - Added LOREL1R to the Essex Clutch STARs
  .github/CHANGELOG.md
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
Labels: ready

#2547 Fixes #2546 - EGCB SMR Update
  .github/CHANGELOG.md
  Airports/EGCB/EGCB.kmz
  Airports/EGCB/Ground Map/Geo.txt
  Airports/EGCB/SMR/Geo.txt
  Airports/EGCB/SMR/Labels.txt
  Airports/EGCB/SMR/Regions.txt
Labels: enhancement, ready

#2586 Fixes #2584 - Bugs in NW England VRPs
  Airports/EGCB/VRPs.txt
  Airports/EGCC/VRPs.txt
  Airports/EGGP/VRPs.txt
  _data/SMR Files/EGCB/EGCB.kmz
Labels: bug

#2585 Fixes #2583 - Bug in Agreements D->BU
  Agreements/External/D_BU.txt
Labels: bug
