Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-12, with the labels that each got.

#3177 Fixes #3111 - Added Scottish TMA local areas and Glasgow Designated Area
  .github/CHANGELOG.md
  Airports/EGPF/Ownership.txt
  Airports/EGPF/RMA.txt
  Airports/EGPF/Sector.txt
  Airports/EGPH/Ownership.txt
  Airports/EGPH/RMA.txt
  Airports/EGPH/Sector.txt
  Airports/EGPK/Ownership.txt
  Airports/EGPK/RMA.txt
  Ownership/ScAC - West/Rathlin.txt
Labels: procedure-change

#3207 Fixes #3204 - Newcastle Radar Sector lines not displayed
  .github/CHANGELOG.md
  Airports/EGNT/Sector.txt
  Airports/EGNV/Ownership.txt
  Airports/EGNV/Sector.txt
Labels: bug

#3231 Fixes #3214 - Leeds airspace delegation lines added
  .github/CHANGELOG.md
  Airports/EGNM/RMA.txt
Labels: enhancement

#3230 Fixes #3178 - Add Hawarden (EGNR) ownership
  .github/CHANGELOG.md
  Airports/EGNR/Ownership.txt
  Airports/EGNR/Sector.txt
Labels: bug

#3256 Fixes #3238 - Birmingham (EGBB) Corrected holding labels.
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Labels.txt
Labels: bug

#3252 Fixes #3249 - Updated EGHE Runway Headings
  .github/CHANGELOG.md
  Airports/EGHE/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3251 Fixes #3242 - Added EGBB/EGNX Buffer Zone
  .github/CHANGELOG.md
  Airports/EGBB/RMA.txt
Labels: enhancement

#3253 Fixes #3250 - Updated EGPO (Stornoway) Runway and NDB Data
  .github/CHANGELOG.md
  Airports/EGPO/Runway.txt
  Doc/Runway track changes.txt
  Navaids/NDB_All.txt
Labels: airac

#3246 Fixes #3243 Blackpool (EGNH) Runway Headings Update
  .github/CHANGELOG.md
  Airports/EGNH/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3248 Fixes #3247 - Updated EGSS Runway Headings
  .github/CHANGELOG.md
  Airports/EGSS/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3156 Fixes #3135 - Thames/Southend Buffer and minor RMA change
  .github/CHANGELOG.md
  Airports/EGLC/Ownership.txt
  Airports/EGLC/RMA.txt
  Airports/EGLC/Sector.txt
  Misc/STAR_Thames-Southend Buffer.txt
Labels: enhancement, procedure-change

#3245 Fixes #3244 - Added Jersey Approach AoR Static Boundaries
  .github/CHANGELOG.md
  Airports/EGJJ/RMA.txt
Labels: enhancement

#3254 Fixes #3240 - Fixed Warton + Blackpool Sector Display Error
  .github/CHANGELOG.md
  Airports/EGNO/Ownership.txt
Labels: bug

#3278 Fixes #3277 - Updated Midlands Radar Gate
  .github/CHANGELOG.md
  Misc/STAR_Midlands Gate.txt
Labels: enhancement

#3279 Fixes #2733 - EGNS Runway 08 Position and Centreline
  .github/CHANGELOG.md
  Airports/EGNS/Centreline.txt
  Airports/EGNS/Runway.txt
Labels: bug

#3281 Fixes #3280 - Fixes Innacurate EGCC Centrelines
  .github/CHANGELOG.md
  Airports/EGCC/Centreline.txt
Labels: bug

#3284 Fixes #3283 - Fixes Inaccurate EGGP Centrelines and Runway Heading.
  .github/CHANGELOG.md
  Airports/EGGP/Centreline.txt
  Airports/EGGP/Runway.txt
Labels: bug

#3239 Fixes #3229 - Added Observing LTC_CTR Alternative Ownership Functionality
  .github/CHANGELOG.md
  Airports/EGGW/Ownership.txt
  Airports/EGKA/Ownership.txt
  Airports/EGKB/Ownership.txt
  Airports/EGKK/Ownership.txt
  Airports/EGLC/Ownership.txt
  Airports/EGLF/Ownership.txt
  Airports/EGLL/Ownership.txt
  Airports/EGMC/Ownership.txt
  Airports/EGMD/Ownership.txt
  Airports/EGSC/Ownership.txt
  Airports/EGSS/Ownership.txt
  Airports/EGWU/Ownership.txt
  Ownership/Alternate/Airports - LTC/NE.txt
  Ownership/Alternate/Airports - LTC/NW.txt
  Ownership/Alternate/Airports - LTC/SE.txt
  Ownership/Alternate/Airports - LTC/SW.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC NE.txt
  Ownership/TC - LTC/London TC NW.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC SW.txt
Labels: enhancement

#3236 EGNH Frequency Changes
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac

#3237 Fixes #3232 - Copenhagen Ownership Update
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
  Ownership/Non-UK/Copenhagen.txt
Labels: procedure-change

#3290 Fixed #3289 - Ownership in SE STAFA
  .github/CHANGELOG.md
  Airports/EGGP/Ownership.txt
  Ownership/TC - MPC/SE Stafa.txt
Labels: bug

#3288 Fixes #3286 - Improve London City (EGLC) SMR style
  .github/CHANGELOG.md
  Airports/EGLC/SMR/Geo.txt
  Airports/EGLC/SMR/Labels.txt
  Airports/EGLC/SMR/Regions.txt
  _data/SMR Files/EGLC/EGLC SMR 20-03.kmz
  _data/SMR Files/EGLC/EGLC SMR Helper 20-03.kmz
Labels: enhancement

#3273 Fixes #3272 - Adds Newquay (EGHQ) Standard Routings
  .github/CHANGELOG.md
  Airports/EGHQ/Sids.txt
  Airports/EGHQ/Stars.txt
Labels: enhancement

#3318 Fixes #3315 - Added Bembridge (EGHJ) Radio Position
  .github/CHANGELOG.md
  Airports/EGHJ/Positions.txt
Labels: enhancement

#3319 Fixes #3316 - Added Lee-On-Solent (EGHF) Information Position
  .github/CHANGELOG.md
  Airports/EGHF/Basic.txt
  Airports/EGHF/Positions.txt
Labels: enhancement

#3320 Fixes #3317 - Added Sandown (EGHN) Radio Position
  .github/CHANGELOG.md
  Airports/EGHN/Basic.txt
  Airports/EGHN/Positions.txt
Labels: enhancement

#3327 Fixes #3325 - Added Goodwood (EGHR) Information Position
  .github/CHANGELOG.md
  Airports/EGHR/Positions.txt
Labels: enhancement

#3326 Fixes #3322 Add Lee-On-Solent (EGHF) SMR
  .github/CHANGELOG.md
  Airports/EGHF/Runway.txt
  Airports/EGHF/SMR/Geo.txt
  Airports/EGHF/SMR/Labels.txt
  Airports/EGHF/SMR/Regions.txt
  _data/SMR Files/EGHF/EGHF.kmz
Labels: enhancement
