Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2020-04, with the labels that each got.

#2357 Fixes #2356 - Amsterdam Ownership
  .github/CHANGELOG.md
  Ownership/Non-UK/Amsterdam.txt
Labels: enhancement, ready

#2337 Fixes #2336 - Corrected frequency for EGPH DEL
  .github/CHANGELOG.md
  Airports/EGPH/Positions.txt
Labels: bug, ready

#2284 Fixes #2196 - New Agreements in TC NW for City & Southend outbounds
  .github/CHANGELOG.md
  Agreements/Internal/TCNE_TCNW.txt
  Agreements/Internal/TCNW_S.txt
  Agreements/Internal/TCNW_TCSW.txt
Labels: enhancement, ready

#2340 Fixes #2177 - Fixed S10->* NT/NV inbound agreements
  .github/CHANGELOG.md
  Agreements/Internal/10_East.txt
  Agreements/Internal/10_Mon.txt
Labels: bug, ready

#2457 Fixes #2447 - Agreements for EB** inbounds
  .github/CHANGELOG.md
  Agreements/External/D_BUlow.txt
Labels: bug

#2414 Fixes #2399 - Fixed S12->EHAA inbound agreements
  .github/CHANGELOG.md
  Agreements/External/12_AA.txt
  Agreements/External/12_AAhigh.txt
Labels: bug, ready

#2318 Fixes #2313 - CNS07>LEDLA and SID redesig
  .github/CHANGELOG.md
  Airports/EGCN/Fixes.txt
  Airports/EGCN/Sids.txt
Labels: airac, ready

#2349 Fixes #2347 - Added Lands End (EGHC) TWR sector ownership
  .github/CHANGELOG.md
  Airports/EGHC/Ownership.txt
  Airports/EGHC/Runway.txt
  Airports/EGHC/Sector.txt
Labels: enhancement, ready

#2362 Fixes #2342 - Added Balmoral Danger Area (EG R704)
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG R704.txt
Labels: airac, ready

#2416 Fixes #2415 - Valley TACAN correction
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: bug, ready

#2387 Fixes #2383 - Corrected Humber->EHAA EHAM agreement
  .github/CHANGELOG.md
  Agreements/External/Hum_AAlow.txt
Labels: bug, ready

#2381 Fixes #2380 - Barton AFIS Frequency Change
  .github/CHANGELOG.md
  Airports/EGCB/Basic.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac, ready

#2372 Fixes #2367 - Corrected Manchester (EGCC) top-down ownership
  .github/CHANGELOG.md
  Airports/EGCC/Ownership.txt
Labels: bug, ready

#2392 Fixes #2388 - Optimised LS->LD BB/GD/FF departing agreements
  .github/CHANGELOG.md
  Agreements/Internal/S_D.txt
Labels: enhancement

#2350 Fixes #2348 - Added Scilly Isles/St Mary's (EGHE) data and positions
  .github/CHANGELOG.md
  Airports/EGHE/Airspace.txt
  Airports/EGHE/Ownership.txt
  Airports/EGHE/Positions.txt
  Airports/EGHE/Sector.txt
  Airports/EGHQ/Ownership.txt
  UK.rwy
Labels: enhancement

#2351 Fixes #2345 - Renamed EGNV and Amended Relevant Docs
  .github/CHANGELOG.md
  Airports/EGNV/Airspace.txt
  Airports/EGNV/Basic.txt
  Airports/EGNV/Positions.txt
  Airports/EGNV/Positions_Mentor.txt
  Airports/EGNV/SMAA.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac, ready

#2464 Fixes #2463 - Remove old Mil positions and add Fighter control positions
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK.txt
  Misc/Positions_Area Positions 3 UK.txt
Labels: enhancement, ready

#2460 Fixes #2459 - Add Brize Director
  .github/CHANGELOG.md
  Airports/EGVN/Positions.txt
  Airports/EGVN/Runway.txt
Labels: enhancement, ready

#2441 Fixes #2439 - Add Oxford SMAA and correct Radar/Director frequencies
  .github/CHANGELOG.md
  Airports/EGTK/Positions.txt
  Airports/EGTK/Positions_Mentor.txt
  Airports/EGTK/SMAA.txt
Labels: bug, enhancement, ready

#2187 More random fixes from compiler
  Airports/EGAA/SMAA.txt
  Airports/EGAC/SMR/Labels.txt
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  Airports/EGCN/SMAA.txt
  Airports/EGGP/SMAA.txt
  Airports/EGGW/SMAA.txt
  Airports/EGHE/SMR/Labels.txt
  Airports/EGJJ/SMR/Labels.txt
  Airports/EGKB/Ground Map/Geo.txt
  Airports/EGKK/Ground Map/Geo.txt
  Airports/EGKK/SMR/Labels.txt
  Airports/EGLC/SMAA.txt
  Airports/EGLF/Ground Map/Geo.txt
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
  Airports/EGMD/Ground Map/Geo.txt
  Airports/EGNH/SMAA.txt
  Airports/EGNJ/SMAA.txt
  Airports/EGNV/SMAA.txt
  Airports/EGNX/SMAA.txt
  Airports/EGOV/Ground Map/Geo.txt
  Airports/EGPF/SMAA.txt
  Airports/EGPK/SMR/Geo.txt
  Airports/EGPO/Ground Map/Geo.txt
  Airports/EGQK/Ground Map/Geo.txt
  Airports/EGQS/Ground Map/Geo.txt
  Airports/EGSS/SMR/Geo.txt
  Airports/EGXC/Ground Map/Geo.txt
  Airports/EGYD/Ground Map/Geo.txt
  Airports/EGYM/Ground Map/Geo.txt
  Colours.txt
  Misc/Geo_City Transition Tracks.txt
  Misc/Geo_Coastline Low Detail.txt
  Misc/Geo_MSA.txt
  Misc/Geo_Merseyside Coastline.txt
  Misc/Geo_Motorways.txt
  Misc/Geo_Rivers.txt
  Misc/SID_Military Corridors.txt
  Misc/STAR_Worthing Paris Release Line.txt
  Sectors/Static/MTC/MAN E.txt
  Sectors/Static/MTC/MAN W.txt
  Sectors/Static/SCO/Deancross.txt
  Sectors/Static/SCO/West.txt
Labels: bug, enhancement, ready

#2375 Fixes #2373 - Added Iceland radio event clearance positions
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 2 External.txt
Labels: enhancement, ready

#2389 Fixes #2316 - New EGNV Freqs not simulated
  .github/CHANGELOG.md
  Doc/UK VATSIM frequencies.txt
Labels: airac, ready

#2402 Fixes #2400 - Add Brize LARS Frequency
  .github/CHANGELOG.md
  Airports/EGVN/Positions.txt
Labels: enhancement, ready

#2418 Fixes #2378 - Update EGTE SMR
  .github/CHANGELOG.md
  Airports/EGTE/SMR/Labels.txt
Labels: enhancement

#2437 Fixes #2436 - Updated EGUW MATZ
  .github/CHANGELOG.md
  Airports/EGUW/Airspace.txt
Labels: enhancement, ready

#2435 Fixes #2434 - Add EGQK MATZ and runway
  .github/CHANGELOG.md
  Airports/EGQK/Airspace.txt
  Airports/EGQK/Runway.txt
Labels: enhancement, ready

#2429 Fixes #2428 - EGQS Lossiemouth updates
  .github/CHANGELOG.md
  Airports/EGQS/Airspace.txt
  Airports/EGQS/Positions.txt
  Airports/EGQS/Runway.txt
Labels: enhancement, ready

#2433 Fixes #2432 - Redrawn EGQL MATZ
  .github/CHANGELOG.md
  Airports/EGQL/Airspace.txt
  Airports/EGQL/Runway.txt
Labels: enhancement, ready

#2361 Fixes #2354 - Optimised COPX for S29->27 NM/NO/NH outbounds
  .github/CHANGELOG.md
  Agreements/Internal/S29_27.txt
Labels: enhancement, ready

#2346 Fixes #2315 - Updated Southend (EGMC) SMR with SENA Apron
  .github/CHANGELOG.md
  Airports/EGMC/SMR/Geo.txt
  Airports/EGMC/SMR/Labels.txt
  Airports/EGMC/SMR/Regions.txt
  _data/SMR Files/EGMC/Southend SMR 2004.kmz
Labels: airac, ready

#2472 Fixes #2471 - Update to Military radar corridors
  .github/CHANGELOG.md
  Misc/SID_Military Corridors.txt
Labels: enhancement

#2466 Fixes #2368 - Fixed SSFIN->TC NW NUGBO/UTAVA agreements
  .github/CHANGELOG.md
  Agreements/Airport/SS_TCNW.txt
  Ownership/TC - LTC/London TC LOREL.txt
Labels: bug

#2469 Fixes #2468 - Added PC East Internal Agreements
  .github/CHANGELOG.md
  Agreements/Airport/North_NM.txt
  Agreements/Internal/East_North.txt
  Agreements/Internal/Gal_North.txt
  Agreements/Internal/Nor_Tal.txt
  Agreements/Internal/North_East.txt
  Agreements/Internal/North_S29.txt
  Agreements/Internal/North_Tal.txt
  Agreements/Internal/Stafa_27.txt
  Agreements/Internal/Stafa_S29.txt
  Agreements/Internal/Stafa_Trent.txt
  Agreements/Internal/Trent_East.txt
  Agreements/Internal/Trent_North.txt
  Agreements/Internal/Trent_Stafa.txt
  Agreements/Internal/Wal_North.txt
  Agreements/Internal/Wal_Stafa.txt
Labels: enhancement

#2456 Fixes #2455 - Create EGAE SMR
  .github/CHANGELOG.md
  Airports/EGAE/SMR/Geo.txt
  Airports/EGAE/SMR/Labels.txt
  Airports/EGAE/SMR/Regions.txt
  _data/SMR Files/EGAE/EGAE - Derry_2020-04.kmz
  _data/SMR Files/EGAE/Ground Map
Labels: enhancement

#2452 Fixes #2451 - Isles of Scilly Enhancements
  .github/CHANGELOG.md
  Misc/Geo_Coastline Low Detail.txt
  Misc/STAR_Lands End Transit Corridor.txt
Labels: enhancement, ready

#2401 Fixes #2398 - Thames clutch agreements
  .github/CHANGELOG.md
  Agreements/Airport/MC_THAMES.txt
  Agreements/Airport/THAMES_TCSE.txt
Labels: bug

#2396 Fixes #2394 - Added EGCB (Barton) Runways
  .github/CHANGELOG.md
  Airports/EGCB/Active_Runway.txt
  Airports/EGCB/Runway.txt
Labels: enhancement

#2370 Fixes #2369 - Improved functionality of EGKK LAM departure agreements
  .github/CHANGELOG.md
  Agreements/Internal/S_TCWEL.txt
  Agreements/Internal/TCSE_S.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC LOREL.txt
Labels: enhancement

#2365 Fixes #2364 - Adjusted Solent online ring display
  .github/CHANGELOG.md
  Airports/EGHH/Sector.txt
  Airports/EGHI/Sector.txt
Labels: enhancement

#2360 Fixes #2358 - Belfast TMA Standing Agreements
  .github/CHANGELOG.md
  Agreements/Airport/AA_Antrim.txt
  Agreements/Airport/AA_Rat.txt
  Agreements/Airport/Ant_AA.txt
  Agreements/Airport/Rat_AA.txt
Labels: enhancement

#2359 Fixes #2181 - Fixed TC NW sector definition and LTC line display issues
  .github/CHANGELOG.md
  Ownership/TC - LTC/London TC CPT.txt
  Ownership/TC - LTC/London TC NW.txt
  Ownership/TC - LTC/London TC SW.txt
  Ownership/TC - LTC/London TC VATON.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
  Sectors/Static/LTC/North West.txt
  Sectors/Static/LTC/South West.txt
Labels: bug, enhancement

#2413 Fixes #2395 - Updated Dcs->Tal ScTMA inbound agreements
  .github/CHANGELOG.md
  Agreements/Internal/Dcs_Tal.txt
Labels: bug

#2474 Fixes #1810 - Added PC West Internal Agreements
  .github/CHANGELOG.md
  Agreements/Internal/IoM_S29.txt
  Agreements/Internal/IoM_Wal.txt
  Agreements/Internal/S29_IoM.txt
  Agreements/Internal/Wal_IoM.txt
Labels: enhancement

#2355 Fixes #2353 - Removed dupe Airspace Bases in LAMIX/OTBED Area
  .github/CHANGELOG.md
  Misc/Freetext_Airspace Bases.txt
Labels: enhancement, ready

#2310 Fixes #1859 - EGGW SMR Update
  .github/CHANGELOG.md
  Airports/EGGW/SMR/Geo.txt
  Airports/EGGW/SMR/Labels.txt
  Airports/EGGW/SMR/Regions.txt
Labels: airac, ready

#2421 Fixes #2420- Redraw EGXC MATZ
  .github/CHANGELOG.md
  Airports/EGXC/Active_Runway.txt
  Airports/EGXC/Airspace.txt
  Airports/EGXC/Positions.txt
  Airports/EGXC/Runway.txt
Labels: enhancement, ready

#2423 Fixes #2422 - Update EGYD MATZ
  .github/CHANGELOG.md
  Airports/EGYD/Active_Runway.txt
  Airports/EGYD/Airspace.txt
  Airports/EGYD/Positions.txt
  Airports/EGYD/Runway.txt
Labels: enhancement, ready

#2425 Fixes #2424 - Update EGYM MATZ and info
  .github/CHANGELOG.md
  Airports/EGYM/Active_Runway.txt
  Airports/EGYM/Airspace.txt
  Airports/EGYM/Positions.txt
  Airports/EGYM/Runway.txt
Labels: enhancement, ready

#2431 Fixes #2430 - EGDM MATZ update
  .github/CHANGELOG.md
  Airports/EGDM/Airspace.txt
Labels: enhancement, ready

#2427 Fixes #2426 - EGOV Valley Update
  .github/CHANGELOG.md
  Airports/EGOV/Active_Runway.txt
  Airports/EGOV/Airspace.txt
  Airports/EGOV/Positions.txt
  Airports/EGOV/Runway.txt
Labels: enhancement, ready

#2335 Fixes #2331 - Update EGKA SMR
  .github/CHANGELOG.md
  Airports/EGKA/Runway.txt
  Airports/EGKA/SMR/Geo.txt
  Airports/EGKA/SMR/Labels.txt
  Airports/EGKA/SMR/Regions.txt
Labels: airac, enhancement

#2393 Fixes #2371 - Optimised COPX for LTMA deps in LON_E area
  .github/CHANGELOG.md
  Agreements/Internal/TCDAG_12.txt
  Agreements/Internal/TCLAM_TCDAG.txt
  Agreements/Internal/TCNE_TCDAG.txt
Labels: bug, enhancement
