Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-04, with the labels that each got.

#3573 Fixes #3571 - Change name of Worthing-Paris Release Line -> La Manche Release Area
  .github/CHANGELOG.md
  Misc/STAR_La Manche Release Area.txt
  Misc/STAR_Worthing Paris Release Line.txt
  compiler.config.json
Labels: controller-pack-change, procedure-change

#3562 Fixes #3559 - Removed Kirkwall (EGPA) W1 Holding Point
  .github/CHANGELOG.md
  Airports/EGPA/SMR/Geo.txt
  Airports/EGPA/SMR/Labels.txt
Labels: airac

#3561 Fixes #3560 - Updated Kirkwall (EGPA) Runway Headings
  .github/CHANGELOG.md
  Airports/EGPA/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3555 Fixes #3554 - Adds Exeter Standard Routings
  .github/CHANGELOG.md
  Airports/EGTE/Sids.txt
  Airports/EGTE/Stars.txt
Labels: api-change-needed, enhancement

#3538 Fixes #3532 - Provide SMAA base data as freetext
  .build/ese_template.txt
  .github/CHANGELOG.md
  Airports/EGBJ/SMAA_Bases.txt
  Airports/EGHQ/SMAA_Bases.txt
  Airports/EGNJ/SMAA_Bases.txt
  Airports/EGNR/SMAA_Bases.txt
  Airports/EGPE/SMAA_Bases.txt
  Airports/EGTE/SMAA_Bases.txt
  Airports/EGTK/SMAA_Bases.txt
  compiler.config.json
Labels: compiler-config-change, enhancement

#3574 Fixes #3570 - Add DVR RFC Area
  .github/CHANGELOG.md
  Misc/STAR_DVR RFC Area.txt
  compiler.config.json
Labels: controller-pack-change, procedure-change

#3592 Fixes #3590 - Removes duplicate codes from a number of aerodromes
  .github/CHANGELOG.md
  .github/workflows/compile.yml
  Airports/EGAE/Ownership.txt
  Airports/EGGD/Ownership.txt
  Airports/EGLL/Ownership.txt
  Airports/EGPK/Ownership.txt
  Airports/EGWU/Ownership.txt
Labels: error

#3579 Fixes #3569 - Added EGLW TWR Ownership & Runway
  .github/CHANGELOG.md
  Airports/EGLW/Active_Runway.txt
  Airports/EGLW/Airspace.txt
  Airports/EGLW/Ownership.txt
  Airports/EGLW/Positions.txt
  Airports/EGLW/Positions_Mentor.txt
  Airports/EGLW/Runway.txt
  Airports/EGLW/Sector.txt
  UK.rwy
Labels: enhancement

#3581 Fixes #3580 - Hawarden RMZ
  .github/CHANGELOG.md
  Airports/EGNR/RMA.txt
Labels: enhancement

#3588 Fixes #3587 - Added EGCC Planner & Fixed EGLL Planner RT callsign
  .github/CHANGELOG.md
  Airports/EGCC/Positions.txt
  Airports/EGLL/Positions.txt
Labels: error, procedure-change

#3595 Fixes #3591 - Removed Erroneous Coordinate in Gatwick RMA
  .github/CHANGELOG.md
  Airports/EGKK/RMA.txt
Labels: error

#3594 Fixes #3586 - Corrected Erroneous MTMA Outbound Agreements via ARSAT
  .github/CHANGELOG.md
  Agreements/Internal/North_S29.txt
Labels: bug

#3601 Fixes #3553 - Added Missing RADAR section to Compiler Config
  .github/CHANGELOG.md
  Misc/Radar Holes.txt
  compiler.config.json
Labels: bug, compiler-config-change

#3572 Fixes #3548 - Shannon LFUNC sectorisation
  .github/CHANGELOG.md
  ARTCC/High/EGPX Scottish FIR.txt
  ARTCC/High/Irish Sea CTA.txt
  Agreements/External/35_SNE.txt
  Agreements/External/4_SNE.txt
  Agreements/External/5_SNE.txt
  Agreements/External/7_SNE.txt
  Agreements/External/8_SNB.txt
  Agreements/External/9_SNB.txt
  Agreements/External/9_SNS.txt
  Agreements/External/IoM_SNE.txt
  Agreements/External/Rat_SNE.txt
  Agreements/External/SNB_9.txt
  Agreements/External/SNE_IoM.txt
  Agreements/External/SNE_Rat.txt
  Ownership/Non-UK/Shannon.txt
  Sectors/Lines - Ireland.txt
Labels: enhancement

#3607 Fixes #3602 - Add EGPG SMR
  .github/CHANGELOG.md
  Airports/EGPG/SMR/Geo.txt
  Airports/EGPG/SMR/Labels.txt
  Airports/EGPG/SMR/Regions.txt
  Colours.txt
Labels: enhancement

#3584 Fixes #3583 - Manchester MSA cones colour
  .github/CHANGELOG.md
  Airports/EGCC/SMAA.txt
  Colours.txt
  Misc/Geo_MSA.txt
  compiler.config.json
Labels: enhancement

#3612 Fixes #3611 - Bournemouth Holding Point Names
  .github/CHANGELOG.md
  Airports/EGHH/SMR/Labels.txt
Labels: error

#3589 Fixes #2282 - Unifies Airspace Bases
  .github/CHANGELOG.md
  Airports/EGBB/Airspace_Bases.txt
  Airports/EGLF/Airspace_Bases.txt
  Misc/Freetext_Airspace Bases.txt
Labels: enhancement

#3622 Fixes #3541 - New AC South Positions
  Misc/Positions_Area Positions 2 UK Event.txt
  Ownership/AC - South/1.txt
  Ownership/AC - South/15.txt
  Ownership/AC - South/16.txt
  Ownership/AC - South/17.txt
  Ownership/AC - South/18.txt
  Ownership/AC - South/2.txt
  Ownership/AC - South/20.txt
  Ownership/AC - South/21.txt
  Ownership/AC - South/22.txt
  Ownership/AC - South/25.txt
  Ownership/AC - South/26.txt
  Ownership/AC - South/Dover.txt
  Ownership/AC - South/Worthing.txt
  Ownership/TC - LTC/London TC CPT.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC SW.txt
  Ownership/TC - LTC/London TC VATON.txt
Labels: procedure-change

#3566 Fixes #3439 - AC South Resect - Add External Agreements
  Agreements/External/15_BU.txt
  Agreements/External/15_EE-N.txt
  Agreements/External/15_YY-K.txt
  Agreements/External/18_PN.txt
  Agreements/External/18_RR-E.txt
  Agreements/External/1_RR-Q.txt
  Agreements/External/20_RR-V.txt
  Agreements/External/20_RR.txt
  Agreements/External/21_RR.txt
  Agreements/External/2_EE-N.txt
  Agreements/External/2_YY-K.txt
  Agreements/External/D_BU.txt
  Agreements/External/D_EE-N.txt
  Agreements/External/D_YY-K.txt
  Agreements/External/EE-N_16.txt
  Agreements/External/EE-N_17.txt
  Agreements/External/EE-N_D.txt
  Agreements/External/PN_17.txt
  Agreements/External/PN_D.txt
  Agreements/External/PN_TCSE.txt
  Agreements/External/RR-J_19.txt
  Agreements/External/RR-J_22.txt
  Agreements/External/RR-J_S.txt
  Agreements/External/RR_18.txt
  Agreements/External/RR_19.txt
  Agreements/External/RR_21.txt
  Agreements/External/RR_22.txt
  Agreements/External/RR_S.txt
  Agreements/External/S_PN.txt
  Agreements/External/S_RR-E.txt
  Agreements/External/S_RR-Q.txt
  Agreements/External/S_RR-V.txt
  Agreements/External/S_RR.txt
Labels: procedure-change

#3582 Fixes #3563 - Area positions clean-up and addition of Oceanic freqs
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK Permanent.txt
  Misc/Positions_Area Positions 2 UK Event.txt
  Misc/Positions_Area Positions 3 UK Spares.txt
  Misc/Positions_Area Positions 4 External.txt
Labels: enhancement

#3621 Fixes #3542 - Top-down coverage new AC South Sectors
  Airports/EGGW/Ownership.txt
  Airports/EGKA/Ownership.txt
  Airports/EGKB/Ownership.txt
  Airports/EGKK/Ownership.txt
  Airports/EGLC/Ownership.txt
  Airports/EGLF/Ownership.txt
  Airports/EGLL/Ownership.txt
  Airports/EGMC/Ownership.txt
  Airports/EGMD/Ownership.txt
  Airports/EGSC/Ownership.txt
  Airports/EGSS/Ownership.txt
  Airports/EGWU/Ownership.txt
  Ownership/Alternate/Airports - LTC/SE.txt
  Ownership/Alternate/Airports - LTC/SW.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC NW.txt
Labels: procedure-change

#3558 Fixes #3557 - Adds Exeter Split and COPX Functionality
  .github/CHANGELOG.md
  Agreements/Airport/6_TE.txt
  Agreements/Airport/FF_TE.txt
  Agreements/Airport/TE_6.txt
  Airports/EGFF/Ownership.txt
  Airports/EGTE/Ownership.txt
  Airports/EGTE/Sector.txt
Labels: enhancement

#3617 Fixes #3616 - New Coventry (EGBE) SMR
  .github/CHANGELOG.md
  Airports/EGBE/Ground Map/Geo.txt
  Airports/EGBE/Ground Map/Labels.txt
  Airports/EGBE/SMR/Geo.txt
  Airports/EGBE/SMR/Labels.txt
  Airports/EGBE/SMR/Regions.txt
  _data/SMR Files/EGBE/EGBE.kmz
Labels: enhancement

#3625 Fixes #3564 - Reykjavik (BIRD) CTP Sectorisation
  .github/CHANGELOG.md
  Ownership/Non-UK/Reykjavik.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - PACC.txt
Labels: procedure-change
