Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-06, with the labels that each got.

#3694 Fixes #3688 - Added RUXIN Fix
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: airac

#3695 Fixes #3690 - Redesignated Guernsey (EGJB) STARs GUR1Y/1Z -> GUR2Y/2Z
  .github/CHANGELOG.md
  Airports/EGJB/Stars.txt
Labels: airac

#3693 Fixes #3691 RCH NDB decommissioned
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
  Navaids/NDB_Old.txt
Labels: airac

#3696 Fixes #3689 - Various Gloucestershire (EGBJ) SMR & runway changes
  .github/CHANGELOG.md
  Airports/EGBJ/Runway.txt
  Airports/EGBJ/SMR/Geo.txt
  Airports/EGBJ/SMR/Regions.txt
  _data/SMR Files/EGBJ/EGBJ 2106.kmz
Labels: airac

#3614 Fixes #3610 - Spice up the Sumburgh (EGPB) SMR
  .github/CHANGELOG.md
  Airports/EGPB/SMR/Geo.txt
  Airports/EGPB/SMR/Labels.txt
  Airports/EGPB/SMR/Regions.txt
  _data/SMR Files/EGPB/EGPB.kmz
Labels: enhancement

#3717 Fixes #3716 - Correct Humberside (EGNJ) SMAA
  .github/CHANGELOG.md
  Airports/EGNJ/SMAA.txt
Labels: error

#3714 Fixes #3713 - Improve Doncaster (EGCN) Centreline
  .github/CHANGELOG.md
  Airports/EGCN/Centreline.txt
Labels: enhancement

#3725 Fixes #3692 - Various Swansea (EGFH) SMR & runway changes
  .github/CHANGELOG.md
  Airports/EGFH/Runway.txt
  Airports/EGFH/SMR/Geo.txt
  Airports/EGFH/SMR/Labels.txt
Labels: airac

#3709 Fixes #3708 - Improve Humberside (EGNJ) Centreline
  .github/CHANGELOG.md
  Airports/EGNJ/Centreline.txt
Labels: enhancement

#3707 Fixes #3706 - Improve Leeds (EGNM) Centreline
  .github/CHANGELOG.md
  Airports/EGNM/Centreline.txt
Labels: enhancement

#3718 Fixes #3715 - Correct Doncaster (EGCN) SMAA
  .github/CHANGELOG.md
  Airports/EGCN/SMAA.txt
Labels: error

#3720 Fixes #3719 - Improve Newcastle (EGNT) Centreline
  .github/CHANGELOG.md
  Airports/EGNT/Centreline.txt
Labels: enhancement

#3722 Fixes #3721 - Add Newcastle (EGNT) FAVAs
  .github/CHANGELOG.md
  Airports/EGNT/SMAA.txt
Labels: enhancement

#3724 Fixes #3723 - Improve Teeside (EGNV) Centreline
  .github/CHANGELOG.md
  Airports/EGNV/Centreline.txt
Labels: enhancement

#3686 AC North Sectorisation and top-down ownership
  .github/CHANGELOG.md
  Airports/EGCC/Ownership.txt
  Airports/EGCN/Ownership.txt
  Airports/EGGP/Ownership.txt
  Airports/EGNH/Ownership.txt
  Airports/EGNJ/Ownership.txt
  Airports/EGNM/Ownership.txt
  Airports/EGNO/Ownership.txt
  Airports/EGNR/Ownership.txt
  Airports/EGNS/Ownership.txt
  Airports/EGNT/Ownership.txt
  Airports/EGNV/Ownership.txt
  Ownership/Alternate/Airports - MPC/East.txt
  Ownership/Alternate/Airports - MPC/Isle of Man.txt
  Ownership/Alternate/Airports - MPC/NorthEast.txt
  Ownership/Alternate/Airports - MPC/SouthEast.txt
  Ownership/TC - MPC/East.txt
  Ownership/TC - MPC/IoM.txt
  Ownership/TC - MPC/North.txt
  Ownership/TC - MPC/S29.txt
  Ownership/TC - MPC/SE Stafa.txt
  Ownership/TC - MPC/SE Trent.txt
  Ownership/TC - MPC/Wallasey.txt
Labels: procedure-change
