Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-09, with the labels that each got.

#3832 Fixes #3822 - Added Various Jersey (EGJJ) STAR Changes
  .github/CHANGELOG.md
  Airports/EGJJ/Stars.txt
Labels: airac

#3831 Fixes #3825 - Redesignated Guernsey (EGJB) GUR STARs
  .github/CHANGELOG.md
  Airports/EGJB/Stars.txt
Labels: airac

#3817 Fixes #3806 - Added Bristol RNAV-5 STARs
  .github/CHANGELOG.md
  Airports/EGGD/Stars.txt
Labels: airac

#3791 Fixes #3705 & #3355 - Gatwick SMR Update
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Labels.txt
  Airports/EGKK/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGKK/EGKK_SMR_1.png
  _data/SMR Files/EGKK/EGKK_SMR_2.png
  _data/SMR Files/EGKK/EGKK_SMR_Ref_Src_List.md
  _data/SMR Files/EGKK/Gatwick SMR 2021.kmz
Labels: enhancement

#3821 Fixes #3803 - Added Raymill House Restricted Area (R106)
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG R106.txt
Labels: airac

#3823 Fixes #3802 - Added Llanbedr Danger Areas (D217A-K)
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D217.txt
Labels: airac

#3830 Fixes #3826 - Added Kemble (EGBP) RNP Approach Fixes
  .github/CHANGELOG.md
  Airports/EGBP/Fixes.txt
Labels: airac

#3834 Fixes #3701 - Update London City (EGLC) SMR
  .github/CHANGELOG.md
  Airports/EGLC/SMR/Geo.txt
  Airports/EGLC/SMR/Labels.txt
  _data/SMR Files/EGLC/EGLC SMR 21-06.kmz
Labels: airac, controller-pack-change

#3837 Fixes #3810 - Updated AC West -> FF Agreements
  .github/CHANGELOG.md
  Agreements/Airport/5_FF.txt
  Agreements/Airport/8_FF.txt
Labels: procedure-change

#3842 Fixes #3794 - Added missing Stansted (EGSS) taxiway line
  .github/CHANGELOG.md
  Airports/EGSS/SMR/Geo.txt
  _data/SMR Files/EGSS/Stansted SMR.kmz
Labels: error

#3841 Fixes #3840 - Amended BRI 1C STAR Notation
  .github/CHANGELOG.md
  Airports/EGGD/Stars.txt
Labels: error

#3844 Fixes #3819 - Various Fairoaks (EGTF) Changes
  .github/CHANGELOG.md
  Airports/EGTF/Runway.txt
  Airports/EGTF/SMR/Geo.txt
  Airports/EGTF/SMR/Labels.txt
  _data/SMR Files/EGTF/Fairoaks New SMR.kmz
Labels: airac

#3845 Fixes #3820 - Various Thruxton (EGHO) Changes
  .github/CHANGELOG.md
  Airports/EGHO/SMR/Regions.txt
  _data/SMR Files/EGHO/EGHO.kmz
Labels: airac

#3859 Fixes #3856 - Truncated Jersey (EGJJ) CAN SIDs to LUSIT
  .github/CHANGELOG.md
  Airports/EGJJ/Sids.txt
Labels: airac

#3860 Fixes #3855 - Truncated Guernsey (EGJB) CAN SIDs to LUSIT
  .github/CHANGELOG.md
  Airports/EGJB/Sids.txt
Labels: airac

#3867 Fixes #3866 - Updated Maastricht (EBBU_U_CTR) Radar Frequency
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#3865 Fixes #3854 - Renamed Manchester (EGCC) NA Hold to NA1
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
Labels: airac
