Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-12, with the labels that each got.

#3880 Area Sector Definition Tidy Up (2021/11)
  .github/CHANGELOG.md
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
  Ownership/AC - Central/27.txt
  Ownership/AC - Central/28.txt
  Ownership/AC - Central/34.txt
  Ownership/AC - North/10.txt
  Ownership/AC - North/11.txt
  Ownership/TC - LTC/London TC CPT.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC NE.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
  Sectors/Lines - MPC.txt
  Sectors/Lines - Misc.txt
  Sectors/Lines - PACC.txt
Labels: bug, enhancement

#3899 Fixes #3888 - Replaced Lands End Transit Corridor with New RMZ
  .github/CHANGELOG.md
  Airports/EGHE/Sector.txt
  Misc/STAR_Lands End RMZ.txt
  Misc/STAR_Lands End Transit Corridor.txt
Labels: airac

#3900 Fixes #3890 and #3898 - Bristol Stands Removed
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
Labels: airac

#3902 Fixes #3901 - Add St Athan KMZ
  _data/SMR Files/EGSY/EGSY.kmz
Labels: error

#3904 Fixes #3903 - Amended Thames (EGLC) SMAA
  .github/CHANGELOG.md
  Airports/EGLC/SMAA.txt
Labels: airac, controller-pack-change

#3908 Fixes #3894 - FRA deployment 1 removed fixes
  .github/CHANGELOG.md
  Navaids/FIXES_Old.txt
  Navaids/FIXES_UK.txt
Labels: airac

#3909 Fixes #3893 - FRA Deployment 1 new fixes
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: airac

#3910 Fixes #3895 - FRA deployment 1 Removed Airways
  .github/CHANGELOG.md
  Airways/RNAV/Upper/L983.txt
  Airways/RNAV/Upper/M83.txt
  Airways/RNAV/Upper/N491.txt
  Airways/RNAV/Upper/N502.txt
  Airways/RNAV/Upper/N512.txt
  Airways/RNAV/Upper/N521.txt
  Airways/RNAV/Upper/N66.txt
  Airways/RNAV/Upper/T55.txt
  Airways/RNAV/Upper/UL619.txt
  Airways/RNAV/Upper/UM125.txt
  Airways/RNAV/Upper/UM86.txt
  Airways/RNAV/Upper/UM869.txt
  Airways/RNAV/Upper/UM89.txt
  Airways/RNAV/Upper/UN537.txt
  Airways/RNAV/Upper/UN562.txt
  Airways/RNAV/Upper/UN581.txt
  Airways/RNAV/Upper/UN583.txt
  Airways/RNAV/Upper/UN584.txt
  Airways/RNAV/Upper/UN591.txt
  Airways/RNAV/Upper/UN593.txt
  Airways/RNAV/Upper/UN603.txt
  Airways/RNAV/Upper/UN614.txt
  Airways/RNAV/Upper/UP24.txt
  Airways/RNAV/Upper/UP60.txt
  Airways/RNAV/Upper/UP600.txt
  Airways/RNAV/Upper/UP61.txt
  Airways/RNAV/Upper/UP612.txt
  Airways/RNAV/Upper/UZ105.txt
  Airways/RNAV/Upper/UZ107.txt
  Airways/RNAV/Upper/Z278.txt
Labels: airac

#3911 Fixes #3896 - FRA Deployment 1 Amended Airways
  .github/CHANGELOG.md
  Airways/Conventional/Lower/L612.txt
  Airways/Conventional/Lower/P600.txt
  Airways/Conventional/Lower/T256.txt
  Airways/Conventional/Lower/Y905.txt
  Airways/RNAV/Lower/P6.txt
  Airways/RNAV/Upper/L10.txt
  Airways/RNAV/Upper/L602.txt
  Airways/RNAV/Upper/L603.txt
  Airways/RNAV/Upper/L613.txt
  Airways/RNAV/Upper/L7.txt
  Airways/RNAV/Upper/M142.txt
  Airways/RNAV/Upper/M147.txt
  Airways/RNAV/Upper/M148.txt
  Airways/RNAV/Upper/M90.txt
  Airways/RNAV/Upper/M982.txt
  Airways/RNAV/Upper/N110.txt
  Airways/RNAV/Upper/N34.txt
  Airways/RNAV/Upper/N44.txt
  Airways/RNAV/Upper/N562.txt
  Airways/RNAV/Upper/N610.txt
  Airways/RNAV/Upper/N96.txt
  Airways/RNAV/Upper/N97.txt
  Airways/RNAV/Upper/P144.txt
  Airways/RNAV/Upper/P15.txt
  Airways/RNAV/Upper/P5.txt
  Airways/RNAV/Upper/P58.txt
  Airways/RNAV/Upper/T7.txt
  Airways/RNAV/Upper/UL612.txt
  Airways/RNAV/Upper/UL975.txt
  Airways/RNAV/Upper/UM185.txt
  Airways/RNAV/Upper/UM82.txt
  Airways/RNAV/Upper/UN57.txt
  Airways/RNAV/Upper/UN590.txt
  Airways/RNAV/Upper/UN601.txt
  Airways/RNAV/Upper/UP16.txt
  Airways/RNAV/Upper/UP18.txt
  Airways/RNAV/Upper/UP59.txt
  Airways/RNAV/Upper/UP6.txt
  Airways/RNAV/Upper/UP620.txt
  Airways/RNAV/Upper/UT256.txt
Labels: airac

#3912 Fixes #3891 - Glasgow (EGPF) Threshold coordinates and Mag Var updated
  .github/CHANGELOG.md
  Airports/EGPF/Runway.txt
Labels: airac

#3916 Fixes #3915 - LARLA triangle to S9 and COPX update
  .github/CHANGELOG.md
  Agreements/External/9_RR-W.txt
  Agreements/External/RR-W_9.txt
  Ownership/AC - West/9.txt
  Ownership/Non-UK/Brest.txt
Labels: airac

#3918 Fixes #3917 - New Bristol delegated airspace
  .github/CHANGELOG.md
  Misc/STAR_GD-FF CTA Line.txt
Labels: procedure-change

#3920 Fixes #3919 - Added FRA Deployment 1 as a STAR
  .github/CHANGELOG.md
  Misc/STAR_EGPX FRA.txt
Labels: airac

#3930 Fixes #3928 - Update Glasgow Runway Headings
  .github/CHANGELOG.md
  Airports/EGPF/Runway.txt
Labels: airac

#3936 Fixes #3921 - Land's End name updated
  .github/CHANGELOG.md
  Airports/EGHC/Airspace.txt
  Airports/EGHC/Basic.txt
  Airports/EGHC/Positions.txt
  Airports/EGHC/SMR/Geo.txt
  Airports/EGHC/SMR/Regions.txt
  Misc/STAR_Lands End RMZ.txt
  Navaids/VOR_UK.txt
Labels: airac

#3924 Fixes #3868 - Update Doncaster Stands
  .github/CHANGELOG.md
  Airports/EGCN/SMR/Geo.txt
  Airports/EGCN/SMR/Labels.txt
Labels: airac

#3932 Fixes #3887 - Removed M604 Conventional airway entry
  .github/CHANGELOG.md
  Airways/Conventional/Lower/M604.txt
Labels: error

#3933 Fixes #3925 - EURM_CTR split --> EURM_W_CTR
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#3934 Fixes #3931 - Updated Eglinton (EGAE) runway threshold coords
  .github/CHANGELOG.md
  Airports/EGAE/Runway.txt
Labels: enhancement

#3935 Fixes #3922 - Borders CTA 1 base change
  .github/CHANGELOG.md
  ARTCC/High/Borders CTA.txt
  Misc/Freetext_Airspace Bases.txt
Labels: airac

#3938 Fixes #3937 - Add Guernsey Approach to Top-Down Order
  .github/CHANGELOG.md
  Airports/EGJA/Ownership.txt
Labels: bug

#3940 Fixes #3939 - Removed redundant old data
  .github/CHANGELOG.md
  Airports/EGCC/Fixes.txt
  _data/Closed Airfields/EGCD/Basic.txt
  _data/Closed Airfields/EGCD/Centreline.txt
  _data/Closed Airfields/EGCD/Runway.txt
  _data/Closed Airfields/EGCD/Stars.txt
  _data/Closed Airfields/EGHD/Basic.txt
  _data/Closed Airfields/EGHD/Centreline.txt
  _data/Closed Airfields/EGHD/Ownership.txt
  _data/Closed Airfields/EGHD/Positions.txt
  _data/Closed Airfields/EGHD/Positions_Mentor.txt
  _data/Closed Airfields/EGHD/Sector.txt
  _data/Closed Airfields/EGMH/Active_Runway.txt
  _data/Closed Airfields/EGMH/Basic.txt
  _data/Closed Airfields/EGMH/Centreline.txt
  _data/Closed Airfields/EGMH/Ground Map/Geo.txt
  _data/Closed Airfields/EGMH/Ground Map/Labels.txt
  _data/Closed Airfields/EGMH/Positions.txt
  _data/Closed Airfields/EGMH/Positions_Mentor.txt
  _data/Closed Airfields/EGMH/Runway.txt
  _data/Closed Airfields/EGTG/Ground Map/Geo.txt
  _data/Old/ARTCC_Danger Areas.txt
  _data/Old/EGCC/Fixes.txt
  _data/Old/EGHH/Geo.txt
  _data/Old/EGJJ/CTR.txt
  _data/Old/EGKK/Labels.txt
  _data/Old/EGKK/Regions.txt
  _data/Old/EGLL/Fixes.txt
  _data/Old/EGLL/RNAV SIDs.txt
  _data/Old/EGLL/Transitions.txt
  _data/Old/EGPH/Geo.txt
  _data/Old/Lines.txt
  _data/Old/Old NDBs.txt
  _data/Old/Runway Fixes.txt
  _data/Old/Static Boundaries.txt
  compiler.config.json
Labels: enhancement

#3944 Fixes #3941 - Updated Prestwick (EGPK) runway headings
  .github/CHANGELOG.md
  Airports/EGPK/Runway.txt
Labels: airac

#3943 Fixes #3942 - Amended Doncaster (EGCN) 'A' stand labels
  Airports/EGCN/SMR/Labels.txt
Labels: enhancement

#3946 Fixes #3945 - Updated MUAC Jever ownership and frequencies
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
  Ownership/Non-UK/Maastricht.txt
Labels: error
