Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-08, with the labels that each got.

#3768 Fixes #3767 - Remove D3 holding point at EGNH
  .github/CHANGELOG.md
  Airports/EGNH/SMR/Geo.txt
  Airports/EGNH/SMR/Labels.txt
  Airports/EGNX/Ground_Network.txt
Labels: airac

#3776 Fixes #3760 - Little Rissington ATZ added
  .github/CHANGELOG.md
  Airports/EGVL/Airspace.txt
  Airports/EGVL/Basic.txt
Labels: airac

#3782 Fixes #3764 - Added Heathrow Taxiway A (South) Closure
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Regions.txt
Labels: airac

#3781 Fixes #3615 - Malfunctioning handoffs between PCSE and CCS fixed
  .github/CHANGELOG.md
  Airports/EGCC/Stars.txt
Labels: bug

#3779 Fixes #3710 - Fixed missing Jersey Line
  .github/CHANGELOG.md
  Airports/EGJJ/Ownership.txt
  Airports/EGJJ/Sector.txt
Labels: bug

#3785 Fixes #3680 - Removed all Archived/Withdrawn Data
  .github/CHANGELOG.md
  Agreements/Internal/14_TCJAC.txt
  Agreements/Internal/14_TCSAB.txt
  Agreements/Internal/TCSAB_TCSE.txt
  Airports/EGBB/Sids.txt
  Airports/EGGP/Stars.txt
  Airports/EGHH/Stars.txt
  Airports/EGHI/Stars.txt
  Airports/EGJJ/Stars.txt
  Airports/EGKB/Stars.txt
  Airports/EGKK/Stars.txt
  Airports/EGLC/Sids.txt
  Airports/EGLC/Stars.txt
  Airports/EGLL/Sids.txt
  Airports/EGLL/Stars.txt
  Airports/EGNX/Stars.txt
  Airports/EGPF/Stars.txt
  Airports/EGPK/Stars.txt
  Airports/EGWU/Stars.txt
  Airways/Conventional/Lower/L975.txt
  Airways/Conventional/Lower/M604.txt
  Airways/Conventional/Lower/N57.txt
  Navaids/FIXES_Non-UK.txt
  Navaids/FIXES_Old.txt
  Navaids/VOR_UK.txt
  _data/Old/Old NDBs.txt
Labels: enhancement

#3789 Fixes #3788 - Corrected Teesside (EGNV) Misspelling
  .github/CHANGELOG.md
  Airports/EGNV/Airspace.txt
  Airports/EGNV/Basic.txt
  Airports/EGNV/Ground Map/Geo.txt
  Airports/EGNV/Positions.txt
  Airports/EGNV/Positions_Mentor.txt
  Airports/EGNV/SMAA.txt
  Airports/EGNV/SMR/Regions.txt
  Doc/UK VATSIM frequencies.txt
Labels: controller-pack-change, error

#3787 Fixes #3727 - Further AC North Resectorisation Changes
  .github/CHANGELOG.md
  Airports/EGCC/Ownership.txt
  Airports/EGCN/Ownership.txt
  Airports/EGGP/Ownership.txt
  Airports/EGNH/Ownership.txt
  Airports/EGNJ/Ownership.txt
  Airports/EGNM/Ownership.txt
  Airports/EGNO/Ownership.txt
  Airports/EGNR/Ownership.txt
  Airports/EGNS/Ownership.txt
  Airports/EGNT/Ownership.txt
  Airports/EGNV/Ownership.txt
  Misc/Positions_Area Positions 1 UK Permanent.txt
  Misc/Positions_Area Positions 2 UK Event.txt
  Ownership/Alternate/Airports - MPC/East.txt
  Ownership/Alternate/Airports - MPC/Isle of Man.txt
  Ownership/Alternate/Airports - MPC/NorthEast.txt
  Ownership/Alternate/Airports - MPC/SouthEast.txt
  Ownership/Alternate/Airports - MPC/Wallasey.txt
  Ownership/TC - MPC/East.txt
  Ownership/TC - MPC/IoM.txt
  Ownership/TC - MPC/North.txt
  Ownership/TC - MPC/S29.txt
  Ownership/TC - MPC/SE Stafa.txt
  Ownership/TC - MPC/SE Trent.txt
  Ownership/TC - MPC/Wallasey.txt
Labels: enhancement

#3780 Fixes #3711 - PC SE Sector lines amended
  .github/CHANGELOG.md
  Sectors/Lines - LACC.txt
Labels: bug

#3786 Fixes #3783 - Gloucester OCAS Area Updated
  .github/CHANGELOG.md
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: enhancement, controller-pack-change

#3793 Fixes #3792 - Fixed PE APP -> Montrose COPX Display
  .github/CHANGELOG.md
  Agreements/Airport/PE_Mon.txt
Labels: bug

#3812 Fixes #3800 - Extended M604 DET -> LYD
  .github/CHANGELOG.md
  Airways/RNAV/Upper/M604.txt
Labels: airac

#3811 Fixes #3799 - Updated Sywell (EGBK) 03L/21R Mag Var
  .github/CHANGELOG.md
  Airports/EGBK/Runway.txt
Labels: airac

#3816 Fixes #3807 - Added Cardiff RNAV-5 STARs
  .github/CHANGELOG.md
  Airports/EGFF/Stars.txt
  Navaids/FIXES_UK.txt
Labels: airac

#3790 D008C D013 Coordinates Updated
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D008.txt
  ARTCC/Danger Areas/EG D013.txt
Labels: airac

#3835 Fixes #3804 - Update Biggin Hill (EGKB) SMR
  .github/CHANGELOG.md
  Airports/EGKB/SMR/Geo.txt
  Airports/EGKB/SMR/Labels.txt
  Airports/EGKB/SMR/Regions.txt
  _data/SMR Files/EGKB/EGKB-2109.kmz
Labels: airac

#3824 Fixes #3805 - Renamed Birmingham (EGBB) STAR MAKUX1B -> MAKUX2B
  .github/CHANGELOG.md
  Airports/EGBB/Stars.txt
Labels: airac
