Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-05, with the labels that each got.

#3644 Fixes #3640 - Removed ASKEY, CASEY and CLIPY
  .github/CHANGELOG.md
  Navaids/FIXES_Old.txt
  Navaids/FIXES_UK.txt
Labels: airac

#3652 Fixes #3649 - Edinburgh (EGPH) Mag heading updates
  .github/CHANGELOG.md
  Airports/EGPH/Runway.txt
Labels: airac

#3663 Fixes #3660 - Removed Sumburgh Radar Standby and Updated Squawk Range
  .github/CHANGELOG.md
  Airports/EGPB/Ownership.txt
  Airports/EGPB/Positions.txt
  Airports/EGPB/Positions_Mentor.txt
Labels: enhancement

#3667 Fixes #3639 - Updated Swansea (EGFH) ARP
  .github/CHANGELOG.md
  Airports/EGFH/Basic.txt
Labels: airac

#3636 Fixes #3631 - Fixed Sector 24 ownership
  .github/CHANGELOG.md
  Ownership/AC - South/24.txt
Labels: bug

#3662 Fixes #3661 - Kirkwall (EGPA) - Threshold + KW NDB coordinate changes
  .github/CHANGELOG.md
  Airports/EGPA/Runway.txt
  Navaids/NDB_All.txt
Labels: airac

#3654 Fixes #3638 - Updated Wellesbourne (EGBW) Runway tracks
  .github/CHANGELOG.md
  Airports/EGBW/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3664 Fixes #3659 - Updated Gloucestershire (EGBJ) Runway Data
  .github/CHANGELOG.md
  Airports/EGBJ/Runway.txt
  Doc/Runway track changes.txt
Labels: airac

#3643 Fixes #3642 - updated Blackbushe (EGLK) SMR
  .github/CHANGELOG.md
  Airports/EGLK/Runway.txt
  Airports/EGLK/SMR/Geo.txt
  Airports/EGLK/SMR/Labels.txt
  _data/SMR Files/EGLK/Blackbushe EGLK.kmz
Labels: enhancement

#3635 Fixes #3634 - Revert BIRD CTP sectorisation
  .github/CHANGELOG.md
  Ownership/Non-UK/Reykjavik.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - PACC.txt
Labels: procedure-change

#3637 Fixes #3568 - Compiler config update
  Misc/Regions_GB Landmass Medium Detail.txt
  compiler.config.json
Labels: enhancement

#3630 Fixes #3618 - Ground Map and SMR Cleanup V2
  .github/CHANGELOG.md
  Airports/EGNC/SMR/Geo.txt
  Airports/EGNC/SMR/Labels.txt
  Airports/EGNH/SMR/Geo.txt
  Airports/EGNH/SMR/Labels.txt
  Airports/EGPB/SMR/Geo.txt
  Airports/EGPB/SMR/Labels.txt
Labels: enhancement

#3633 Fixes #3632 New Carlisle (EGNC) SMR
  .github/CHANGELOG.md
  Airports/EGNC/SMR/Geo.txt
  Airports/EGNC/SMR/Labels.txt
  Airports/EGNC/SMR/Regions.txt
  _data/SMR Files/EGNC/EGNC.kmz
Labels: enhancement
