Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-03, with the labels that each got.

#3495 Fixes #3494 - Fixed erroneous TC East static boundary
  .github/CHANGELOG.md
  Sectors/Static/LTC/East.txt
Labels: bug

#3490 Fixes #3405 - Fixed Missing Mentoring APP Sector Lines for East Midlands (EGNX)
  .github/CHANGELOG.md
  Airports/EGNX/Ownership.txt
Labels: bug, ready-for-review

#3492 Fixes #3491 - Fix Oxford (EGTK) ATZ sector size
  .github/CHANGELOG.md
  Airports/EGTK/Sector.txt
Labels: bug

#3508 Fixes #3505 - Updated Coordinates following Jersey Magnetic Variation Survey
  .github/CHANGELOG.md
  Navaids/FIXES_SIDS-STARS.txt
  Navaids/VOR_Non-UK.txt
  Navaids/VOR_UK.txt
Labels: airac, ready-for-review

#3509 Fixes #3506 - Updated GUR VOR Coordiantes due to Magnetic Variation Survey
  .github/CHANGELOG.md
  Navaids/VOR_Non-UK.txt
  Navaids/VOR_UK.txt
Labels: airac, ready-for-review

#3511 Fixes #3510 - Added Fictional "Apron V" for Hawarden (EGNR)
  .github/CHANGELOG.md
  Airports/EGNR/Freetext.txt
  Airports/EGNR/SMR/Regions.txt
Labels: enhancement

#3514 Fixes #3504 - Add Hawarden (EGNR) airways departures
  .github/CHANGELOG.md
  Airports/EGNR/Sids.txt
Labels: api-change-needed, enhancement

#3518 Fixes #3517 - Updated MUAC Delta/Koksy sector boundary
  .github/CHANGELOG.md
  Ownership/AC - Central/13.txt
  Ownership/AC - Central/14.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/Non-UK/Brussels.txt
  Ownership/Non-UK/Maastricht.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - LACC.txt
Labels: procedure-change

#3519 Fixes #3507 - Removed all references to EURI
  .build/ese_template.txt
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
  Ownership/Non-UK/EUR Islands.txt
  Ownership/Non-UK/Reykjavik.txt
  Ownership/Non-UK/Shannon.txt
Labels: procedure-change

#3521 Fixes #3520 - Added St Athan Extended Centrelines
  .github/CHANGELOG.md
  Airports/EGSY/Centreline.txt
Labels: enhancement

#3525 Fixes #3524 - Add various fixes in the northeast corner of the French UTA
  .github/CHANGELOG.md
  Navaids/FIXES_Non-UK.txt
Labels: enhancement, ready-for-review

#3513 Fixes #3512 - Improved Hawarden (EGNR) Centrelines
  .github/CHANGELOG.md
  Airports/EGNR/Centreline.txt
Labels: controller-pack-change, enhancement

#3502 Fixes #3500 - Fixed S5 -> DUB S - ABLIN/LIPGO Auto-Handoff
  .github/CHANGELOG.md
  Airports/EIDW/Fixes.txt
  Airports/EIDW/Stars.txt
Labels: bug, ready-for-review

#3499 Fixes #3498 - Reordered Gatwick SIDs to improve display
  .github/CHANGELOG.md
  Airports/EGKK/Sids.txt
Labels: bug

#3032 Fixes #3023 - Add radar sites/holes
  .build/ese_template.txt
  .github/CHANGELOG.md
  Misc/Radar Holes.txt
  Misc/Radar Sites.txt
Labels: compiler-config-change, enhancement

#3529 Fixes #3528 - Ownership fixes for EGHC/HE/HQ
  .github/CHANGELOG.md
  Airports/EGHC/Ownership.txt
  Airports/EGHE/Ownership.txt
  Airports/EGHQ/Ownership.txt
Labels: bug

#3516 Fixes #3515 - Various updates to Scottish lines/ownership
  .github/CHANGELOG.md
  Airports/EGPB/Sector.txt
  Ownership/ScAC - East/Hebrides.txt
  Ownership/ScAC - East/Montrose.txt
  Ownership/ScAC - West/Deancross.txt
  Ownership/ScAC - West/Rathlin.txt
  Sectors/Lines - PACC.txt
Labels: enhancement

#3523 Fixes #3522 - Fixed EDYY -> Clacton COPX ordering
  .github/CHANGELOG.md
  Agreements/External/YY-D_13.txt
  Agreements/External/YY-K_13.txt
  Agreements/External/YY-K_D (13+14).txt
  Agreements/External/YY-K_E (13+14).txt
Labels: bug

#3493 Separated Heathrow's Bealine and maintenance areas into own group
  .github/CHANGELOG.md
  Airports/EGLL/Freetext.txt
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
  Airports/EGLL/SMR/Regions.txt
  README.md
Labels: enhancement, ready-for-review

#3533 Fix Shannon SOTA Sector Defintion
  .github/CHANGELOG.md
  Sectors/Lines - Ireland.txt
Labels: bug

#3497 Fixes #3496 - Add EGBB Ground Networks
  .github/CHANGELOG.md
  Airports/EGBB/Fixes.txt
  Airports/EGBB/Ground_Network.txt
Labels: enhancement, ready-for-review

#3531 Fixes #3530 - Add EGPH Ground Network
  .github/CHANGELOG.md
  Airports/EGPH/Fixes.txt
  Airports/EGPH/Ground_Network.txt
Labels: enhancement, ready-for-review

#3503 Fixes #3501 - Added Missing Alternate Ownership for Warton (EGNO)
  .github/CHANGELOG.md
  Airports/EGNH/Sector.txt
  Airports/EGNO/Ownership.txt
Labels: bug
