Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2021-07, with the labels that each got.

#3734 Fixes #3732 - Add Southampton (EGHI) Standard Departures
  .github/CHANGELOG.md
  Airports/EGHI/Sids.txt
Labels: enhancement

#3739 Fixes #3735 - Add FF -> GD Inbound COPX
  .github/CHANGELOG.md
  Agreements/Airport/FF_GD.txt
Labels: enhancement

#3741 Fixes #3735 - Add EGHG Sectors
  .github/CHANGELOG.md
  Airports/EGHG/Ownership.txt
  Airports/EGHG/Positions.txt
  Airports/EGHG/Sector.txt
Labels: enhancement

#3744 Fixes #3677 - Missing TC NW/Daventry line
  .github/CHANGELOG.md
  Sectors/Lines - LTC.txt
Labels: bug

#3750 Fixes #3749 - Amended S13->S26 COPX for Severn group inbounds
  .github/CHANGELOG.md
  Agreements/Internal/13_26.txt
Labels: procedure-change

#3748 Fixes #3747 - Fixed GD -> FF Inbound Agreement
  .github/CHANGELOG.md
  Agreements/Airport/GD_FF.txt
Labels: bug

#3737 Fixes #3729 - RAF Linton on Ouse Removed
  .github/CHANGELOG.md
  Airports/EGXU/Airspace.txt
  Airports/EGXU/Basic.txt
  Airports/EGXU/Runway.txt
Labels: airac

#3738 Fixes #3728 - Jersey STARs updated
  .github/CHANGELOG.md
  Agreements/Airport/S_JJ.txt
  Airports/EGJJ/Stars.txt
Labels: airac

#3740 Fixes #3735 - Add London S6 -> TE APP COPX (FF Closed)
  .github/CHANGELOG.md
  Agreements/Airport/6_TE.txt
Labels: enhancement

#3742 Fixes #3735 - Add LETC to HEAPP Sector
  .github/CHANGELOG.md
  Airports/EGHE/Ownership.txt
  Airports/EGHE/Sector.txt
Labels: enhancement

#3754 Fixes #3726 - Aldergrove Radar frequency change
  .github/CHANGELOG.md
  Airports/EGAA/Positions.txt
Labels: airac, on-hold

#3746 Add EGNX Ground Networks
  .github/CHANGELOG.md
  Airports/EGNX/Ground_Network.txt
Labels: enhancement

#3770 Fixes #3766 - Blackpool (EGNH) RWY 28 threshold coord update
  .github/CHANGELOG.md
  Airports/EGNH/Runway.txt
Labels: airac

#3736 Fixes #3735 - EGGD & EGFF Sector Update
  .github/CHANGELOG.md
  Airports/EGFF/Ownership.txt
  Airports/EGFF/Sector.txt
  Airports/EGGD/Ownership.txt
  Airports/EGGD/Sector.txt
  compiler.config.json
Labels: compiler-config-change, enhancement

#3772 Fixes #3762 - Shobdon AFIS Added
  .github/CHANGELOG.md
  Airports/EGBS/Basic.txt
Labels: airac
