Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2022-10, with the labels that each got.

#4417 Fixes 4342 - TC NE top-down ownership
  .github/CHANGELOG.md
  Airports/EGSC/Ownership.txt
  Airports/EGSS/Ownership.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC NE.txt
Labels: enhancement

#4430 Fixes #4429 - Update FIXES_UK.txt from eAIP ENR 4.4
  .github/CHANGELOG.md
  Airports/EGPH/Stars.txt
  Navaids/FIXES_UK.txt
Labels: enhancement

#4436 Fixes #4431 - Fixed AC Lakes static boundary
  .github/CHANGELOG.md
  Sectors/Static/LON/Lakes.txt
Labels: bug

#4437 Fixes #4421 - Fixed Severn group inbound COPX (DVR -> WOR)
  .github/CHANGELOG.md
  Agreements/Internal/26_25.txt
Labels: bug

#4439 Fixes #4438 - Fixed COPX display for LTMA deps via SITET/XAMAB
  .github/CHANGELOG.md
  Agreements/External/18_PN.txt
  Agreements/External/18_RR-E.txt
  Agreements/External/1_RR-Q.txt
  compiler.config.json
Labels: bug

#4440 Fixes #4110 - Fixed Jersey Control COPX function
  .github/CHANGELOG.md
  Agreements/Airport/20_JJ.txt
  Agreements/Airport/21_JJ.txt
  Agreements/Airport/6_JJ.txt
  Agreements/Airport/JJ_21.txt
  Agreements/Airport/JJ_6.txt
  Agreements/Airport/JJ_S.txt
  Agreements/Airport/S_JJ.txt
  Ownership/Non-UK/Brest.txt
  Sectors/Lines - External FIR.txt
Labels: bug

#4441 Fixes #4393 - Fixed COPX Display for DW Inbnds (Lakes -> PC)
  .github/CHANGELOG.md
  compiler.config.json
Labels: bug

#4433 Fixes #4432 - Add and Update Cosford (EGWC) data
  .github/CHANGELOG.md
  Airports/EGWC/Basic.txt
  Airports/EGWC/Runway.txt
  Airports/EGWC/SMR/Geo.txt
  Airports/EGWC/SMR/Regions.txt
  _data/SMR Files/EGWC/Cosford_SMR.kmz
Labels: enhancement, controller-pack-change

#4435 Fixes #4434 - Updated Guernsey (EGJB) SMR
  .github/CHANGELOG.md
  Airports/EGJB/SMR/Geo.txt
  Airports/EGJB/SMR/Regions.txt
  _data/SMR Files/EGJB/EGJB Guernesy.kmz
Labels: enhancement

#4442 Fixses #4424 - Updated Exeter (EGTE) SMR
  .github/CHANGELOG.md
  Airports/EGTE/SMR/Geo.txt
  Airports/EGTE/SMR/Labels.txt
  Airports/EGTE/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGTE/Exeter (EGTE) SMR.kmz
Labels: airac, controller-pack-change

#4444 Fixes #4443 - Removed dummy London sectors
  .github/CHANGELOG.md
  Agreements/Airport/21_Solent.txt
  Agreements/Airport/S_Solent.txt
  Airports/EGHH/Sector.txt
  Airports/EGHI/Sector.txt
  Ownership/AC - South/Dover.txt
  Ownership/AC - South/Worthing.txt
Labels: enhancement

#4452 Fixes #4451 - Update Primary Radar Holes with Windfarm TMZ data
  .github/CHANGELOG.md
  Misc/Radar Holes.txt
Labels: enhancement

#4454 Fixes #4453 - Corrected EGPX Airfield Ownership (ScAC Low)
  .github/CHANGELOG.md
  Airports/EGAA/Ownership.txt
  Airports/EGAC/Ownership.txt
  Airports/EGAE/Ownership.txt
  Airports/EGPA/Ownership.txt
  Airports/EGPB/Ownership.txt
  Airports/EGPC/Ownership.txt
  Airports/EGPD/Ownership.txt
  Airports/EGPE/Ownership.txt
  Airports/EGPF/Ownership.txt
  Airports/EGPH/Ownership.txt
  Airports/EGPK/Ownership.txt
  Airports/EGPN/Ownership.txt
  Airports/EGPO/Ownership.txt
  Ownership/Alternate/Airports - SCO/Central.txt
  Ownership/Alternate/Airports - SCO/Hebrides.txt
  Ownership/Alternate/Airports - SCO/Moray.txt
  Ownership/Alternate/Airports - SCO/Rathlin.txt
  Ownership/Alternate/Airports - SCO/Tay.txt
  Ownership/Alternate/Airports - SCO/Tyne.txt
  Ownership/Alternate/Airports - STC/Antrim.txt
  Ownership/Alternate/Airports - STC/Galloway.txt
  Ownership/Alternate/Airports - STC/Talla.txt
Labels: bug
