Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2022-02, with the labels that each got.

#3977 Fixes #3969 - Stansted (EGSS) SMR Update
  .github/CHANGELOG.md
  Airports/EGSS/SMR/Geo.txt
  Airports/EGSS/SMR/Labels.txt
  Airports/EGSS/SMR/Regions.txt
Labels: airac, controller-pack-change

#3989 Fixes #3987 - Remove Old Heathrow (EGLL) SMR
  .github/CHANGELOG.md
  Airports/EGLL/Freetext.txt
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Regions.txt
Labels: enhancement, ops-input-required

#4030 Fixes #4028 - Amended S29 - Deancross MTMA deps agreement
  .github/CHANGELOG.md
  Agreements/Internal/S29_Dcs.txt
Labels: procedure-change

#4046 Fixes #4045 - New callsign format for Maastricht Eurocontrol (EURM-W_CTR)
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#4052 Fixes #4050 - EGNS Runway HDG
  .github/CHANGELOG.md
  Airports/EGNS/Runway.txt
Labels: airac

#4064 Fixes #4061 - Removed TRIPO from EGLL & EGWU STARs
  .github/CHANGELOG.md
  Airports/EGLL/Stars.txt
  Airports/EGWU/Stars.txt
Labels: error

#4033 Fixes #4019 - Added Debden VRP, Stansted (EGSS)
  .github/CHANGELOG.md
  Airports/EGSS/VRPs.txt
Labels: error

#4031 Fixes #4015 - Aligned EGPX FRA with FIR
  .github/CHANGELOG.md
  Misc/STAR_EGPX FRA.txt
Labels: enhancement

#4044 Fixes #4040 - Internal (Enroute) 25 kHz frequency conversion
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK Permanent.txt
  Misc/Positions_Area Positions 2 UK Event.txt
  Misc/Positions_Area Positions 3 UK Spares.txt
Labels: procedure-change

#4051 Fixes #4047 - Scilly Isles (EGHE) SMR Changes
  .github/CHANGELOG.md
  Airports/EGHE/SMR/Geo.txt
  Airports/EGHE/SMR/Labels.txt
  Airports/EGHE/SMR/Regions.txt
  _data/SMR Files/EGHE/St Marys SMR.kmz
Labels: airac

#4025 Fixes #4022 - CTA/TMA airspace changes - Part 1 (SAIP AD6-related)
  .github/CHANGELOG.md
  ARTCC/High/Clacton CTA.txt
  ARTCC/High/Daventry CTA.txt
  ARTCC/High/London TMA.txt
  ARTCC/High/Midlands CTA.txt
  ARTCC/High/Southern CTA.txt
  Airports/EGSS/Airspace.txt
  Airports/EGSS/Airspace_Bases.txt
  Misc/Freetext_Airspace Bases.txt
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
  Sectors/Lines - LACC.txt
Labels: airac

#4068 Fixes #4067 - Brest Callsign changes
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#4060 Fixes #4058 - EGGW New Transition Fixes
  .github/CHANGELOG.md
  Airports/EGGW/Fixes.txt
Labels: airac

#4056 Fixes #4039 - External 25 kHz frequency conversion
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#4032 Fixes #4024 - Added EGMC Departures to TCNW -> TCSW CPT Agreement
  .github/CHANGELOG.md
  Agreements/Internal/TCNW_TCCPT.txt
  Agreements/Internal/TCNW_TCSW.txt
Labels: procedure-change

#4073 Fixes #4072 - Updated Worthing and Dover Static Boundaries
  .github/CHANGELOG.md
  Sectors/Static/LON/Dover.txt
  Sectors/Static/LON/Worthing.txt
Labels: error

#4065 Fixes #4027 - Changes to Stansted & Luton airspace (SAIP AD6)
  .github/CHANGELOG.md
  Airports/EGGW/Airspace.txt
  Airports/EGGW/Ownership.txt
  Airports/EGGW/RMA.txt
  Airports/EGGW/Sector.txt
  Airports/EGSS/Ownership.txt
  Airports/EGSS/RMA.txt
  Airports/EGSS/Sector.txt
  Misc/STAR_Luton-Stansted Buffer.txt
  Misc/STAR_X-Y Line.txt
  Misc/STAR_XY Line.txt
Labels: procedure-change

#4021 SAIP AD6 - Stansted/Luton position and procedure changes
  .github/CHANGELOG.md
  Agreements/Airport/SS_GW.txt
  Agreements/Airport/SS_SS.txt
  Agreements/Airport/TCLOR_GW.txt
  Agreements/Airport/TCLOR_SS.txt
  Agreements/Airport/TCRED_SS.txt
  Agreements/Internal/TCNW_TCLOR.txt
  Agreements/Internal/TCRED_TCLOR.txt
  Airports/EGGW/Airspace.txt
  Airports/EGGW/Ownership.txt
  Airports/EGGW/RMA.txt
  Airports/EGGW/Sector.txt
  Airports/EGGW/Stars.txt
  Airports/EGSC/Sector.txt
  Airports/EGSS/Ownership.txt
  Airports/EGSS/Positions.txt
  Airports/EGSS/Positions_Mentor.txt
  Airports/EGSS/RMA.txt
  Airports/EGSS/Sector.txt
  Airports/EGSS/Sids.txt
  Misc/STAR_Luton-Stansted Buffer.txt
  Misc/STAR_X-Y Line.txt
  Misc/STAR_XY Line.txt
  Navaids/FIXES_UK.txt
Labels: airac

#4059 Fixes #4057 - Add New Scottish CTAs & Remove Airways
  .github/CHANGELOG.md
  ARTCC/High/Airways.txt
  ARTCC/High/Argyll CTA.txt
  ARTCC/High/Berry Head CTA.txt
  ARTCC/High/Borders CTA.txt
  ARTCC/High/Conditional - Berry Head CTA.txt
  ARTCC/High/Conditional - Borders CTA 5.txt
  ARTCC/High/Conditional - Cotswold CTA.txt
  ARTCC/High/Conditional - N864 (TLA-ASNUD).txt
  ARTCC/High/Conditional - NITON CTA 2.txt
  ARTCC/High/Conditional - P18 (ADN-NATEB) CDR1.txt
  ARTCC/High/Conditional - Portsmouth CTA.txt
  ARTCC/High/Cotswold CTA.txt
  ARTCC/High/Forth CTA.txt
  ARTCC/High/Moray CTA.txt
  ARTCC/High/NITON CTA.txt
  ARTCC/High/Portsmouth CTA.txt
  ARTCC/High/Tay CTA.txt
  Airports/EGNX/Airspace_Bases.txt
  Misc/Freetext_Airspace Bases.txt
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: airac

#4080 Fixes #4075 - Polaris callsign changes
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#4049 Fixes #4034 - New TC CPT, S25 and S23 EGSS departure COPX via KENET
  .github/CHANGELOG.md
  Agreements/Internal/25_23.txt
  Agreements/Internal/TCCPT_23.txt
  Agreements/Internal/TCCPT_25.txt
Labels: procedure-change

#4089 Fixes #4074 - Added all Thames Group airfields to TC SW -> S23 agreement via KENET
  .github/CHANGELOG.md
  Agreements/Internal/TCSW_23.txt
Labels: procedure-change

#4092 Fixes #4091 - Corrected Shoreham (EGKA) Fixes
  .github/CHANGELOG.md
  Airports/EGKA/Fixes.txt
Labels: error

#3984 Fixes #3927 - St Athan (EGSY) ground changes
  .github/CHANGELOG.md
  Airports/EGSY/SMR/Geo.txt
  Airports/EGSY/SMR/Labels.txt
  Airports/EGSY/SMR/Regions.txt
  _data/SMR Files/EGSY/EGSY (2113).kmz
Labels: airac

#4084 Fixes #4083 - Updated EISN and EIDW callsigns
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
  Ownership/Non-UK/Dublin L18.txt
  Ownership/Non-UK/Dublin.txt
  Ownership/Non-UK/Shannon.txt
Labels: enhancement, procedure-change

#4077 Fixes #4076 - Corrected Rathlin/Shannon agreements for ScTMA/EGPK tfc
  .github/CHANGELOG.md
  Agreements/External/Rat_SNE.txt
  Agreements/External/SNE_Rat.txt
Labels: error

#4090 Fixes #4069 - Amended Stansted (EGSS) and Cambridge (EGSC) top-down ownership
  .github/CHANGELOG.md
  Airports/EGSC/Ownership.txt
  Airports/EGSS/Ownership.txt
  Ownership/Alternate/Airports - LTC/E.txt
  Ownership/Alternate/Airports - LTC/NE.txt
  Ownership/Alternate/Airports - LTC/NW.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC NE.txt
Labels: procedure-change

#4093 Fixes #4085 - Added Deancross -> Galloway Belfast Group inbound COPX
  .github/CHANGELOG.md
  Agreements/Internal/Dcs_Gal.txt
Labels: procedure-change

#4095 Fixes #3993 - Scottish FAVA without SMAA
  .github/CHANGELOG.md
  Airports/EGAA/SMAA.txt
  Airports/EGAC/SMAA.txt
  Airports/EGPD/SMAA.txt
  Airports/EGPF/SMAA.txt
  Airports/EGPH/SMAA.txt
  Airports/EGPK/SMAA.txt
Labels: enhancement, controller-pack-change

#4097 Fixes #4094 1/2 - Elstree Additions (Minor)
  .github/CHANGELOG.md
  Airports/EGTR/Airspace.txt
  Airports/EGTR/Positions.txt
  Airports/EGTR/Runways.txt
  Airports/EGTR/VRPs.txt
Labels: enhancement

#4100 Fixes #4099 - Update ARTCC Masts display
  .github/CHANGELOG.md
  ARTCC/Danger Areas/Masts.txt
Labels: error

#4102 Fixes #4101 - Luton and Stansted LFAs
  .github/CHANGELOG.md
  Airports/EGGW/Airspace.txt
  Airports/EGSL/Airspace.txt
  Airports/EGSS/Airspace.txt
Labels: enhancement

#4096 Fixes #4070 - Added Selectable Display Options to aid Essex Group Vectoring
  .github/CHANGELOG.md
  Airports/EGGW/RMA.txt
  Airports/EGSS/RMA.txt
Labels: enhancement

#4103 Fixes #4087 - Fixed CPT/COWLY COPX TC NW -> TC CPT for SS/SC deps
  .github/CHANGELOG.md
  Ownership/TC - LTC/London TC CPT.txt
Labels: bug

#4105 Fixes #4104 - Corrected COPX for LTMA deps via LELNA/LORKU
  .github/CHANGELOG.md
  Agreements/External/20_RR-V.txt
Labels: error

#4106 Fixes #4086 - Amended Scottish internal event agreements
  .github/CHANGELOG.md
  Agreements/Internal/Mon_Tay.txt
  Agreements/Internal/Tyne_Mon.txt
  Ownership/TC - STC/Tay.txt
Labels: enhancement

#4109 Fixes #4107 - Added EGTK and EGSC to TC COWLY -> S25 COPX
  .github/CHANGELOG.md
  Agreements/Internal/TCCOW_TCCPT.txt
Labels: procedure-change

#4113 Fixes #4112 - SAIP AD6 Bug Fixes
  Agreements/Internal/TCCOW_TCNW.txt
  Agreements/Internal/TCVAT_TCLOR.txt
  Airports/EGGW/Stars.txt
  Airports/EGSS/Airspace.txt
  Airports/EGSS/Positions.txt
  Airports/EGSS/Positions_Mentor.txt
Labels: error

#4038 Fixes #4026 - SAIP AD6 London Sector Changes
  .github/CHANGELOG.md
  Ownership/AC - Central/12.txt
  Ownership/AC - Central/28.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC NE.txt
  Ownership/TC - LTC/London TC NW.txt
  Ownership/TC - LTC/London TC REDFA.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
  Sectors/Static/LON/Daventry.txt
  Sectors/Static/LTC/East.txt
  Sectors/Static/LTC/North East.txt
  Sectors/Static/LTC/North West.txt
Labels: procedure-change
