Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2022-05, with the labels that each got.

#4232 Fixes #4231 - Change to PC Trent/TC WELIN sectorisation north of ELVOS
  .github/CHANGELOG.md
  Ownership/TC - LTC/London TC WELIN.txt
  Ownership/TC - MPC/SE Trent.txt
Labels: procedure-change

#4239 Fixes #4238 - Amended Midlands Buffer Zone width
  .github/CHANGELOG.md
  Airports/EGBB/RMA.txt
  Misc/STAR_Midlands Buffer Zone.txt
Labels: procedure-change

#4261 Fixes #4252 - Heathrow (EGLL) stands renumbered
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
Labels: airac

#4265 Fixes #4253 - Norwich (EGSH) runway definition update
  .github/CHANGELOG.md
  Airports/EGSH/Runway.txt
Labels: airac

#4266 Fixes #4256 - Updated Moray CTA 16 base
  .github/CHANGELOG.md
  ARTCC/High/Moray CTA.txt
Labels: airac

#4271 Fixes #4262 - Updated Heathrow (EGLL) SMR to remove WIP
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Regions.txt
Labels: procedure-change

#4158 Fixes #4157 - Update Edinburgh (EGPH) SMR
  .github/CHANGELOG.md
  Airports/EGPH/SMR/Geo.txt
  Airports/EGPH/SMR/Labels.txt
  Airports/EGPH/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGPH/(OLD) Edinburgh - EGPH SMR.kmz
  _data/SMR Files/EGPH/Edinburgh SMR 202204.kmz
Labels: enhancement

#4274 Fixes #4273 - Fix SANBA SID Drawing and Tracking
  .github/CHANGELOG.md
  Airports/EGCC/Fixes.txt
  Airports/EGCC/Sids.txt
Labels: bug

#4270 Fixes #4267 - Remove Sywell (EGBK) RNP Fixes
  .github/CHANGELOG.md
  Airports/EGBK/Fixes.txt
Labels: error

#4197 Fixes #4196 - Added Oban (EGEO) SMR
  .github/CHANGELOG.md
  Airports/EGEO/SMR/Geo.txt
  Airports/EGEO/SMR/Labels.txt
  Airports/EGEO/SMR/Regions.txt
  _data/SMR Files/EGEO/EGEO Oban.kmz
Labels: enhancement, controller-pack-change

#4206 Fixes #4204 - Updated Wellesbourne (EGBW) SMR
  .github/CHANGELOG.md
  Airports/EGBW/SMR/Geo.txt
  Airports/EGBW/SMR/Regions.txt
  _data/SMR Files/EGBW/EGBW--SMR.kmz
Labels: enhancement

#4272 Fixes #4268 - Change to external COPX S6/36 and LFRR-V for Severn outbounds
  .github/CHANGELOG.md
  Agreements/External/36_RR-V.txt
  Agreements/External/6_RR-V.txt
  compiler.config.json
Labels: procedure-change

#4236 Fixes #4235 - Changes to external COPX for traffic via SITET
  .github/CHANGELOG.md
  Agreements/External/18_PN.txt
Labels: procedure-change

#4250 AIRAC 2205 - Various 5LNC, STAR and ATS Route Updates
  .github/CHANGELOG.md
  Airports/EGBB/Stars.txt
  Airports/EGBE/Stars.txt
  Airports/EGFF/Stars.txt
  Airports/EGGD/Stars.txt
  Airports/EGNX/Stars.txt
  Airways/RNAV/Upper/UL975.txt
  Navaids/FIXES_UK.txt
  Navaids/VOR_UK.txt
Labels: airac

#4259 Fixes #4255 - New Manchester (EGCC) RNAV STARs
  .github/CHANGELOG.md
  Airports/EGCC/Fixes.txt
  Airports/EGCC/Stars.txt
Labels: airac

#4260 Fixes #4254 - New Liverpool (EGGP) RNAV STARs
  .github/CHANGELOG.md
  Airports/EGGP/Stars.txt
  Airports/EGNR/Stars.txt
Labels: airac

#4276 Fixes #4251 - Gloucestershire (EGBJ) Runway 18-36 Closed
  .github/CHANGELOG.md
  Airports/EGBJ/Runway.txt
Labels: airac

#4234 Fixes #4233 - Change to S36/S20 sectorisation near OTMET
  .github/CHANGELOG.md
  Ownership/AC - South/1.txt
  Ownership/AC - South/20.txt
  Ownership/AC - South/21.txt
  Ownership/AC - West/36.txt
  Ownership/AC - West/6.txt
  Sectors/Lines - LACC.txt
  Sectors/Static/LON/AC West.txt
  Sectors/Static/LON/Exmoor.txt
  Sectors/Static/LON/Sector 23.txt
  Sectors/Static/LON/Worthing.txt
Labels: procedure-change

#4280 Fixes #4279 - Fix erroneous A-Ireland point
  .github/CHANGELOG.md
  Misc/Regions_GB Landmass Medium Detail.txt
Labels: error

#4278 Fixes #4277 - Updated Gloucestershire (EGBJ) SMR
  .github/CHANGELOG.md
  Airports/EGBJ/SMR/Geo.txt
  Airports/EGBJ/SMR/Labels.txt
  Airports/EGBJ/SMR/Regions.txt
  _data/SMR Files/EGBJ/Gloucestershire SMR 2207.kmz
Labels: enhancement

#4264 Fixes #4263 - Montrose <-> East agreement changes
  .github/CHANGELOG.md
  Agreements/Internal/East_Mon.txt
  Agreements/Internal/Mon_East.txt
Labels: procedure-change

#4282 Fixes #4281 - Remove superfluous lines from Prestwick (EGPK) SMR
  .github/CHANGELOG.md
  Airports/EGPK/SMR/Geo.txt
Labels: enhancement
