Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2022-01, with the labels that each got.

#3950 Fixes #3926 - NEW Oxford (EGTK) SMR Update
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Labels.txt
Labels: controller-pack-change

#3954 Fixes #3953 - Corrected sector line error (London S25)
  .github/CHANGELOG.md
  Ownership/AC - South/25.txt
  Sectors/Lines - LACC.txt
Labels: bug

#3914 Fixes #3913 - Adds Major Hospital Helipad Markers
  .github/CHANGELOG.md
  Misc/Freetext_UK HEMS.txt
Labels: enhancement

#3980 Fixes #3961 - Updated VALBO coordinates
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: airac

#3973 Fixes #3965 Land's End (EGHC) Holding Points
  .github/CHANGELOG.md
  Airports/EGHC/SMR/Labels.txt
Labels: airac

#3986 Fixes #3968 - Manchester (EGCC) New De-Icing Areas
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
Labels: controller-pack-change

#3976 Fixes #3962 - Added Windsor Castle Restricted Airspace (R156)
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG R156.txt
Labels: airac

#3974 Fixes #3972 Isle of Man (EGNS) Runway 08 Threshold Coordinates
  .github/CHANGELOG.md
  Airports/EGNS/Runway.txt
Labels: airac

#3975 Fixes #3971 - Shobdon (SH) NDB Coordinates
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac

#3982 Fixes #3967 Swansea Heli Changes
  .github/CHANGELOG.md
  Airports/EGFH/SMR/Geo.txt
  Airports/EGFH/SMR/Labels.txt
Labels: airac

#3991 Fixes #3990 - Norwich Runway Heading update
  .github/CHANGELOG.md
  Airports/EGSH/Runway.txt
Labels: airac

#4002 Fixes #4001 - Added 26's L Indicator EGKK
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Regions.txt
Labels: enhancement

#3997 Fixes #3996 - Kinloss portion of CMATZ Withdrawn
  .github/CHANGELOG.md
  Airports/EGQK/Airspace.txt
Labels: procedure-change

#3978 Fixes #3970 - Updated Eglinton (EGAE) stand coordinates
  .github/CHANGELOG.md
  Airports/EGAE/SMR/Labels.txt
Labels: airac

#3983 Fixes #3963 - Glasgow (EGPF) Taxiway Closure
  .github/CHANGELOG.md
  Airports/EGPF/SMR/Geo.txt
  Airports/EGPF/SMR/Labels.txt
  Airports/EGPF/SMR/Regions.txt
Labels: airac

#3999 Fixes #3998 - Fixed bug in TC SE sector line
  .github/CHANGELOG.md
  Sectors/Lines - LTC.txt
Labels: bug

#3981 Fixes #3964 - Gloucestershire Disused Taxiway SMR Change
  .github/CHANGELOG.md
  Airports/EGBJ/SMR/Geo.txt
  Airports/EGBJ/SMR/Labels.txt
  Airports/EGBJ/SMR/Regions.txt
  _data/SMR Files/EGBJ/EGBJ 2106.kmz
  _data/SMR Files/EGBJ/Gloucestershire SMR.kmz
Labels: airac

#4004 Fixes #4003 - Heathrow WIP Partial removal
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Regions.txt
Labels: error

#4000 Fixes #3543 - LAC South (and associated sectors) Line Display
  .github/CHANGELOG.md
  Ownership/AC - Central/12.txt
  Ownership/AC - South/1.txt
  Ownership/AC - South/15.txt
  Ownership/AC - South/17.txt
  Ownership/AC - South/18.txt
  Ownership/AC - South/19.txt
  Ownership/AC - South/2.txt
  Ownership/AC - South/20.txt
  Ownership/AC - South/21.txt
  Ownership/AC - South/22.txt
  Ownership/AC - South/24.txt
  Ownership/AC - South/25.txt
  Ownership/AC - South/26.txt
  Ownership/AC - West/23.txt
  Ownership/AC - West/36.txt
  Ownership/AC - West/6.txt
  Ownership/Non-UK/Brest.txt
  Ownership/TC - LTC/London TC CPT.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC LOREL.txt
  Ownership/TC - LTC/London TC REDFA.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC SW.txt
  Ownership/TC - LTC/London TC VATON.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
Labels: enhancement

#4007 Fixes #4005 #4006 - Updated Area Position definitions
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK Permanent.txt
  Misc/Positions_Area Positions 2 UK Event.txt
Labels: enhancement, procedure-change

#3955 Fixes #3876 - Added London OTMET position (event only)
  .github/CHANGELOG.md
  Airports/EGHH/Ownership.txt
  Airports/EGHI/Ownership.txt
  Airports/EGJA/Ownership.txt
  Airports/EGJB/Ownership.txt
  Airports/EGJJ/Ownership.txt
  Airports/EGTE/Ownership.txt
  Misc/Positions_Area Positions 2 UK Event.txt
  Misc/Positions_Area Positions 3 UK Spares.txt
  Ownership/AC - South/20.txt
  Ownership/AC - South/21.txt
  Ownership/AC - South/22.txt
  Ownership/AC - West/36.txt
  Ownership/AC - West/6.txt
Labels: enhancement

#3957 Fixes #3956 - Simplified and corrected UK VATSIM frequencies doc
  Doc/UK VATSIM frequencies.txt
Labels: enhancement

#3958 Various airways changes, updates and folder adjustment
  .github/CHANGELOG.md
  Airways/Conventional - Non-UK/Lower/A25.txt
  Airways/Conventional - Non-UK/Lower/A30.txt
  Airways/Conventional - Non-UK/Lower/A34.txt
  Airways/Conventional - Non-UK/Lower/B24.txt
  Airways/Conventional - Non-UK/Lower/B3.txt
  Airways/Conventional - Non-UK/Lower/G27.txt
  Airways/Conventional - Non-UK/Lower/G271.txt
  Airways/Conventional - Non-UK/Lower/G272.txt
  Airways/Conventional - Non-UK/Lower/G273.txt
  Airways/Conventional - Non-UK/Lower/G274.txt
  Airways/Conventional - Non-UK/Lower/J20.txt
  Airways/Conventional - Non-UK/Lower/J22.txt
  Airways/Conventional - Non-UK/Lower/R50.txt
  Airways/Conventional - Non-UK/Lower/V2.txt
  Airways/Conventional - Non-UK/Lower/V3.txt
  Airways/Conventional/Lower/N580.txt
  Airways/Conventional/Lower/P20.txt
  Airways/Helicopter/H10.txt
  Airways/Helicopter/H2.txt
  Airways/Helicopter/H22.txt
  Airways/Helicopter/H3.txt
  Airways/Helicopter/H4.txt
  Airways/Helicopter/H5.txt
  Airways/Helicopter/H7.txt
  Airways/Helicopter/H9.txt
  Airways/Helicopter/LF-HE.txt
  Airways/Helicopter/LF-HN.txt
  Airways/Helicopter/LF-HS.txt
  Airways/Helicopter/LF-HW.txt
  Airways/Other/T13.txt
  Airways/Other/T16.txt
  Airways/Other/T213.txt
  Airways/Other/T290.txt
  Airways/Other/T9.txt
  Airways/Other/TB1.txt
  Airways/Other/TB2.txt
  Airways/Other/TB3.txt
  Airways/Other/TB6.txt
  Airways/Other/TB7.txt
  Airways/Other/TL4.txt
  Airways/Other/TR1.txt
  Airways/Other/TR3.txt
  Airways/RNAV/Lower/L612.txt
  Airways/RNAV/Lower/L975.txt
  Airways/RNAV/Lower/N57.txt
  Airways/RNAV/Lower/N601.txt
  Airways/RNAV/Lower/P16.txt
  Airways/RNAV/Lower/P17.txt
  Airways/RNAV/Lower/P25.txt
  Airways/RNAV/Lower/P7.txt
  Airways/RNAV/Lower/T256.txt
  Airways/RNAV/Lower/Y250.txt
  compiler.config.json
Labels: enhancement

#4012 Corrected S1 and S17 sector definitions
  Ownership/AC - South/1.txt
  Ownership/AC - South/17.txt
Labels: bug

#4014 Various ownership and sector line fixes
  Airports/EGLF/Ownership.txt
  Ownership/AC - Central/27.txt
  Ownership/AC - Central/28.txt
  Ownership/AC - North/10.txt
  Ownership/AC - South/25.txt
  Ownership/AC - South/26.txt
  Ownership/ScAC - West/Rathlin.txt
  Ownership/TC - LTC/London TC CPT.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC VATON.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Ownership/TC - MPC/SE Trent.txt
  Ownership/TC - STC/Tay.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
  Sectors/Lines - PACC.txt
Labels: bug
