Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2022-06, with the labels that each got.

#4287 Fixes #4285 - Update Goodwood (GWC) VOR co-ordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#4294 Fixes #4284 - Update Lee-on-Solent (EGHF) SMR
  .github/CHANGELOG.md
  Airports/EGHF/SMR/Geo.txt
  Airports/EGHF/SMR/Labels.txt
  Airports/EGHF/SMR/Regions.txt
  _data/SMR Files/EGHF/EGHF.kmz
Labels: airac

#4301 Fixes #4300 - Removed EGCC SID 'RWxxx' fixes
  .github/CHANGELOG.md
  Airports/EGCC/Sids.txt
Labels: enhancement

#4302 Fixes #4283 - Update Biggin Hill (EGKB) SMR
  .github/CHANGELOG.md
  Airports/EGKB/SMR/Geo.txt
  Airports/EGKB/SMR/Labels.txt
  Airports/EGKB/SMR/Regions.txt
  _data/SMR Files/EGKB/EGKB-2206.kmz
Labels: airac

#4304 Fixes #4303 - Updated MTMA inbound Dav -> PC SE COPX
  .github/CHANGELOG.md
  Agreements/Internal/28_Trent.txt
Labels: enhancement

#4305 Fixes #2594 - Update East Midlands (EGNX) SMR
  .github/CHANGELOG.md
  Airports/EGNX/SMR/Geo.txt
  Airports/EGNX/SMR/Labels.txt
  Airports/EGNX/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGNX/EGNX.kmz
Labels: airac

#4308 Fixes #4307 - Corrected St Athan (EGSY) Ownership
  .github/CHANGELOG.md
  Airports/EGSY/Ownership.txt
Labels: bug

#4312 Fixes #4306 - Corrected coordinates of waypoint ABDAL
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: error

#4313 Fixes #4310 - Goodwood (EGHR) RWY THR coordinates updated
  .github/CHANGELOG.md
  Airports/EGHR/Runway.txt
Labels: airac

#4314 Fixes #4311 - Dundee (EGPN) RWY THR coordinates updated
  .github/CHANGELOG.md
  Airports/EGPN/Runway.txt
Labels: airac
