Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-05, with the labels that each got.

#4705 Fixes #4704 - Add TDA D597
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D597.txt
Labels: enhancement

#4703 Fixes #4702 - Stansted (EGSS) Swapping stands 64L and 64R around
  .github/CHANGELOG.md
  Airports/EGSS/SMR/Labels.txt
Labels: bug, good-first-issue

#4707 Fixes #4706 - Update Manchester (EGCC) Z Lines
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
Labels: enhancement

#4722 Fixes #4721 - Add option for coastline
  .github/CHANGELOG.md
  Colours.txt
Labels: enhancement

#4701 Fixes #4700 - Fix Blackpool (EGNH) and Warton (EGNO) VRPs
  .github/CHANGELOG.md
  Airports/EGNH/VRPs.txt
Labels: bug

#4719 Fixes #4711 - Move Jersey (EGJJ) holds A4 and A3 slighty
  .github/CHANGELOG.md
  Airports/EGJJ/SMR/Regions.txt
  _data/SMR Files/EGJJ/Jersey SMR 2305.kmz
Labels: airac

#4717 Fixes #4716 - Removed 2+ year old procedures and fixes
  .github/CHANGELOG.md
  Airports/EGGW/Stars.txt
  Airports/EGKB/Stars.txt
  Airports/EGKK/Fixes.txt
  Airports/EGKK/Sids.txt
  Airports/EGLC/Stars.txt
  Airports/EGMC/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
  Airways/RNAV/Upper/Y312.txt
  Navaids/FIXES_Old.txt
Labels: enhancement

#4718 Fixes #4712 - Update Sumburgh (EGPB) stand numbers
  .github/CHANGELOG.md
  Airports/EGPB/SMR/Geo.txt
  Airports/EGPB/SMR/Labels.txt
Labels: airac

#4723 Fixes #4713 - Update Wolverhampton (EGBO) SMR & Define Runway 10-28
  .github/CHANGELOG.md
  Airports/EGBO/Runway.txt
  Airports/EGBO/SMR/Geo.txt
  Airports/EGBO/SMR/Labels.txt
  Airports/EGBO/SMR/Regions.txt
  _data/SMR Files/EGBO/EGBO SMR 2003.kmz
  _data/SMR Files/EGBO/EGBO SMR 2305.kmz
Labels: airac

#4724 Fixes #4714 - Update Manchester (EGCC) SMR around new T2 Construction Area
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  _data/SMR Files/EGCC/EGCC_SMR_23-05.kmz
Labels: airac

#4720 Fixes #4715 - Add New Luton (EGGW) Delta Apron and stands
  .github/CHANGELOG.md
  Airports/EGGW/SMR/Geo.txt
  Airports/EGGW/SMR/Labels.txt
  Airports/EGGW/SMR/Regions.txt
  _data/SMR Files/EGGW/Luton SMR.kmz
Labels: airac

#4730 Fixes #4708 - Update Dunkeswell (EGTU) Threshold Coords
  .github/CHANGELOG.md
  Airports/EGTU/Runway.txt
Labels: airac

#4731 Fixes #4726 - Added TCNW -> TCSW LF/Wessex Inbound Agreement
  .github/CHANGELOG.md
  Agreements/Internal/TCNW_TCSW.txt
Labels: bug

#4729 Fixes #4709 - Define Chalgrove (EGLJ) runway 12/30
  .github/CHANGELOG.md
  Airports/EGLJ/Runway.txt
Labels: airac

#4732 Fixes #4710 - Update Bristol (EGGD) SMR
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
  Airports/EGGD/SMR/Regions.txt
  _data/SMR Files/EGGD/EGGD 2305.kmz
Labels: airac

#4734 Fixes #4733 - Fixed ESSEX_APP online rings (also standardised LTMA APP ring sizes)
  .github/CHANGELOG.md
  Airports/EGGW/Ownership.txt
  Airports/EGGW/Sector.txt
  Airports/EGHI/Sector.txt
  Airports/EGLC/Sector.txt
  Airports/EGSS/Ownership.txt
  Airports/EGSS/Sector.txt
Labels: bug

#4741 Fixes #4738 - Updated Humberside (EGNJ) Runway Headings
  .github/CHANGELOG.md
  Airports/EGNJ/Runway.txt
Labels: airac

#4727 Fixes #4725 - Updated various MIL RWY Headings
  .github/CHANGELOG.md
  Airports/EGOE/Runway.txt
  Airports/EGOQ/Runway.txt
  Airports/EGOS/Runway.txt
  Airports/EGUN/Runway.txt
  Airports/EGVO/Runway.txt
  Airports/EGWU/Runway.txt
  Airports/EGXT/Runway.txt
  Airports/EGXZ/Runway.txt
Labels: airac

#4749 Fixes #4746 - Default coastline colour
  .github/CHANGELOG.md
  Colours.txt
Labels: enhancement

#4747 Fixes #4745 - Update Glasgow (EGPF) Fava Colour
  .github/CHANGELOG.md
  Airports/EGPF/SMAA.txt
  Colours.txt
Labels: enhancement
