Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-04, with the labels that each got.

#4673 Fixes #4671 - Added EGTK RWY 19 extended centreline
  .github/CHANGELOG.md
  Airports/EGTK/Centreline.txt
Labels: enhancement

#4670 Fixes #4668 - Corrected OCAS region coords Cotswold CTA
  .github/CHANGELOG.md
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: bug

#4669 Fixes #4667 - Corrected Biggin Hill (EGKB) STARs
  .github/CHANGELOG.md
  Airports/EGKB/Stars.txt
Labels: bug

#4681 Fixes #4680 - Fixed LKS/NOR alternative sector ownership
  .github/CHANGELOG.md
  Ownership/AC - North/10.txt
  Ownership/AC - North/11.txt
  Ownership/AC - North/3.txt
  Ownership/AC - North/4.txt
  Ownership/AC - North/7.txt
Labels: bug

#4687 Fixes #4686 - TC SW -> S23 LL/KK/WU deps agreement
  .github/CHANGELOG.md
  Agreements/Internal/TCSW_23.txt
Labels: bug

#4679 Fixes #4675 - Various VRP Updates (AIRAC 2304)
  .github/CHANGELOG.md
  Airports/EGAA/VRPs.txt
  Airports/EGAE/VRPs.txt
  Airports/EGCM/VRPs.txt
  Airports/EGEC/VRPs.txt
  Airports/EGGP/VRPs.txt
  Airports/EGNM/VRPs.txt
  Airports/EGNO/VRPs.txt
  Airports/EGNS/VRPs.txt
  Airports/EGNV/VRPs.txt
  Airports/EGPB/VRPs.txt
  Airports/EGPE/VRPs.txt
  Airports/EGPF/VRPs.txt
  Airports/EGPH/VRPs.txt
  Airports/EGPK/VRPs.txt
  Airports/EGPO/VRPs.txt
  Airports/EGPU/VRPs.txt
  Airports/EGSH/VRPs.txt
Labels: airac

#4697 Fixes #4677 - Update Bristol (EGGD) Stands on SMR
  .github/CHANGELOG.md
  Airports/EGGD/Ground Map/Freetext.txt
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
  Airports/EGGD/SMR/Regions.txt
Labels: airac

#4693 Fixes #4691 - Added pseudo LAC S14 ownership for agreement display
  .github/CHANGELOG.md
  Agreements/Internal/14_TCJAC.txt
  Ownership/AC - Central/14.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/Non-UK/Brussels.txt
  Ownership/Non-UK/Maastricht.txt
  Sectors/Lines - External FIR.txt
Labels: enhancement

#4692 Fixes #4690 - Added missing PC IoM -> WAL EGNM inbound agreement
  Agreements/Internal/IoM_Wal.txt
Labels: bug

#4683 Fixes #4682 - Update Stansted (EGSS) Air Network
  .github/CHANGELOG.md
  Airports/EGSS/Fixes.txt
Labels: ground/air-network

#4694 Fixes #4676 - Fixed ESSEX_APP / London line display
  .github/CHANGELOG.md
  Airports/EGGW/Ownership.txt
  Airports/EGSS/Ownership.txt
Labels: bug

#4685 Fixes #4684 - Add grass taxiway labels to Oxford (EGTK) SMR
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Labels.txt
  Airports/EGTK/SMR/Regions.txt
Labels: airac
