Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-07, with the labels that each got.

#4769 Fixes #4768 - Add Farnborough (EGLF) Apron B
  .github/CHANGELOG.md
  Airports/EGLF/Ground Map/Labels.txt
  Airports/EGLF/SMR/Geo.txt
  Airports/EGLF/SMR/Labels.txt
  Airports/EGLF/SMR/Regions.txt
Labels: airac

#4787 Fixes #4775 - Update Compton Abbas (EGHA) ARP
  .github/CHANGELOG.md
  Airports/EGHA/Basic.txt
Labels: airac

#4785 Fixes #4777 - Update NDB LBA Coordinates
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac

#4773 Fixes #4772 - Add Cambridge (EGSC) SMAA Altitudes
  .github/CHANGELOG.md
  Airports/EGSC/SMAA_Bases.txt
Labels: enhancement

#4771 Fixes #4770 - Add Edinburgh (EGPH) 10nm-20nm centerline
  .github/CHANGELOG.md
  Colours.txt
  Misc/SID_Edinburgh Centreline.txt
Labels: enhancement

#4793 Fixes #4778 - Updated London City (EGLC) Runway Data
  .github/CHANGELOG.md
  Airports/EGLC/Runway.txt
Labels: airac

#4794 Fixes #4790 - Update Fairford (EGVA) SID Designators
  .github/CHANGELOG.md
  Airports/EGVA/Sids.txt
Labels: airac

#4792 Fixes #4782 - Update Belfast Aldergrove (EGAA) Stands
  .github/CHANGELOG.md
  Airports/EGAA/SMR/Geo.txt
  Airports/EGAA/SMR/Labels.txt
  _data/SMR Files/EGAA/Belfast Aldergrove SMR.kmz
Labels: bug

#4791 Fixes #4776 - Add Guernsey (EGJB) Stands 2A and 3A and hold F line
  .github/CHANGELOG.md
  Airports/EGJB/SMR/Geo.txt
  Airports/EGJB/SMR/Labels.txt
  _data/SMR Files/EGJB/EGJB Guernesy.kmz
Labels: airac

#4789 Fixes #4781 - Update Prestwick (EGPK) SMAA
  .github/CHANGELOG.md
  Airports/EGPK/SMAA.txt
Labels: airac

#4788 Fixes #4780 - Remove Gatwick (EGKK) Stand 551
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Labels.txt
  _data/SMR Files/EGKK/Gatwick SMR 2307.kmz
Labels: airac

#4767 Fixes #4766 - Updated Manchester (EGCC) Q1 Position and add Q2
  .github/CHANGELOG.md
  Airports/EGCC/Ground Map/Freetext.txt
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  _data/SMR Files/EGCC/Manchester SMR.kmz
Labels: airac

#4798 Fixes #4797 - Added Tug Point to Southend (EGMC) SMR
  .github/CHANGELOG.md
  Airports/EGMC/SMR/Geo.txt
  Airports/EGMC/SMR/Labels.txt
  _data/SMR Files/EGMC/EGMC_Aerodrome_Chart_07-23.png
Labels: enhancement

#4810 Fixes #4809 - Correct Cardiff (EGFF) Holding Point C name
  .github/CHANGELOG.md
  Airports/EGFF/SMR/Labels.txt
Labels: bug

#4831 Fixes #4830 - Add Exeter (EGTE) ATZ
  .github/CHANGELOG.md
  Airports/EGTE/Airspace.txt
Labels: enhancement

#4813 Fixes #4812 - Remove Leeds Bradford (EGNM) Holding Point M1
  .github/CHANGELOG.md
  Airports/EGNM/SMR/Geo.txt
  Airports/EGNM/SMR/Labels.txt
Labels: bug

#4829 Fixes #4827 - Add Belfast City (EGAC) Stands 21 and 24
  .github/CHANGELOG.md
  Airports/EGAC/SMR/Geo.txt
  Airports/EGAC/SMR/Labels.txt
  _data/SMR Files/EGAC/Belfast City SMR.kmz
Labels: enhancement

#4820 Fixes #4779 - Add London City (EGLC) Stand 10L
  .github/CHANGELOG.md
  Airports/EGLC/SMR/Labels.txt
Labels: airac

#4833 Fixes #4832 - Add EGSH and EGNJ inbound agreements via RAVLO
  .github/CHANGELOG.md
  Agreements/External/YY-D_11.txt
Labels: airac

#4806 Fixes #4805 - Add Campbeltown (EGEC) SMR
  .github/CHANGELOG.md
  Airports/EGEC/Active_Runway.txt
  Airports/EGEC/Positions.txt
  Airports/EGEC/Runway.txt
  Airports/EGEC/SMR/Geo.txt
  Airports/EGEC/SMR/Labels.txt
  Airports/EGEC/SMR/Regions.txt
  _data/SMR Files/EGEC/EGEC.kmz
Labels: enhancement

#4802 Fixes #4801 - Add Kemble (EGBP) Stands 1-4
  .github/CHANGELOG.md
  Airports/EGBP/SMR/Labels.txt
Labels: enhancement

#4808 Fixes #4807 - Birmingham (EGBB) Holding Point J1 incorrectly named
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Labels.txt
Labels: bug

#4835 Fixes #4834 - Improve Redhill (EGKR) SMR Display
  .github/CHANGELOG.md
  Airports/EGKR/SMR/Geo.txt
  Airports/EGKR/SMR/Labels.txt
  Airports/EGKR/SMR/Regions.txt
  _data/SMR Files/EGKR/EGKR.kmz
Labels: enhancement

#4823 Fixes #4822 - Update all incorrect fixes for airport RNAV sids / RNAV approaches
  .github/CHANGELOG.md
  Airports/EGBB/Fixes.txt
  Airports/EGBJ/Fixes.txt
  Airports/EGKK/Fixes.txt
  Airports/EGLL/Fixes.txt
  Airports/EGMD/Fixes.txt
  Airports/EGNL/Fixes.txt
  Airports/EGNT/Fixes.txt
  Airports/EGPU/Fixes.txt
  Airports/EGSC/Fixes.txt
  Airports/EGTC/Fixes.txt
Labels: bug

#4858 Fixes #4850 - Remove Haverfordwest (HAV) NDB
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac

#4844 Fixes #4843 - Standardise Holding Point Ordering in Labels
  Airports/EGBB/SMR/Labels.txt
  Airports/EGBK/SMR/Labels.txt
  Airports/EGBO/SMR/Labels.txt
  Airports/EGBS/SMR/Labels.txt
  Airports/EGCB/SMR/Labels.txt
  Airports/EGDR/SMR/Labels.txt
  Airports/EGEO/SMR/Labels.txt
  Airports/EGET/SMR/Labels.txt
  Airports/EGFF/SMR/Labels.txt
  Airports/EGFH/SMR/Labels.txt
  Airports/EGGD/SMR/Labels.txt
  Airports/EGGP/SMR/Labels.txt
  Airports/EGGW/SMR/Labels.txt
  Airports/EGHC/SMR/Labels.txt
  Airports/EGHG/SMR/Labels.txt
  Airports/EGHO/SMR/Labels.txt
  Airports/EGHQ/SMR/Labels.txt
  Airports/EGJJ/SMR/Labels.txt
  Airports/EGKA/SMR/Labels.txt
  Airports/EGKR/SMR/Labels.txt
  Airports/EGLC/SMR/Labels.txt
  Airports/EGLF/SMR/Labels.txt
  Airports/EGMC/SMR/Labels.txt
  Airports/EGMD/SMR/Labels.txt
  Airports/EGNE/SMR/Labels.txt
  Airports/EGNO/SMR/Labels.txt
  Airports/EGNS/SMR/Labels.txt
  Airports/EGNT/SMR/Labels.txt
  Airports/EGNX/SMR/Labels.txt
  Airports/EGPA/SMR/Labels.txt
  Airports/EGPC/SMR/Labels.txt
  Airports/EGPG/SMR/Labels.txt
  Airports/EGSC/SMR/Labels.txt
  Airports/EGTF/SMR/Labels.txt
  Airports/EGTK/SMR/Labels.txt
  Airports/EGTO/SMR/Labels.txt
  Airports/EGTR/SMR/Labels.txt
Labels: enhancement

#4819 Fixes #4818 - Fix incorrect Non-UK FIX coordinates (Netherlands)
  .github/CHANGELOG.md
  Navaids/FIXES_Non-UK.txt
Labels: bug

#4804 Fixes #4803 - Add White Waltham (EGLM) SMR
  .github/CHANGELOG.md
  Airports/EGLM/Positions.txt
  Airports/EGLM/SMR/Labels.txt
  Airports/EGLM/SMR/Regions.txt
  _data/SMR Files/EGLM/EGLM.kmz
Labels: enhancement

#4864 Fixes #4847 - Update Bournemouth (BIA) NDB Coordinate
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac

#4696 Fixes #4695 - Added EGNX SID Lines and VFR Lanes
  .github/CHANGELOG.md
  Colours.txt
  Misc/Geo_Long Eaton Shepshed Lanes.txt
  Misc/STAR_EGNX SID Lines 09.txt
  Misc/STAR_EGNX SID Lines 27.txt
Labels: enhancement

#4863 Fixes #4862 - Correct Guernsey (EGJB) Approach Identifiers
  .github/CHANGELOG.md
  Airports/EGJA/Ownership.txt
  Airports/EGJB/Ownership.txt
  Airports/EGJB/Positions.txt
  Airports/EGJB/Positions_Mentor.txt
Labels: bug

#4856 Fixes #4853 - Remove Oxford (EGTK) holding point G
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Geo.txt
  Airports/EGTK/SMR/Labels.txt
  _data/SMR Files/EGTK/EGTK.kmz
  _data/SMR Files/EGTK/Old KMZs/Oxford SMR (2101).kmz
  _data/SMR Files/EGTK/Old KMZs/Oxford SMR (2105).kmz
  _data/SMR Files/EGTK/Old KMZs/Oxford SMR (2208).kmz
  _data/SMR Files/EGTK/Old KMZs/Oxford SMR (2303).kmz
  _data/SMR Files/EGTK/Old KMZs/Oxford SMR (OLD).kmz
Labels: airac

#4880 Fixes #4846 - Update Bournemouth (EGHH) runway threshold coordinates
  .github/CHANGELOG.md
  Airports/EGHH/Runway.txt
Labels: airac

#4878 Fixes #4873 - Add Missing Humberside (EGNJ) RNP Approach fixes
  .github/CHANGELOG.md
  Airports/EGNJ/Fixes.txt
Labels: enhancement

#4817 Fixes #4816 - Fix incorrect VOR/NDB Coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
  _data/Tools/resources/airac-dates.pdf
  _data/Tools/src/api.py
  _data/Tools/src/runner.py
  _data/Tools/src/util/airac.py
  _data/Tools/src/util/util.py
  _data/Tools/tests/test_airac.py
  _data/Tools/tests/test_api.py
  _data/Tools/tests/test_util.py
Labels: bug

#4882 Fixes #4838 - Update Brize Norton (EGVN) Holding Points
  .github/CHANGELOG.md
  Airports/EGVN/SMR/Geo.txt
  Airports/EGVN/SMR/Labels.txt
  _data/SMR Files/EGVN/EGVN.kmz
Labels: enhancement
