Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-10, with the labels that each got.

#5021 Fixes #5020 - Update Leuchars (EGQL) SMR
  .github/CHANGELOG.md
  Airports/EGQL/SMR/Geo.txt
  Airports/EGQL/SMR/Labels.txt
  Airports/EGQL/SMR/Regions.txt
  _data/SMR Files/EGQL/EGQL.kmz
Labels: bug

#5027 Fixes #5026 - Changes to Polaris (ENSV) positions and ownership
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
  Ownership/Non-UK/Polaris - Stavanger.txt
Labels: procedure-change

#5025 Fixes #5007 - Update Blackbushe (EGLK) SMR
  .github/CHANGELOG.md
  Airports/EGLK/SMR/Geo.txt
  Airports/EGLK/SMR/Labels.txt
  Airports/EGLK/SMR/Regions.txt
Labels: airac

#5037 Fixes #5032 - Revised SUM VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5040 Fixes #5039 - Remove old 25 kHz frequencies (non-UK)
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#5036 Fixes #5035 - Remove withdrawn data (AIRAC 2021/11 and prior)
  .github/CHANGELOG.md
  Airports/EGBB/Stars.txt
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  Airports/EGFF/Stars.txt
  Airports/EGGD/Stars.txt
  Airports/EGJB/Sids.txt
  Airports/EGJB/Stars.txt
  Airports/EGJJ/Sids.txt
  Airports/EGJJ/Stars.txt
  Navaids/NDB_Old.txt
Labels: enhancement

#5038 Fixes #5033 - Revised Blackbushe (EGLK) runway threshold coordinates
  .github/CHANGELOG.md
  Airports/EGLK/Runway.txt
Labels: airac

#5042 Fixes #5041 - 8.33 Transition (ENR Phase 3) - Event/Spare Frequencies
  Misc/Positions_Area Positions 2 UK Event.txt
  Misc/Positions_Area Positions 3 UK Spares.txt
Labels: procedure-change

#5045 Fixes #5044 - Update Mold Town VRP name
  .github/CHANGELOG.md
  Airports/EGNR/VRPs.txt
Labels: airac

#5029 Fixes #5028 - Fixed Thames agreement display for LC deps to TC NE
  .github/CHANGELOG.md
  Agreements/Airport/LC_TCNE.txt
  Agreements/Airport/LC_THAMES.txt
  Agreements/Airport/THAMES_TCNE.txt
Labels: bug

#5031 Fixes #5030 - Added Benbecula (EGPL) sector ownership
  .github/CHANGELOG.md
  Airports/EGPL/Ownership.txt
  Airports/EGPL/Sector.txt
Labels: enhancement

#5049 Fixes #5047 - Add temporary Cardiff (EGFF) positions for WorldFlight
  .github/CHANGELOG.md
  Airports/EGFF/Positions.txt
Labels: procedure-change

#5051 Fixes #5050 - 8.33 Transition (External) - Belux and French vACCs
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#5055 Fixes #5046 - Removed Prestwick (EGPK) ground position
  .github/CHANGELOG.md
  Airports/EGPK/Ownership.txt
  Airports/EGPK/Positions.txt
  Airports/EGPK/Positions_Mentor.txt
  Airports/EGPK/Sector.txt
Labels: bug

#5053 Fixes #5052 - 8.33 Transition (External) - Copenhagen and Shannon/Dublin
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
  Ownership/Non-UK/Copenhagen.txt
  Ownership/Non-UK/Shannon.txt
Labels: procedure-change

#5062 Fixes #5061 - Removed 'catch all' COPX lines for EH** deps
  .github/CHANGELOG.md
  Agreements/External/AA_14.txt
  Agreements/External/YY-D_13+14.txt
Labels: bug

#5063 Fixes #5052 - 2311 EISN sectorisation part 2
  Misc/Positions_Area Positions 4 External.txt
  Ownership/Non-UK/Shannon.txt
Labels: procedure-change

#5043 Fixes #5014 - Update all Conventional SIDs
  .github/CHANGELOG.md
  Agreements/Airport/CC_Wal.txt
  Agreements/Airport/GP_Wal.txt
  Agreements/Airport/LL_LL.txt
  Agreements/Airport/LL_TCNW.txt
  Agreements/Airport/LL_TCSE.txt
  Agreements/Airport/LL_TCSW.txt
  Airports/EGBB/Sids.txt
  Airports/EGCC/Sids.txt
  Airports/EGFF/Sids.txt
  Airports/EGGD/Sids.txt
  Airports/EGGP/Sids.txt
  Airports/EGGW/Sids.txt
  Airports/EGJB/Sids.txt
  Airports/EGJJ/Sids.txt
  Airports/EGKK/Sids.txt
  Airports/EGLL/Sids.txt
  Airports/EGNM/Sids.txt
  Airports/EGNT/Sids.txt
  Airports/EGNX/Sids.txt
  Airports/EGPF/Sids.txt
  Airports/EGPH/Sids.txt
  Airports/EGSS/Sids.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: enhancement

#5067 Fixes #5064 - Updated Honington (EGXH) basic information
  .github/CHANGELOG.md
  Airports/EGXH/Basic.txt
  Airports/EGXH/Positions.txt
  Airports/EGXH/Runway.txt
Labels: airac

#5068 Fixes #5066 - Added Topcliffe (EGXZ) runway 07/25
  .github/CHANGELOG.md
  Airports/EGXZ/Runway.txt
Labels: airac

#5070 Fixes #4936 - Added basic information for Syerston (EGXY)
  .github/CHANGELOG.md
  Airports/EGXY/Airspace.txt
  Airports/EGXY/Basic.txt
  Airports/EGXY/Positions.txt
Labels: enhancement
