Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-01, with the labels that each got.

#4534 Fixes #4533 - Change Stapleford (EGSG) frequency
  .github/CHANGELOG.md
  Airports/EGSG/Basic.txt
  Doc/UK VATSIM frequencies.txt
Labels: bug

#4540 Fixes #4539 - Added Winstone (WIN) DME
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#4545 Fixes #4538 - Update Manchester (EGCC) 05R threshold coordinate
  .github/CHANGELOG.md
  Airports/EGCC/Runway.txt
Labels: airac

#4552 Fixes #4541 - Updated Tiree (TIR) VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#4551 Fixes #4542 - Changed Brecon (BCN) VOR to DME only
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#4553 Fixes #4544 - Updated Barra (BRR) NDB coordinates
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac

#4547 Fixes #4543 - Move East Midlands (EGNX) K1 Holding Point
  .github/CHANGELOG.md
  Airports/EGNX/SMR/Geo.txt
  Airports/EGNX/SMR/Labels.txt
  _data/SMR Files/EGNX/EGNX.kmz
Labels: airac

#4550 Fixes #4548 - Updated Manchester (EGCC) inbound release COPX
  .github/CHANGELOG.md
  Agreements/Airport/North_CC.txt
  Agreements/Airport/Trent_CC.txt
  Agreements/Airport/Wal_CC.txt
Labels: procedure-change

#4546 Fixes #4536 - Add Sumburgh (EGPB) stand 19
  .github/CHANGELOG.md
  Airports/EGPB/SMR/Geo.txt
  Airports/EGPB/SMR/Labels.txt
  _data/SMR Files/EGPB/EGPB.kmz
Labels: airac

#4549 Fixes #4514 - Update Edinburgh (EGPH) SMR
  .github/CHANGELOG.md
  Airports/EGPH/SMR/Geo.txt
  Airports/EGPH/SMR/Labels.txt
  Airports/EGPH/SMR/Regions.txt
  _data/SMR Files/EGPH/(OLD) Edinburgh - EGPH SMR.kmz
  _data/SMR Files/EGPH/Edinburgh SMR 202204.kmz
  _data/SMR Files/EGPH/Edinburgh SMR.kmz
Labels: enhancement, airac, controller-pack-change

#4535 Fixes #4500 - Update Walney (EGNL) SMR
  .github/CHANGELOG.md
  Airports/EGNL/SMR/Geo.txt
  Airports/EGNL/SMR/Labels.txt
  Airports/EGNL/SMR/Regions.txt
  _data/SMR Files/EGNL/Walney - EGNL SMR.kmz
Labels: airac

#4555 Fixes #4537 - Update Birmingham (EGBB) stands
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Labels.txt
  Airports/EGBB/SMR/Regions.txt
  _data/SMR Files/EGBB/Birmingham (EGBB) SMR 2022-11.kmz
  _data/SMR Files/EGBB/Birmingham SMR 201506.kmz
  _data/SMR Files/EGBB/Birmingham SMR.kmz
  _data/SMR Files/EGBB/Old SMR/Regions.txt
Labels: airac

#4556 Fixes #4481 - Revised LAC West Event Ownership
  .github/CHANGELOG.md
  Airports/EGBJ/Ownership.txt
  Airports/EGFF/Ownership.txt
  Airports/EGGD/Ownership.txt
  Airports/EGHC/Ownership.txt
  Airports/EGHE/Ownership.txt
  Airports/EGHG/Ownership.txt
  Airports/EGHQ/Ownership.txt
  Airports/EGJA/Ownership.txt
  Airports/EGJB/Ownership.txt
  Airports/EGJJ/Ownership.txt
  Airports/EGSY/Ownership.txt
  Airports/EGTE/Ownership.txt
  Misc/Positions_Area Positions 2 UK Event.txt
  Ownership/AC - West/23.txt
  Ownership/AC - West/35.txt
  Ownership/AC - West/36.txt
  Ownership/AC - West/5.txt
  Ownership/AC - West/6.txt
  Ownership/AC - West/8.txt
  Ownership/AC - West/9.txt
  Ownership/Alternate/Airports - LON/AC West.txt
Labels: procedure-change

#4560 Fixes #4557 - Revised Dublin Group COPX (PC IoM -> EIDW ACC)
  .github/CHANGELOG.md
  Agreements/External/IoM_DUBN.txt
  Agreements/External/IoM_SNE.txt
Labels: procedure-change

#4561 Fixes #4554 - Updated various COPX TC SW -> TC NW
  .github/CHANGELOG.md
  Agreements/Internal/TCSW_TCNW.txt
Labels: bug

#4563 Fixes #4559 - Update Wycombe Air Park/Booker (EGTB) SMR
  .github/CHANGELOG.md
  Airports/EGTB/SMR/Labels.txt
  Airports/EGTB/SMR/Regions.txt
  _data/SMR Files/EGTB/Wycombe SMR.kmz
Labels: airac, controller-pack-change

#4564 Fixes #4469 - Update Swansea (EGFH) SMR
  .github/CHANGELOG.md
  Airports/EGFH/SMR/Geo.txt
  Airports/EGFH/SMR/Labels.txt
  Airports/EGFH/SMR/Regions.txt
  _data/SMR Files/EGFH/Swansea SMR.kmz
Labels: airac

#4562 Fixes #4558 - Amended Reykjavik (BIRD) sectors and COPX
  .github/CHANGELOG.md
  Agreements/External/Heb_RKE.txt
  Agreements/External/Heb_RKS.txt
  Agreements/External/Mor_RKE.txt
  Ownership/Non-UK/Reykjavik.txt
  Sectors/Lines - External FIR.txt
  Sectors/Lines - PACC.txt
Labels: procedure-change

#4569 Fixes #4567 - TACAN Coordinate Updates (#4567)
  .github/CHANGELOG.md
  Airways/Other/TB2.txt
  Airways/Other/TB7.txt
  Navaids/FIXES_TACAN-Routes.txt
  Navaids/VOR_Non-UK.txt
  Navaids/VOR_UK.txt
Labels: airac

#4573 Fixes #4570 - Corrected Duxford (EGSU) hold and runway labels
  .github/CHANGELOG.md
  Airports/EGSU/SMR/Labels.txt
Labels: bug

#4568 Fixes #4415 - Updated general contributing guide
  .github/Contributing.md
Labels: docs

#4574 Fixes #4571 - Kinloss (EGQK) Closed
  .github/CHANGELOG.md
  UK.rwy
  _data/Closed Airfields/EGQK/Basic.txt
  _data/Closed Airfields/EGQK/Ground Map/Geo.txt
  _data/Closed Airfields/EGQK/Ownership.txt
  _data/Closed Airfields/EGQK/Positions.txt
  _data/Closed Airfields/EGQK/Runway.txt
  _data/Closed Airfields/EGQK/Sector.txt
Labels: bug, airac

#4591 Fixes #4590 - Define Duxford (EGSU) ATZ
  .github/CHANGELOG.md
  Airports/EGSU/Airspace.txt
Labels: enhancement
