Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-08, with the labels that each got.

#4891 Fixes #4884 - Add Prestwick (EGPK) missing holding points
  .github/CHANGELOG.md
  Airports/EGPK/SMR/Geo.txt
  Airports/EGPK/SMR/Labels.txt
Labels: enhancement

#4765 Fixes VATSIM-UK/uk-controller-pack/issues/215
  .github/workflows/compile.yml
Labels: enhancement

#4824 Fixes #4821 - Update Fairford (EGVA) Fixes and STARs
  .github/CHANGELOG.md
  Airports/EGVA/Fixes.txt
  Airports/EGVA/Stars.txt
Labels: enhancement

#4869 Fixes #4868 - Correct Edinburgh (EGPH) Tower automatic arrival airport selection
  .github/CHANGELOG.md
  Airports/EGPH/Ownership.txt
Labels: bug

#4876 Fixes #4874 - Update Non-UK VORs and fixes
  .github/CHANGELOG.md
  Navaids/FIXES_Non-UK.txt
  Navaids/Fixes_Non-UK/FIXES_Belgium.txt
  Navaids/Fixes_Non-UK/FIXES_France.txt
  Navaids/Fixes_Non-UK/FIXES_Ireland.txt
  Navaids/Fixes_Non-UK/FIXES_Netherlands.txt
  Navaids/Fixes_Non-UK/FIXES_Norway.txt
  Navaids/Fixes_Non-UK/FIXES_Other.txt
  Navaids/VOR_Non-UK.txt
  Navaids/VOR_UK.txt
  compiler.config.json
Labels: bug, enhancement

#4857 Fixes #4854 - Update Marham (EGYM) runway designator
  .github/CHANGELOG.md
  Airports/EGYM/Runway.txt
  UK.rwy
Labels: airac

#4796 Fixes #4795 - Remove redundant air network fixes
  .github/CHANGELOG.md
  Airports/EGBB/Fixes.txt
  Airports/EGSS/Fixes.txt
Labels: bug

#4896 Fixes #4895 - Remove EGPA and EGPL AFIS positions
  .github/CHANGELOG.md
  Airports/EGPA/Positions.txt
  Airports/EGPL/Positions.txt
Labels: procedure-change

#4889 Fixes #4875 - Add and Update Military Runway Definitions
  .github/CHANGELOG.md
  Airports/EGDI/Runway.txt
  Airports/EGDO/Runway.txt
  Airports/EGDY/Runway.txt
  Airports/EGKN/Basic.txt
  Airports/EGKT/Runway.txt
  Airports/EGOV/Runway.txt
  Airports/EGOW/Runway.txt
  Airports/EGQL/Runway.txt
  Airports/EGQS/Runway.txt
  Airports/EGUL/Runway.txt
  Airports/EGUW/Runway.txt
  Airports/EGVL/Basic.txt
  Airports/EGVP/Runway.txt
  Airports/EGWN/Basic.txt
  Airports/EGXE/Runway.txt
  Airports/EGXW/Runway.txt
  Airports/EGYD/Runway.txt
  UK.rwy
Labels: bug

#4861 Fixes #4839 - Add Valley (EGOV) Holding point labels
  .github/CHANGELOG.md
  Airports/EGOV/SMR/Labels.txt
Labels: enhancement

#4860 Fixes #4842 - Add Northolt (EGWU) stands
  .github/CHANGELOG.md
  Airports/EGWU/SMR/Geo.txt
  Airports/EGWU/SMR/Labels.txt
  _data/SMR Files/EGWU/EGWU.kmz
Labels: enhancement

#4898 Fixes #4897 - Update all VRPs
  .github/CHANGELOG.md
  Airports/EGCB/VRPs.txt
  Airports/EGCC/VRPs.txt
  Airports/EGCM/VRPs.txt
  Airports/EGCN/VRPs.txt
  Airports/EGGP/VRPs.txt
  Airports/EGHC/VRPs.txt
  Airports/EGHE/VRPs.txt
  Airports/EGHH/VRPs.txt
  Airports/EGHI/VRPs.txt
  Airports/EGJJ/VRPs.txt
  Airports/EGKK/VRPs.txt
  Airports/EGKR/VRPs.txt
  Airports/EGLC/VRPs.txt
  Airports/EGLF/VRPs.txt
  Airports/EGNE/VRPs.txt
  Airports/EGNH/VRPs.txt
  Airports/EGNJ/VRPs.txt
  Airports/EGNM/VRPs.txt
  Airports/EGNR/VRPs.txt
  Airports/EGNT/VRPs.txt
  Airports/EGNV/VRPs.txt
  Airports/EGPB/VRPs.txt
  Airports/EGPD/VRPs.txt
  Airports/EGPE/VRPs.txt
  Airports/EGPH/VRPs.txt
  Airports/EGPI/VRPs.txt
  Airports/EGPK/VRPs.txt
  Airports/EGSH/VRPs.txt
  Airports/EGSS/VRPs.txt
  Airports/EGVN/VRPs.txt
Labels: enhancement

#4784 Fixes #4783 - Add ALT procedures for REXAM/NANTI
  .github/CHANGELOG.md
  Airports/EGGP/Sids.txt
Labels: procedure-change

#4905 Fixes #4904 - Update Birmingham (EGBB) SMR
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Geo.txt
  Airports/EGBB/SMR/Labels.txt
  Airports/EGBB/SMR/Regions.txt
  Airports/EGKR/SMR/Regions.txt
  Airports/EGNT/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGBB/EGBB.kmz
  _data/SMR Files/EGBB/Old SMR/EGBB.kmz
Labels: enhancement

#4900 Fixes #4899 - Add Derby (EGBD) SMR
  .github/CHANGELOG.md
  Airports/EGBD/SMR/Geo.txt
  Airports/EGBD/SMR/Labels.txt
  Airports/EGBD/SMR/Regions.txt
  _data/SMR Files/EGBD/EGBD.kmz
Labels: enhancement

#4903 Fixes #4902 - Remove Manchester (EGCC) disused stands
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
Labels: enhancement

#4910 Fixes #4909 - Updated EuroCenter vACC callsign (prefixes)
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#4920 Fixes #4919 - Update compiler version
  .github/workflows/compile.yml
  .github/workflows/validate.yml
Labels: compiler-config-change

#4915 Fixes #4913 - 8.33 Trial - Changes to external frequencies
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#4911 Fixes #4907 - Remove Gatwick (EGKK) stand 145 L/R labels
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Labels.txt
Labels: bug

#4944 Fixes #4937 - Rename Waddington (EGXW) holding points
  .github/CHANGELOG.md
  Airports/EGXW/SMR/Labels.txt
Labels: bug

#4941 Fixes #4931 - Update Kirknewton (EGKT) Runway coordinates
  .github/CHANGELOG.md
  Airports/EGKT/Runway.txt
Labels: airac

#4946 Fixes #4940 - Update Dover (DVR) VOR/DME coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#4945 Fixes #4942 - Added EG D713 (Fast Jet Area South) & EG D901 (Fast Jet Area North)
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D713.txt
  ARTCC/Danger Areas/EG D901.txt
Labels: airac

#4921 Fixes #4917 - Define Jersey Control regions & colours
  .github/CHANGELOG.md
  Colours.txt
  Misc/Regions_Jersey.txt
Labels: enhancement, controller-pack-change
