Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-12, with the labels that each got.

#5121 Fixes #5120 - Add Hereford (EGVH) Airport
  .github/CHANGELOG.md
  Airports/EGVH/Basic.txt
  Airports/EGVH/Fixes.txt
  Airports/EGVH/Runway.txt
Labels: enhancement

#5118 Fixes #5116 - Correct Waddington (EGXW) ATZ
  .github/CHANGELOG.md
  Airports/EGXW/Airspace.txt
Labels: bug

#5126 Fixes #5123 - Remove Heathrow (EGLL) MAY SIDs
  .github/CHANGELOG.md
  Airports/EGLL/Fixes.txt
  Airports/EGLL/Sids.txt
Labels: airac

#5127 Fixes #5124 - Remove Manchester (EGCC) MONTY SIDs
  .github/CHANGELOG.md
  Airports/EGCC/Fixes.txt
  Airports/EGCC/Sids.txt
  Airports/EGGP/Fixes.txt
Labels: airac

#5135 Fixes #5130 - Reinstate Upavon (EGDJ)
  .github/CHANGELOG.md
  Airports/EGDJ/Basic.txt
  Airports/EGDJ/Positions.txt
Labels: airac

#5125 Fixes #5122 - Add GPL v3 license
  Comments.txt
  README.md
Labels: docs

#5133 Fixes #5132 - Align aerodrome naming with AIP
  .github/CHANGELOG.md
  Airports/EGAC/Basic.txt
  Airports/EGBO/Basic.txt
  Airports/EGBW/Basic.txt
  Airports/EGCJ/Basic.txt
  Airports/EGFA/Basic.txt
  Airports/EGKK/Basic.txt
  Airports/EGNE/Basic.txt
  Airports/EGNV/Basic.txt
  Airports/EGPD/Basic.txt
Labels: bug

#5136 Fixes #5128 - Cranfield (EGTC) New Apron
  .github/CHANGELOG.md
  Airports/EGTC/SMR/Geo.txt
  Airports/EGTC/SMR/Labels.txt
  Airports/EGTC/SMR/Regions.txt
  _data/SMR Files/EGTC/EGTC.kmz
Labels: airac

#5138 Fixes #5137 - Reposition Birmingham (EGBB) Hold Y1
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Geo.txt
  _data/SMR Files/EGBB/EGBB.kmz
Labels: airac

#5140 Fixes #5139 - Implemented TC Midlands as a permanent position
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK Permanent.txt
  Misc/Positions_Area Positions 2 UK Event.txt
Labels: procedure-change

#5134 Fixes #5129 - Update Farnborough (EGLF) SMR
  .github/CHANGELOG.md
  Airports/EGLF/SMR/Geo.txt
  Airports/EGLF/SMR/Labels.txt
  Airports/EGLF/SMR/Regions.txt
  _data/SMR Files/EGLF/EGLF.kmz
Labels: enhancement, airac

#5148 Fixes #5146 - Remove East Midlands (EGNX) BPK2P SID
  .github/CHANGELOG.md
  Airports/EGNX/Fixes.txt
  Airports/EGNX/Sids.txt
Labels: airac

#5147 Fixes #5145 - Change East Midlands Radar (EGNX_APP) frequency
  .github/CHANGELOG.md
  Airports/EGNX/Positions.txt
Labels: procedure-change

#5150 Fixes #5149 - Amend SS FIN to TC NW standing agreement (COPX)
  .github/CHANGELOG.md
  Agreements/Airport/SS_TCNW.txt
Labels: procedure-change

#5144 Fixes #5143 - Update Moray Firth TMZ Radar Hole Lateral Limits
  .github/CHANGELOG.md
  Misc/Radar Holes.txt
Labels: airac

#5154 Fixes #5153 - Create Islay (EGPI) SMR
  .github/CHANGELOG.md
  Airports/EGPI/SMR/Geo.txt
  Airports/EGPI/SMR/Labels.txt
  Airports/EGPI/SMR/Regions.txt
  _data/SMR Files/EGPI/EGPI.svg
Labels: enhancement

#5142 Fixes #5141 - Amended PC Southeast sector ownership order
  .github/CHANGELOG.md
  Airports/EGCC/Ownership.txt
  Ownership/Alternate/Airports - MPC/SouthEast.txt
  Ownership/TC - MPC/SE Stafa.txt
  Ownership/TC - MPC/SE Trent.txt
Labels: procedure-change

#5152 Fixes #5151 - Add Oxford (EGTK) outbound agreement from TC WELIN to CLN (S12)
  .github/CHANGELOG.md
  Agreements/Internal/TCWEL_12.txt
Labels: procedure-change
