Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-02, with the labels that each got.

#4594 Fixes #4585 - Added EGTT West FRA Depiction
  .github/CHANGELOG.md
  Misc/STAR_West_FRA.txt
Labels: airac

#4580 Fixes #4579 - Update FIXES_UK.txt to match 2303 ENR 4.4
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: airac

#4603 Fixes #4600 - Remove all Doncaster Sheffield (EGCN) standing agreements
  .github/CHANGELOG.md
  Agreements/External/SNE_IoM.txt
  Agreements/Internal/10_East.txt
  Agreements/Internal/28_Trent.txt
  Agreements/Internal/34_28.txt
  Agreements/Internal/5_Wal.txt
  Agreements/Internal/Ant_IoM.txt
  Agreements/Internal/Dcs_Gal.txt
  Agreements/Internal/East_10.txt
  Agreements/Internal/East_Mon.txt
  Agreements/Internal/Gal_North.txt
  Agreements/Internal/IoM_Wal.txt
  Agreements/Internal/Mon_East.txt
  Agreements/Internal/Rat_IoM.txt
  Agreements/Internal/S29_27.txt
  Agreements/Internal/S29_5.txt
  Agreements/Internal/S29_Dcs.txt
  Agreements/Internal/Trent_North.txt
  Agreements/Internal/Tyne_Mon.txt
  Agreements/Internal/Wal_North.txt
Labels: procedure-change

#4582 Fixes #4578 - Update all SIDs/STAR changes for AIRAC 2303
  .github/CHANGELOG.md
  Airports/EGCC/Stars.txt
  Airports/EGFF/Sids.txt
  Airports/EGFF/Stars.txt
  Airports/EGGD/Sids.txt
  Airports/EGGD/Stars.txt
  Airports/EGGP/Stars.txt
  Airports/EGGW/Sids.txt
  Airports/EGGW/Stars.txt
  Airports/EGKK/Stars.txt
  Airports/EGLC/Stars.txt
  Airports/EGLL/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
  Navaids/FIXES_Old.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: airac

#4589 Fixes #4584 - AIRAC 2303 Upper Airspace Changes
  .github/CHANGELOG.md
  ARTCC/High/Banba CTA.txt
  ARTCC/High/Berry Head CTA.txt
  ARTCC/High/Cotswold CTA.txt
  ARTCC/High/Daventry CTA.txt
  ARTCC/High/EGTT London FIR.txt
  ARTCC/High/Midlands CTA.txt
  ARTCC/High/NITON CTA.txt
  ARTCC/High/PEPZE CTA.txt
  ARTCC/High/Southern CTA.txt
  ARTCC/High/Strumble CTA.txt
  ARTCC/High/West CTA.txt
  Airports/EGFF/Airspace_Bases.txt
  Airports/EGGD/Airspace_Bases.txt
  Misc/Freetext_Airspace Bases.txt
  Misc/Regions_Uncontrolled airspace (Grey).txt
  Misc/Regions_Uncontrolled airspace.txt
Labels: airac

#4613 Fixes #4612 - Added Humberside (EGNJ) ATZ
  .github/CHANGELOG.md
  Airports/EGNJ/Airspace.txt
Labels: enhancement

#4615 Fixes #4614 - Added Gamston (EGNE) ATZ
  .github/CHANGELOG.md
  Airports/EGNE/Airspace.txt
Labels: enhancement
