Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-09, with the labels that each got.

#4949 Fixes #4928 - Add Portland Heliport (EGDP) Data
  .github/CHANGELOG.md
  Airports/EGDP/Basic.txt
  Airports/EGDP/Positions.txt
Labels: airac

#4950 Fixes #4840 - Add Yeovilton (EGDY) stand numbers
  .github/CHANGELOG.md
  Airports/EGDY/SMR/Labels.txt
  _data/SMR Files/EGDY/EGDY.kmz
Labels: enhancement

#4943 Fixes #4924 #4925 #4926 #4927 - 8.33 Trial (AD Phase 1) - Transition EGLL/PH/SS/GP Frequencies
  .github/CHANGELOG.md
  Airports/EGGP/Basic.txt
  Airports/EGGP/Positions.txt
  Airports/EGLL/Basic.txt
  Airports/EGLL/Positions.txt
  Airports/EGPH/Basic.txt
  Airports/EGPH/Positions.txt
  Airports/EGSS/Basic.txt
  Airports/EGSS/Positions.txt
Labels: procedure-change

#4935 Fixes #4930 - Remove Bristol (EGGD) stands 31R and 33L
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
  _data/SMR Files/EGGD/EGGD.kmz
Labels: airac

#4951 Fixes #4939 - Add Leeds East (EGCM) SMR
  .github/CHANGELOG.md
  Airports/EGCM/SMR/Geo.txt
  Airports/EGCM/SMR/Labels.txt
  Airports/EGCM/SMR/Regions.txt
  _data/SMR Files/EGCM/EGCM.kmz
Labels: enhancement

#4962 Fixes #4961 - Update Wattisham (EGUW) Tower Frequency
  .github/CHANGELOG.md
  Airports/EGUW/Positions.txt
Labels: airac

#4918 Fixes #4867 - Fixed Farnborough (EGLF) Inbound Agreements via CPT
  .github/CHANGELOG.md
  Agreements/Internal/TCNW_TCSW.txt
  compiler.config.json
Labels: bug

#4963 Fixes #4958 - Add Biggin Hill (EGKB) new taxiway
  .github/CHANGELOG.md
  Airports/EGKB/SMR/Geo.txt
  Airports/EGKB/SMR/Labels.txt
  Airports/EGKB/SMR/Regions.txt
  _data/SMR Files/EGKB/EGKB.kmz
Labels: airac

#4952 Fixes #4901 - Create Haverfordwest (EGFE) SMR
  .github/CHANGELOG.md
  Airports/EGFE/SMR/Geo.txt
  Airports/EGFE/SMR/Labels.txt
  Airports/EGFE/SMR/Regions.txt
  _data/SMR Files/EGFE/EGFE.kmz
Labels: enhancement

#4881 Fixes #4845 - Update Belfast Aldergrove (EGAA) SMR
  .github/CHANGELOG.md
  Airports/EGAA/SMR/Geo.txt
  Airports/EGAA/SMR/Labels.txt
  _data/SMR Files/EGAA/EGAA.kmz
Labels: airac

#4933 Fixes #4929 - Add Fairoaks (EGTF) disused taxiway
  .github/CHANGELOG.md
  Airports/EGTF/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGTF/EGTF.kmz
Labels: airac

#4966 Fixes #4934 - Added Middle Wallop (EGVP) FATO and RNP SIDs
  .github/CHANGELOG.md
  Airports/EGVP/Fixes.txt
  Airports/EGVP/Runway.txt
  Airports/EGVP/Sids.txt
Labels: enhancement

#4969 Fixes #4968 - Correct 8.33kHz trial ATIS frequencies
  .github/CHANGELOG.md
  Airports/EGGP/Positions.txt
  Airports/EGLL/Positions.txt
  Airports/EGPH/Positions.txt
  Airports/EGSS/Positions.txt
Labels: bug

#4986 Fixes #4984 - EGAA inbounds now via BELZU
  .github/CHANGELOG.md
  Agreements/Airport/Ant_AA.txt
Labels: bug

#4979 Fixes #4970 - Remove double fix definitions
  .github/CHANGELOG.md
  Navaids/Fixes_Non-UK/FIXES_France.txt
Labels: bug

#4976 Fixes #4975 - Define Blackpool (EGNH) ATZ
  .github/CHANGELOG.md
  Airports/EGNH/Airspace.txt
Labels: enhancement

#4999 Fixes #4989 - Updated BEL VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5000 Fixes #4990 - Updated BHD VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5006 Fixes #4996 - Updated TRN VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5001 Fixes #4991 - Updated OTR VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5002 Fixes #4992 - Updated POL VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5004 Fixes #4994 - Updated STU VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5005 Fixes #4995 - Updated TLA VOR coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#4998 Fixes #4988 - Prestwick (EGPK) VRPs renamed
  .github/CHANGELOG.md
  Airports/EGPK/VRPs.txt
Labels: airac

#5010 Fixes #4987 - Update Oxford (EGTK) SMR Hold Points
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Geo.txt
  Airports/EGTK/SMR/Labels.txt
  _data/SMR Files/EGTK/EGTK.kmz
Labels: airac

#5009 Fixes #5008 - Transition all UK enroute non-event frequencies to 8.33kHz
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 1 UK Permanent.txt
  Misc/Positions_Area Positions 2 UK Event.txt
Labels: procedure-change

#5013 Fixes #5012 - Transition EGKK frequencies to 8.33 kHz
  .github/CHANGELOG.md
  Airports/EGKK/Positions.txt
Labels: procedure-change, controller-pack-change

#4974 Fixes #4932 - Add Brize Norton (EGVN) Stand Numbers
  .github/CHANGELOG.md
  Airports/EGVN/SMR/Labels.txt
  _data/SMR Files/EGVN/EGVN.kmz
Labels: enhancement

#4978 Fixes #4977 - Automatically use latest compiler version for workflow
  .github/workflows/compile.yml
  .github/workflows/validate.yml
Labels: enhancement

#5017 Fixes #5016 - Change callsign for Hawarden Director to Hawarden Radar
  .github/CHANGELOG.md
  Airports/EGNR/Positions.txt
Labels: airac
