Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2023-11, with the labels that each got.

#5076 Fixes #5075 - Removed ERROR lines for transitioned 8.33 ENR positions
  Misc/Positions_Area Positions 1 UK Permanent.txt
Labels: enhancement

#5059 Fixes #5058 - Added DVR -> LFEE COPX for EGKK/GW outbounds RINTI
  .github/CHANGELOG.md
  Agreements/External/15_EE-N.txt
  Agreements/External/2_EE-N.txt
  Ownership/Non-UK/Paris.txt
Labels: procedure-change

#5078 Fixes #5024 - Add Southampton (EGHI) runway extension
  .github/CHANGELOG.md
  Airports/EGHI/SMR/Regions.txt
Labels: airac

#5079 Fixes #5077 - Fixed Brecon (S5) ownership in ELSOF/DIDZA/Brize area
  .github/CHANGELOG.md
  Ownership/AC - Central/27.txt
  Ownership/AC - South/25.txt
  Ownership/AC - West/5.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
Labels: bug

#4972 Fixes #4967 - Update Heathrow (EGLL) GND sector splits
  .github/CHANGELOG.md
  Airports/EGLL/Ownership.txt
  Airports/EGLL/Sector.txt
Labels: bug, enhancement

#5091 Fixes #5087 - Fix Henton (HEN) NDB coordinates
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: bug

#5090 Fixes #5084 - Remove Gatwick (EGKK) HARDY 5M/5V SIDs
  .github/CHANGELOG.md
  Airports/EGKK/Sids.txt
Labels: airac

#5092 Fixes #5086 - Rename enroute fixes
  .github/CHANGELOG.md
  Agreements/External/9_SNB.txt
  Airways/RNAV/Lower/N18.txt
  Airways/RNAV/Lower/N24.txt
  Airways/RNAV/Lower/N83.txt
  Airways/RNAV/Lower/P2.txt
  Navaids/FIXES_UK.txt
Labels: airac

#5101 Fixes #5098 - Remove fixes withdrawn 2021/12
  .github/CHANGELOG.md
  Navaids/FIXES_Old.txt
Labels: enhancement

#5100 Fixes #5097 - Remove withdrawn 25 kHz external position definitions
  .github/CHANGELOG.md
  Misc/Positions_Area Positions 4 External.txt
Labels: procedure-change

#5104 Fixes #5103 - Correct Aldergrove (EGAA) TWR Arrival airport ownership
  .github/CHANGELOG.md
  Airports/EGAA/Ownership.txt
Labels: bug

#5094 Fixes #5065 - Add stands to Northolt (EGWU) SMR
  .github/CHANGELOG.md
  Airports/EGWU/SMR/Geo.txt
  Airports/EGWU/SMR/Labels.txt
  _data/SMR Files/EGWU/EGWU.kmz
Labels: airac

#5074 Fixes #5073 - Add Heathrow (EGLL) Transitions
  .github/CHANGELOG.md
  Agreements/Airport/LL_LL.txt
  Airports/EGLL/Fixes.txt
  Airports/EGLL/Stars.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: enhancement

#5102 Fixes #5095 - Update Luton (EGGW) SMR
  .github/CHANGELOG.md
  Airports/EGGW/SMR/Geo.txt
  Airports/EGGW/SMR/Labels.txt
  Airports/EGGW/SMR/Regions.txt
  _data/SMR Files/EGGW/EGGW.kmz
Labels: enhancement, airac

#5106 Fixes #5105 - Fix Highlands and Islands ownership
  .github/CHANGELOG.md
  Airports/EGPA/Ownership.txt
  Airports/EGPA/Positions_Mentor.txt
  Airports/EGPA/Sector.txt
  Airports/EGPC/Ownership.txt
  Airports/EGPC/Positions_Mentor.txt
  Airports/EGPC/Sector.txt
  Airports/EGPL/Ownership.txt
  Airports/EGPL/Sector.txt
  Airports/EGPN/Ownership.txt
  Airports/EGPN/Positions_Mentor.txt
  Airports/EGPN/Sector.txt
  Airports/EGPO/Ownership.txt
  Airports/EGPO/Sector.txt
Labels: bug, enhancement

#5108 Fixes #5107 - Refactor SID and STAR fixes
  .github/CHANGELOG.md
  Agreements/Airport/LL_TCSW.txt
  Airports/EGBB/Fixes.txt
  Airports/EGCC/Fixes.txt
  Airports/EGCN/Fixes.txt
  Airports/EGFF/Fixes.txt
  Airports/EGGD/Fixes.txt
  Airports/EGGP/Fixes.txt
  Airports/EGGW/Fixes.txt
  Airports/EGJJ/Fixes.txt
  Airports/EGKB/Fixes.txt
  Airports/EGKK/Fixes.txt
  Airports/EGLC/Fixes.txt
  Airports/EGLL/Fixes.txt
  Airports/EGNM/Fixes.txt
  Airports/EGNX/Fixes.txt
  Airports/EGPF/Fixes.txt
  Airports/EGPH/Fixes.txt
  Airports/EGSS/Fixes.txt
  Airports/EGVN/Fixes.txt
  Airports/EGVN/Sids.txt
  Airports/EGWU/Fixes.txt
  Navaids/FIXES_SIDS-STARS.txt
Labels: enhancement

#5089 Fixes #5088 - Add New Waddington danger areas
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D324.txt
Labels: airac

#5080 Fixes #5057 - Remove COPX lines for airport towers to APP/CTR
  .github/CHANGELOG.md
  Agreements/Airport/CC_North.txt
  Agreements/Airport/CC_Stafa.txt
  Agreements/Airport/CC_Wal.txt
  Agreements/Airport/GP_GP.txt
  Agreements/Airport/GP_Wal.txt
  Agreements/Airport/LL_LL.txt
  Agreements/Airport/LL_TCNE.txt
  Agreements/Airport/LL_TCNW.txt
  Agreements/Airport/LL_TCSE.txt
  Agreements/Airport/LL_TCSW.txt
  Agreements/Airport/NX_NX.txt
Labels: bug

#5112 Fixes #5111 - Correct Stornoway (EGPO) ATZ Size
  .github/CHANGELOG.md
  Airports/EGPO/Airspace.txt
Labels: bug

#5114 Fixes #5113 - Add Halton (EGWN) AGCS Frequency
  .github/CHANGELOG.md
  Airports/EGWN/Positions.txt
Labels: enhancement
