Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-07, with the labels that each got.

#5342 Fixes #5332 - Update Brize Norton (EGVN) Frequencies
  .github/CHANGELOG.md
  Airports/EGVN/Positions.txt
Labels: on-hold, airac, controller-pack-change

#5339 Fixes #5333 - Update Guernsey (EGJB) SMR Holds
  .github/CHANGELOG.md
  Airports/EGJB/SMR/Geo.txt
  Airports/EGJB/SMR/Labels.txt
  _data/SMR Files/EGJB/EGJB.kmz
Labels: airac

#5357 Fixes #5334 - Update Humberside (EGNJ) SMR incl. move D1 Hold
  .github/CHANGELOG.md
  Airports/EGNJ/SMR/Geo.txt
  Airports/EGNJ/SMR/Labels.txt
  Airports/EGNJ/SMR/Regions.txt
  _data/SMR Files/EGNJ/EGNJ.kmz
Labels: enhancement, airac

#5355 Fixes #5345 - Add / Rename Oxford (EGTK) Heli Holds
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Geo.txt
  Airports/EGTK/SMR/Labels.txt
  Colours.txt
Labels: airac

#5353 Fixes #5344 - Update East Midlands (EGNX) Stand locations
  .github/CHANGELOG.md
  Airports/EGNX/SMR/Geo.txt
  Airports/EGNX/SMR/Labels.txt
  _data/SMR Files/EGNX/EGNX.kmz
Labels: airac

#5352 Fixes #5335 - Update Land's End (EGHC) holds
  .github/CHANGELOG.md
  Airports/EGHC/SMR/Geo.txt
  Airports/EGHC/SMR/Labels.txt
Labels: airac

#5340 Fixes #5338 - Correct Bug with NorthWest Region of GB Landmass
  .github/CHANGELOG.md
  Misc Regions/GB Landmass Medium Detail.txt
Labels: bug

#5343 Fixes #5325 - Add the new run up areas to the Redhill (EGKR) SMR
  .github/CHANGELOG.md
  Airports/EGKR/SMR/Labels.txt
  Airports/EGKR/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGKR/EGKR.kmz
Labels: airac

#5351 Fixes #5348 - Update Barkston Heath (EGYE) runway headings
  .github/CHANGELOG.md
  Airports/EGYE/Runway.txt
Labels: airac

#5366 Fixes #5362 - Update Cambridge (EGSC) Radar Frequencies
  .github/CHANGELOG.md
  Airports/EGSC/Positions.txt
Labels: airac, controller-pack-change

#5368 Fixes #5367 - Change Ronaldsway (EGNS) Radar frequencies
  .github/CHANGELOG.md
  Airports/EGNS/Positions.txt
Labels: procedure-change, controller-pack-change

#5363 Fixes #5318 - Add additional Glasgow Local Area lines
  .github/CHANGELOG.md
  Airports/EGPF/RMA.txt
  Airports/EGPF/Sector.txt
Labels: enhancement

#5370 Fixes #5365 - Remove Edinburgh (EGPH) Stands 2A/3A
  .github/CHANGELOG.md
  Airports/EGPH/SMR/Geo.txt
  _data/SMR Files/EGPH/EGPH.kmz
Labels: airac

#5354 Fixes #5347 - Remove Southend (EGMC) Hold F2
  .github/CHANGELOG.md
  Airports/EGMC/SMR/Geo.txt
  Airports/EGMC/SMR/Labels.txt
  _data/SMR Files/EGMC/EGMC.kmz
Labels: airac

#5356 Fixes #5346 - Add Leeds Bradford (EGNM) tug release points
  .github/CHANGELOG.md
  Airports/EGNM/SMR/Geo.txt
  Airports/EGNM/SMR/Labels.txt
  Airports/EGNM/SMR/Regions.txt
  _data/SMR Files/EGNM/EGNM.kmz
Labels: airac

#5372 Fixes #5371 - Correct Danger Area EGD113B name
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EGD113.txt
Labels: bug

#5395 Fixes #5390 - Update Luton (EGGW) stands 23/L/R
  .github/CHANGELOG.md
  Airports/EGGW/SMR/Labels.txt
Labels: airac, controller-pack-change

#5392 Fixes #5379 - Remove Hold Label Position lines from Newcastle (EGNT) SMR
  .github/CHANGELOG.md
  Airports/EGNT/SMR/Geo.txt
Labels: bug
