Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-01, with the labels that each got.

#5169 Fixes #5159 - Update Kirkwall (EGPA) ATIS frequency
  .github/CHANGELOG.md
  Airports/EGPA/Positions.txt
  Doc/UK VATSIM frequencies.txt
Labels: airac

#5168 Fixes #5158 - Update Alderney (ALD) NDB coordinates
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac

#5171 Fixes #5165 - Update Honington (EGXH) ARP and runway coordinates
  .github/CHANGELOG.md
  Airports/EGXH/Basic.txt
  Airports/EGXH/Positions.txt
  Airports/EGXH/Runway.txt
Labels: airac

#5172 Fixes #5156 - Remove Bristol (EGGD) Stand 4
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
  _data/SMR Files/EGGD/EGGD.kmz
Labels: airac

#5173 Fixes #5163 - Remove Southampton (EGHI) Stand 1
  .github/CHANGELOG.md
  Airports/EGHI/SMR/Geo.txt
  Airports/EGHI/SMR/Labels.txt
  Airports/EGHI/SMR/Regions.txt
Labels: airac

#5178 Fixes #5176 - Correct callsigns for Edinburgh (EGPH) and Glasgow (EGPF) "Director" positions
  .github/CHANGELOG.md
  Airports/EGPF/Positions.txt
  Airports/EGPF/Positions_Mentor.txt
  Airports/EGPH/Positions.txt
  Airports/EGPH/Positions_Mentor.txt
Labels: bug

#5170 Fixes #5164 - Update Brize Norton (EGVN) holding point names
  .github/CHANGELOG.md
  Airports/EGVN/SMR/Geo.txt
  Airports/EGVN/SMR/Labels.txt
  _data/SMR Files/EGVN/EGVN.kmz
Labels: airac

#5155 Fixes #5115 - Update contribution guide documentation
  .github/Contributing.md
  .github/First time contributors' guide.md
Labels: docs

#5166 Fixes #5157 - Update Stansted (EGSS) SMR
  .github/CHANGELOG.md
  Airports/EGSS/SMR/Geo.txt
  Airports/EGSS/SMR/Labels.txt
  Airports/EGSS/SMR/Regions.txt
  _data/SMR Files/EGSS/EGSS.kmz
Labels: airac

#5188 Fixes #5187 - Amend S13 -> S26 agreements to avoid LUS
  .github/CHANGELOG.md
  Agreements/Internal/13_26.txt
Labels: procedure-change

#5180 Fixes #5177 - Add Scottish Tay Event Split
  .github/CHANGELOG.md
  Agreements/Airport/Mon_PE.txt
  Agreements/Airport/Mon_PF.txt
  Agreements/Airport/PD_Tay.txt
  Agreements/Airport/PE_Mon.txt
  Agreements/Airport/PE_WC-Tay.txt
  Agreements/Airport/Tay_PD.txt
  Agreements/Airport/Tay_PF.txt
  Agreements/Airport/Tay_PH.txt
  Agreements/Airport/WC-Tay_PE.txt
  Agreements/Airport/WC-Tay_PF.txt
  Agreements/Internal/Dcs_Mon.txt
  Agreements/Internal/Dcs_Tay.txt
  Agreements/Internal/Dcs_WC-Tay.txt
  Agreements/Internal/Heb_Tay.txt
  Agreements/Internal/Mon_Tay.txt
  Agreements/Internal/Mor_Tay.txt
  Agreements/Internal/Tay_Dcs.txt
  Agreements/Internal/Tay_East.txt
  Agreements/Internal/Tay_Mon.txt
  Agreements/Internal/Tyne_Tay.txt
  Airports/EGPD/Ownership.txt
  Airports/EGPN/Ownership.txt
  Misc/Positions_Area Positions 2 UK Event.txt
  Ownership/ScAC - East/Montrose.txt
  Ownership/ScAC - East/Tay.txt
  Ownership/ScAC - West/Westcoast.txt
  Sectors/Lines - PACC.txt
Labels: procedure-change

#5179 Fixes #5161 - Update Teeside International (EGNV) Draken Stands
  .github/CHANGELOG.md
  Airports/EGNV/SMR/Geo.txt
  Airports/EGNV/SMR/Labels.txt
  Airports/EGNV/SMR/Regions.txt
  _data/SMR Files/EGNV/EGNV.kmz
Labels: airac

#5189 Fixes #5184 - Update Coventry (EGBE) SMR
  .github/CHANGELOG.md
  Airports/EGBE/SMR/Geo.txt
  Airports/EGBE/SMR/Regions.txt
  _data/SMR Files/EGBE/EGBE.kmz
Labels: airac

#5167 Fixes #5162 - Remove Shoreham (EGKA) Helipad 7 Circle
  .github/CHANGELOG.md
  Airports/EGKA/SMR/Geo.txt
Labels: airac

#5191 Fixes #5190 - Correct EGBG_R_TWR position ICAO code
  .github/CHANGELOG.md
  Airports/EGBG/Positions.txt
Labels: bug
