Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-08, with the labels that each got.

#5398 Fixes #5384 - Update Coningsby (EGXC) Runway QFU
  .github/CHANGELOG.md
  Airports/EGXC/Runway.txt
Labels: airac

#5397 Fixes #5386 - Update Valley (EGOV) Runway QFU
  .github/CHANGELOG.md
  Airports/EGOV/Runway.txt
Labels: airac

#5400 Automations - Check pull requests for changelog modification
  .github/workflows/changelog police.yml
Labels: enhancement

#5375 Fixes #5364 - Update Bristol (EGGD) west apron
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
  _data/SMR Files/EGGD/EGGD.kmz
Labels: airac

#5391 Fixes #5387 - Various Mil Freqs Updated (8.33kHz Compliance)
  .github/CHANGELOG.md
  Airports/EGDM/Positions.txt
  Airports/EGDR/Positions.txt
  Airports/EGOS/Positions.txt
  Airports/EGVP/Positions.txt
  Airports/EGXC/Positions.txt
  Airports/EGYD/Positions.txt
  Airports/EGYE/Positions.txt
  Airports/EGYM/Positions.txt
Labels: airac, controller-pack-change

#5393 Fixes #5389 - Add new RNP fixes for Shawbury (EGOS)
  .github/CHANGELOG.md
  Airports/EGOS/Fixes.txt
Labels: airac

#5394 Fixes #5388 - Add new RNP fixes for Mona (EGOQ)
  .github/CHANGELOG.md
  Airports/EGOQ/Fixes.txt
Labels: airac

#5396 Fixes #5381 - Update Benson (EGUB) Runway QFU
  .github/CHANGELOG.md
  Airports/EGUB/Runway.txt
Labels: airac

#5399 Fixes #5373 - Update coastline in Merseyside Coastline
  .github/CHANGELOG.md
  Colours.txt
  Misc Geo/Merseyside Coastline.txt
Labels: enhancement

#5376 Fixes #5374 - Change Conington (EGSF) Radio Frequency
  .github/CHANGELOG.md
  Airports/EGSF/Basic.txt
  Airports/EGSF/Positions.txt
Labels: airac, controller-pack-change

#5378 Fixes #5377 - Update Manchester (EGCC) SMR - WIP Area Expansion
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  _data/SMR Files/EGCC/EGCC.kmz
Labels: airac

#5417 Fixes #5408 - Update Leeds (EGNM) stand numbers
  .github/CHANGELOG.md
  Airports/EGNM/SMR/Labels.txt
Labels: airac

#5433 Fixes #5424 - Archive Bourn (EGSN) Airport
  .github/CHANGELOG.md
  _data/Closed Airfields/EGSN/Basic.txt
Labels: airac

#5434 Fixes #5412 - Update Liverpool (EGGP) stands
  .github/CHANGELOG.md
  Airports/EGGP/SMR/Geo.txt
  Airports/EGGP/SMR/Labels.txt
  _data/SMR Files/EGGP/EGGP.kmz
Labels: airac

#5437 Fixes #5429 - Add MID fixes for Mona (EGOQ)
  .github/CHANGELOG.md
  Airports/EGOQ/Fixes.txt
Labels: airac

#5432 Fixes #5421 - Remove Shobdon (SH) NDB
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: airac
