Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-11, with the labels that each got.

#5497 Fixes #5496 - Add Manchester (EGCC) Taxi line Linking D and K
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  _data/SMR Files/EGCC/EGCC.kmz
Labels: enhancement

#5507 Fixes #5504 - Change Netheravon (EGDN) frequency
  .github/CHANGELOG.md
  Airports/EGDN/Basic.txt
Labels: airac

#5495 Fixes #5494 - Update Ronaldsway (EGNS) Holding Points.
  .github/CHANGELOG.md
  Airports/EGNS/SMR/Geo.txt
  Airports/EGNS/SMR/Labels.txt
  Airports/EGNS/SMR/Regions.txt
  _data/SMR Files/EGNS/EGNS.kmz
Labels: airac

#5508 Fixes #5503 - Update Cranwell (CWZ) TACAN position
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5509 Fixes #5505 - Update Yeovil (EGDY) frequencies
  .github/CHANGELOG.md
  Airports/EGDY/Basic.txt
  Airports/EGDY/Positions.txt
Labels: airac

#5514 Fixes #5511 - Update Northolt (EGWU) runway QFU
  .github/CHANGELOG.md
  Airports/EGWU/Runway.txt
Labels: airac

#5515 Fixes #5510 - Add Valley (EGOV) RNP fixes
  .github/CHANGELOG.md
  Airports/EGOV/Fixes.txt
Labels: airac

#5513 Fixes #5512 - Add Farnborough (EGLF) LARS Boundary
  .github/CHANGELOG.md
  Colours.txt
  Misc Other/SID_Farnborough LARS.txt
Labels: enhancement

#5500 Fixes #5499 - MUAC Jever sectorisation changes
  .github/CHANGELOG.md
  Agreements/External/Hum_YY-J.txt
  Agreements/External/Hum_YY-JL.txt
  Agreements/External/YY-JL_Hum.txt
  Agreements/External/YY-J_Hum.txt
  Area Positions/4 External.txt
  Sector Boundaries/Lines - PACC.txt
  Sector Ownership/Non-UK/Maastricht.txt
Labels: procedure-change
