Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-02, with the labels that each got.

#5196 Fixes #5192 - Add new FIXES for AIRAC 2402
  .github/CHANGELOG.md
  Navaids/FIXES_UK.txt
Labels: airac

#5202 Fixes #5201 - Correct French ATS Routes
  .github/CHANGELOG.md
  ATS Routes/Conventional - Non-UK/Lower/A30.txt
  ATS Routes/Conventional - Non-UK/Lower/B24.txt
  ATS Routes/Conventional - Non-UK/Lower/G273.txt
  Navaids/Fixes_Non-UK/FIXES_Other.txt
  Navaids/NDB_All.txt
Labels: bug

#5204 Fixes #5203 - Replace temp danger area EGD597 with EGD514 Combat Area
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EG D514.txt
  ARTCC/Danger Areas/EG D597.txt
Labels: airac

#5198 Fixes #5197 - Add 'missing' Gatwick (EGKK) Taxiway Labels
  .github/CHANGELOG.md
  Airports/EGKK/Freetext.txt
Labels: enhancement

#5182 Fixes #5181 - Heathrow (EGLL) RMA 'halved'
  .github/CHANGELOG.md
  Airports/EGLL/RMA.txt
Labels: enhancement, controller-pack-change

#5209 Fixes #5208 - Add Optional Labels for Heathrow Heli Lanes
  .github/CHANGELOG.md
  Airports/EGLL/Freetext.txt
Labels: enhancement

#5195 Fixes #5193 - Add position definition for Land's End ATIS (EGHC_ATIS)
  .github/CHANGELOG.md
  Airports/EGHC/Positions.txt
Labels: airac

#5200 Fixes #5199 - Fix incorrect agreements
  .github/CHANGELOG.md
  Agreements/External/8_SNB.txt
  Agreements/External/RR_JJ.txt
  Agreements/Internal/27_TCCOW.txt
Labels: bug

#5214 Fixes #5213 - Add New Brussels agreement via FRA (IMPOH) Route
  .github/CHANGELOG.md
  Agreements/External/YY-K_E (13+14).txt
  Navaids/Fixes_Non-UK/FIXES_Netherlands.txt
Labels: procedure-change

#5210 Fixes #5206 - Refine TC East LTMA outbound standing agreements
  .github/CHANGELOG.md
  Agreements/Internal/TCDAG_12.txt
  Agreements/Internal/TCRED_12.txt
  Agreements/Internal/TCSAB_15.txt
Labels: bug

#5216 Fixes #5215 - Add S1->S18 Paris Inbound Agreements
  .github/CHANGELOG.md
  Agreements/Internal/1_18.txt
Labels: procedure-change

#5218 Fixes #5217 - Amend North Sea (S10 and S11) DFL
  Agreements/Internal/11_10.txt
  Ownership/AC - North/10.txt
  Ownership/AC - North/11.txt
Labels: procedure-change

#5219 Fixes #5194 - Add Wolverhampton (EGBO) Heli pads and Update SMR
  .github/CHANGELOG.md
  Airports/EGBO/SMR/Geo.txt
  Airports/EGBO/SMR/Labels.txt
  Airports/EGBO/SMR/Regions.txt
  _data/SMR Files/EGBO/EGBO.kmz
Labels: enhancement, airac

#5207 Fixes #5205 - Add Redhill (EGKR) Hover spots and HTAs
  .github/CHANGELOG.md
  Airports/EGKR/SMR/Geo.txt
  Airports/EGKR/SMR/Labels.txt
  _data/SMR Files/EGKR/EGKR.kmz
Labels: enhancement

#5221 Fixes #5220 - Update Belfast Aldergrove (EGAA) Delegated Airspace
  .github/CHANGELOG.md
  Airports/EGAA/Sector.txt
Labels: procedure-change
