Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-04, with the labels that each got.

#5268 Fixes #5244 - Add Thruxton (EGHO) Heli Aiming Points
  .github/CHANGELOG.md
  Airports/EGHO/SMR/Geo.txt
  Airports/EGHO/SMR/Labels.txt
  _data/SMR Files/EGHO/EGHO.kmz
Labels: enhancement

#5265 Fixes #5258 - Update Birmingham (EGBB) SMR Stands and Add WIP area
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Geo.txt
  Airports/EGBB/SMR/Labels.txt
  _data/SMR Files/EGBB/EGBB.kmz
Labels: airac

#5266 Fixes #5224 - Add Coventry (EGBE) Stopway and Disused areas and Update SMR
  .github/CHANGELOG.md
  Airports/EGBE/SMR/Geo.txt
  Airports/EGBE/SMR/Regions.txt
  _data/SMR Files/EGBE/EGBE.kmz
Labels: airac

#5271 Fixes #5225 - Update Bristol (EGGD) SMR, addition of new holds and stand
  .github/CHANGELOG.md
  Airports/EGGD/SMR/Geo.txt
  Airports/EGGD/SMR/Labels.txt
  _data/SMR Files/EGGD/EGGD.kmz
Labels: airac

#5262 Fixes #5229 - Update Ronaldsway (EGNS) SMR
  .github/CHANGELOG.md
  Airports/EGNS/SMR/Geo.txt
  Airports/EGNS/SMR/Labels.txt
  Airports/EGNS/SMR/Regions.txt
  _data/SMR Files/EGNS/EGNS.kmz
Labels: airac

#5269 Fixes #5263 - Remove less precise fixes
  Navaids/Fixes_Non-UK/FIXES_Belgium.txt
  Navaids/Fixes_Non-UK/FIXES_Netherlands.txt
Labels: bug

#4886 Fixes #4885 - Create UK AIP Parser Tooling
  _data/Tools/.gitignore
  _data/Tools/src/api.py
  _data/Tools/src/runner.py
  _data/Tools/tests/test_api.py
Labels: enhancement

#5270 Fixes #5247 - Add EGD218 Fairford
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EGD218.txt
Labels: airac

#5272 Fixes #5246 - Remove old STARs from 2022/05 or earlier
  .github/CHANGELOG.md
  Airports/EGBB/Stars.txt
  Airports/EGBE/Stars.txt
  Airports/EGCC/Stars.txt
  Airports/EGFF/Stars.txt
  Airports/EGGD/Stars.txt
  Airports/EGGP/Stars.txt
  Airports/EGGW/Stars.txt
  Airports/EGNR/Stars.txt
  Airports/EGNX/Stars.txt
Labels: enhancement

#5281 Fixes #5278 - Change Mona (EGOQ) Tower frequency
  .github/CHANGELOG.md
  Airports/EGOQ/Positions.txt
Labels: airac, controller-pack-change

#5291 Fixes #5279 - Change Valley (EGOV) frequencies
  .github/CHANGELOG.md
  Airports/EGOV/Positions.txt
Labels: airac, controller-pack-change

#5290 Fixes #5277 - Update Leuchars (EGQL) frequencies
  .github/CHANGELOG.md
  Airports/EGQL/Positions.txt
Labels: airac, controller-pack-change
