Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-06, with the labels that each got.

#5313 Fixes #5312 - Update Glasgow (EGPF) SMR to new style
  .github/CHANGELOG.md
  Airports/EGPF/SMR/Geo.txt
  Airports/EGPF/SMR/Labels.txt
  Airports/EGPF/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGPF/EGPF.kmz
  _data/SMR Files/EGPF/SMR_2022_Airport.png
  _data/SMR Files/EGPF/SMR_2022_Apron.png
Labels: enhancement

#5330 Fixes #5320 - Add new Gatwick (EGKK) ATCSMA Area 'C'
  .github/CHANGELOG.md
  Airports/EGKK/SMAA.txt
Labels: airac

#5326 Fixes #5296 - Sectorisation Change: Daventry/Clacton/North Sea
  .github/CHANGELOG.md
  Ownership/AC - Central/12.txt
  Ownership/AC - Central/13.txt
  Ownership/AC - Central/14.txt
  Ownership/AC - Central/27.txt
  Ownership/AC - Central/28.txt
  Ownership/AC - Central/34.txt
  Ownership/AC - North/10.txt
  Ownership/AC - North/11.txt
  Ownership/AC - North/3.txt
  Ownership/AC - North/4.txt
  Ownership/AC - South/15.txt
  Ownership/AC - South/19.txt
  Ownership/AC - South/2.txt
  Ownership/AC - South/21.txt
  Ownership/AC - South/22.txt
  Ownership/AC - South/24.txt
  Ownership/AC - South/25.txt
  Ownership/AC - South/26.txt
  Ownership/AC - West/23.txt
  Ownership/AC - West/35.txt
  Ownership/AC - West/5.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/Non-UK/Brussels.txt
  Ownership/Non-UK/Maastricht.txt
  Ownership/TC - LTC/London TC COWLY.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC JACKO.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC REDFA.txt
  Ownership/TC - LTC/London TC SABER.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC SW.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Ownership/TC - MPC/East.txt
  Ownership/TC - MPC/S29.txt
  Ownership/TC - MPC/SE Stafa.txt
  Sectors/Lines - LACC.txt
  Sectors/Static/LON/Clacton.txt
  Sectors/Static/LON/Daventry.txt
  Sectors/Static/LON/North Sea.txt
Labels: procedure-change

#5286 2406 Sectorisation Changes: affects NOR, CLN, DTY, LMS, BCN, Mids
  .github/CHANGELOG.md
  Ownership/AC - Central/12.txt
  Ownership/AC - Central/13.txt
  Ownership/AC - Central/14.txt
  Ownership/AC - Central/27.txt
  Ownership/AC - Central/28.txt
  Ownership/AC - Central/34.txt
  Ownership/AC - North/10.txt
  Ownership/AC - North/11.txt
  Ownership/AC - North/3.txt
  Ownership/AC - North/4.txt
  Ownership/AC - South/15.txt
  Ownership/AC - South/19.txt
  Ownership/AC - South/2.txt
  Ownership/AC - South/21.txt
  Ownership/AC - South/22.txt
  Ownership/AC - South/24.txt
  Ownership/AC - South/25.txt
  Ownership/AC - South/26.txt
  Ownership/AC - West/23.txt
  Ownership/AC - West/35.txt
  Ownership/AC - West/5.txt
  Ownership/Non-UK/Amsterdam.txt
  Ownership/Non-UK/Brussels.txt
  Ownership/Non-UK/Maastricht.txt
  Ownership/TC - LTC/London TC COWLY.txt
  Ownership/TC - LTC/London TC DAGGA.txt
  Ownership/TC - LTC/London TC JACKO.txt
  Ownership/TC - LTC/London TC LAM.txt
  Ownership/TC - LTC/London TC REDFA.txt
  Ownership/TC - LTC/London TC SABER.txt
  Ownership/TC - LTC/London TC SE.txt
  Ownership/TC - LTC/London TC SW.txt
  Ownership/TC - LTC/London TC WELIN.txt
  Ownership/TC - MPC/East.txt
  Ownership/TC - MPC/S29.txt
  Ownership/TC - MPC/SE Stafa.txt
  Sectors/Lines - LACC.txt
  Sectors/Lines - LTC.txt
  Sectors/Static/LON/AC West.txt
  Sectors/Static/LON/Brecon.txt
  Sectors/Static/LON/Clacton.txt
  Sectors/Static/LON/Daventry.txt
  Sectors/Static/LON/North Sea.txt
  Sectors/Static/LON/Sector 23.txt
  Sectors/Static/LTC/Midlands.txt
Labels: bug, on-hold, procedure-change

#5331 Fixes #5327 - Update Bristol (EGGD) Delegated Airspace
  .github/CHANGELOG.md
  Airports/EGGD/Ownership.txt
  Airports/EGGD/RMA.txt
  Airports/EGGD/Sector.txt
Labels: enhancement

#5337 Fixes #5336 - Correct GDUP-2 border error
  .github/CHANGELOG.md
  Airports/EGGD/Sector.txt
Labels: bug

#5324 Fixes #5321 - Change Fast Aviation taxiway color on Bournemouth (EGHH) SMR
  .github/CHANGELOG.md
  Airports/EGHH/SMR/Regions.txt
  _data/SMR Files/EGHH/EGHH.kmz
Labels: airac

#5328 Fixes #5323 - Update Jersey VOR (JSY) coordinates
  .github/CHANGELOG.md
  Navaids/VOR_UK.txt
Labels: airac

#5329 Fixes #5322 - Remove Lashenden NDB (LSH)
  .github/CHANGELOG.md
  Navaids/NDB_All.txt
Labels: on-hold, airac
