Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-05, with the labels that each got.

#5289 Fixes #5282 - Change Prestwick (EGPK) Runway Designators
  .github/CHANGELOG.md
  Airports/EGPK/Fixes.txt
  Airports/EGPK/Runway.txt
  Airports/EGPK/Stars.txt
Labels: airac

#5299 Fixes #5280 - Update Fairford (EGVA) Runway Coordinates
  .github/CHANGELOG.md
  Airports/EGVA/Runway.txt
Labels: airac

#5298 Fixes #5297 - Re-align Fairford (EGVA) ATZ
  .github/CHANGELOG.md
  Airports/EGVA/Airspace.txt
Labels: bug

#5306 Fixes #5305 - Increase Agreement via LONAM (EHAM dep) to FL320
  .github/CHANGELOG.md
  Agreements/External/YY-J_Hum.txt
Labels: procedure-change

#5254 Fixes #5253 - Update Manchester (EGCC) SMR
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  _data/SMR Files/EGCC/EGCC.kmz
Labels: airac

#5302 Fixes #5301 - Update Polaris sector orders
  .github/CHANGELOG.md
  Area Positions/4 External.txt
  Ownership/Non-UK/Polaris - Stavanger.txt
Labels: procedure-change

#5295 Fixes #5294 - Create Ostend TMA
  .github/CHANGELOG.md
  Agreements/External/TCSE_BU.txt
  Airports/EBOS/Basic.txt
  Airports/EBOS/Ownership.txt
  Airports/EBOS/Positions.txt
  Airports/EBOS/Sector.txt
Labels: enhancement

#5308 Fixes #5307 - Add Arrival Airport Ownership for Glasgow (EGPF) Tower
  .github/CHANGELOG.md
  Airports/EGPF/Ownership.txt
Labels: bug

#5311 Fixes #5283 - Update Southampton (EGHI) Stands 2-5 positions
  .github/CHANGELOG.md
  Airports/EGHH/SMR/Geo.txt
  Airports/EGHI/SMR/Geo.txt
  Airports/EGHI/SMR/Labels.txt
  Airports/EGHI/SMR/Regions.txt
  _data/SMR Files/EGHH/EGHH.kmz
Labels: bug, airac

#5310 Fixes #5309 - Add GND and DEL Automatic Airport Selection functionality
  .github/CHANGELOG.md
  Airports/EGAA/Ownership.txt
  Airports/EGBB/Ownership.txt
  Airports/EGCC/Ownership.txt
  Airports/EGDY/Ownership.txt
  Airports/EGGD/Ownership.txt
  Airports/EGGP/Ownership.txt
  Airports/EGGW/Ownership.txt
  Airports/EGHH/Ownership.txt
  Airports/EGHQ/Ownership.txt
  Airports/EGJA/Ownership.txt
  Airports/EGJB/Ownership.txt
  Airports/EGJJ/Ownership.txt
  Airports/EGKK/Ownership.txt
  Airports/EGLC/Ownership.txt
  Airports/EGLF/Ownership.txt
  Airports/EGLL/Ownership.txt
  Airports/EGNM/Ownership.txt
  Airports/EGNT/Ownership.txt
  Airports/EGNX/Ownership.txt
  Airports/EGPD/Ownership.txt
  Airports/EGPF/Ownership.txt
  Airports/EGPH/Ownership.txt
  Airports/EGQL/Ownership.txt
  Airports/EGSS/Ownership.txt
  Airports/EGTK/Ownership.txt
  Airports/EGUB/Ownership.txt
  Airports/EGUN/Ownership.txt
  Airports/EGVN/Ownership.txt
  Airports/EGWU/Ownership.txt
  Airports/EGXC/Ownership.txt
  Airports/EGXT/Ownership.txt
  Airports/EGXZ/Ownership.txt
  Airports/EGYD/Ownership.txt
Labels: enhancement

#5304 Fixes #5305 - Add Burnham Box
  .github/CHANGELOG.md
  Radar Maps (Stars)/Burnham Box.txt
  Radar Maps (Stars)/EXMOR Burnham Line.txt
Labels: enhancement, controller-pack-change

#5300 Fixes #5292 - Update Fleetlands (EGVF) frequency
  .github/CHANGELOG.md
  Airports/EGVF/Basic.txt
Labels: on-hold, airac

#5293 Fixes #5284 - Add Airbus Hangar and Helipads to Oxford (EGTK) SMR
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Geo.txt
  Airports/EGTK/SMR/Labels.txt
  Airports/EGTK/SMR/Regions.txt
  _data/SMR Files/EGTK/EGTK.kmz
Labels: airac
