Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2024-12, with the labels that each got.

#5523 Fixes #5518 - Add EGD098 complex
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EGD098.txt
Labels: enhancement

#5539 Fixes #5519 - Add East Midlands (EGNX) TRPs
  .github/CHANGELOG.md
  Airports/EGNX/SMR/Geo.txt
  Airports/EGNX/SMR/Labels.txt
  Airports/EGNX/SMR/Regions.txt
  _data/SMR Files/EGNX/EGNX.kmz
Labels: airac

#5537 Fixes #5526 - Add Barkston Heath (EGYE) RNP fixes
  .github/CHANGELOG.md
  Airports/EGYE/Fixes.txt
Labels: airac

#5522 Fixes #5521 - Update Gloucester (EGBJ) SMR
  .github/CHANGELOG.md
  Airports/EGBJ/SMR/Geo.txt
  Airports/EGBJ/SMR/Labels.txt
  Airports/EGBJ/SMR/Regions.txt
  _data/SMR Files/EGBJ/EGBJ.kmz
  _data/SMR Files/EGBJ/Old KMZs/EGBJ(pre2413).kmz
Labels: airac

#5542 Fixes #5414 - Update Gatwick (EGKK) SMR runway markings
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Regions.txt
  _data/SMR Files/EGKK/EGKK.kmz
  _data/SMR Files/EGKK/Old KMZs/Gatwick SMR (2410).kmz
Labels: airac

#5532 Fixes #5531 - Change Wittering (EGXT) Frequencies
  .github/CHANGELOG.md
  Airports/EGXT/Positions.txt
Labels: airac, controller-pack-change

#5517 Fixes #5516 - Update LFEE_CTR frequency
  .github/CHANGELOG.md
  Area Positions/4 External.txt
Labels: procedure-change

#5541 Fixes #5540 - Update Amsterdam and MUAC Delta Positions and Coverage Order
  .github/CHANGELOG.md
  Area Positions/4 External.txt
  Sector Ownership/Non-UK/Amsterdam.txt
  Sector Ownership/Non-UK/Maastricht.txt
Labels: procedure-change

#5538 Fixes #5529 - Add Cranwell (EGYD) RNP fixes
  .github/CHANGELOG.md
  Airports/EGYD/Fixes.txt
Labels: airac

#5536 Fixes #5525 - Add Barkston Heath (EGYE) MID Fixes
  .github/CHANGELOG.md
  Airports/EGYE/Fixes.txt
Labels: airac

#5546 Fixes #5545 - Remove EUC-MW_CTR Position from MUAC Sectors
  .github/CHANGELOG.md
  Area Positions/4 External.txt
  Sector Ownership/AC - Central/14.txt
  Sector Ownership/Non-UK/Maastricht.txt
Labels: procedure-change

#5535 Fixes #5528 - Add Cranwell (EGYD) MID Fixes
  .github/CHANGELOG.md
  Airports/EGYD/Fixes.txt
Labels: airac

#5533 Fixes #5530 - Change Waddington (EGXW) Frequencies
  .github/CHANGELOG.md
  Airports/EGXW/Positions.txt
Labels: airac, controller-pack-change

#5447 Fixes #5547 - Correct TC NE -> TC East Standing Agreements
  .github/CHANGELOG.md
  Agreements/Internal/TCDAG_TCSAB.txt
  Agreements/Internal/TCNE_TCRED.txt
  Agreements/Internal/TCNE_TCSAB.txt
  Agreements/Internal/TCRED_TCSAB.txt
Labels: bug

#5544 Fixes #5524 - Update S18->PN agreements
  .github/CHANGELOG.md
  Agreements/External/18_PN.txt
  Agreements/External/18_RR-E.txt
  Agreements/External/PN_17.txt
  Agreements/External/PN_TCSE.txt
  Sector Ownership/Non-UK/Paris.txt
Labels: bug
