Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2025-07, with the labels that each got.

#5778 Issue #5777 - Revise Berry Head CTA 6 OCAS Region
  .github/CHANGELOG.md
  Misc Regions/Uncontrolled airspace (Grey).txt
  Misc Regions/Uncontrolled airspace.txt
Labels: bug

#5759 Fixes #5745 - Create Lakenheath (EGUL) SMR
  .github/CHANGELOG.md
  Airports/EGUL/Basic.txt
  Airports/EGUL/SMR/Geo.txt
  Airports/EGUL/SMR/Labels.txt
  Airports/EGUL/SMR/Regions.txt
  _data/SMR Files/EGUL/EGUL.kmz
Labels: enhancement

#5784 Fixes #5765 - Add Blackpool (EGNH) Heli Stand Visitor 3
  .github/CHANGELOG.md
  Airports/EGNH/SMR/Labels.txt
  _data/SMR Files/EGNH/EGNH.kmz
Labels: airac

#5797 Fixes #5796 - Correct Yeovilton (EGDY) ARP location
  .github/CHANGELOG.md
  Airports/EGDY/Basic.txt
Labels: bug
