Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2025-08, with the labels that each got.

#5795 Fixes #5782 - Add North Sea HMRI End-Points
  .github/CHANGELOG.md
  Navaids/FIXES_HMRI-Gates.txt
Labels: enhancement

#5822 Fixes #5259 - Update Birmingham (EGBB) Terminal WIP area
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Geo.txt
  Airports/EGBB/SMR/Labels.txt
  Airports/EGBB/SMR/Regions.txt
  Colours.txt
  _data/SMR Files/EGBB/EGBB.kmz
  _data/SMR Files/EGBB/Old SMR/EGBB.kmz
Labels: enhancement, airac

#5814 Fixes #5813 Updated Gatwick (EGKK) SMR for accuracy
  .github/CHANGELOG.md
  Airports/EGKK/SMR/Geo.txt
  Airports/EGKK/SMR/Regions.txt
  _data/SMR Files/EGKK/EGKK.kmz
Labels: enhancement

#5829 Fixes #5828 - Added S/A for Mids arrs from S19 -> S25 (event only)
  .github/CHANGELOG.md
  Agreements/Internal/19_25.txt
Labels: enhancement

#5832 Fixes #5703 - Improved S/A display for MTMA deps (DTY -> WOR/DVR)
  .github/CHANGELOG.md
  Agreements/Internal/27_2.txt
  Agreements/Internal/27_24.txt
Labels: enhancement

#5801 Fixes #5800 - Update Portsmouth CTA 5 lateral definition
  .github/CHANGELOG.md
  ARTCC/High/Portsmouth CTA.txt
Labels: airac

#5818 Fixes #5808 - Bournemouth (EGHH) SMR changes
  .github/CHANGELOG.md
  Airports/EGHH/SMR/Geo.txt
  Airports/EGHH/SMR/Labels.txt
  Airports/EGHH/SMR/Regions.txt
  _data/SMR Files/EGHH/EGHH.kmz
Labels: airac

#5823 Fixes #5803 - Add Oxford (EGTK) disused area
  .github/CHANGELOG.md
  Airports/EGTK/SMR/Regions.txt
  _data/SMR Files/EGTK/EGTK.kmz
Labels: airac

#5827 Fixes #5804 - Remove Barton (EGCB) runway designators
  .github/CHANGELOG.md
  Airports/EGCB/SMR/Regions.txt
  _data/SMR Files/EGCB/EGCB.kmz
Labels: airac
