Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2025-03, with the labels that each got.

#5606 Fixes #5604 - Change ENSV enroute frequencies (8.33 implementation)
  .github/CHANGELOG.md
  Area Positions/4 External.txt
Labels: procedure-change

#5609 Fixes #5603 - Truncate East Midlands (EGNX) DTY SIDs to SAPCO
  .github/CHANGELOG.md
  Agreements/Airport/NX_TCWEL.txt
  Airports/EGNX/Fixes.txt
  Airports/EGNX/Sids.txt
Labels: airac

#5624 Fixes #5619 - Change Upavon (EGDJ) freq
  .github/CHANGELOG.md
  Airports/EGDJ/Basic.txt
  Airports/EGDJ/Positions.txt
Labels: airac

#5600 Fixes #5597 - Truncate Essex Group BARMI STARs
  .github/CHANGELOG.md
  Airports/EGGW/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
Labels: airac

#5620 Fixes #5605 - Remove data withdrawn 2023/03 (West Airspace Deployment)
  .github/CHANGELOG.md
  Agreements/Airport/5_FF.txt
  Agreements/Airport/6_FF.txt
  Agreements/Airport/FF_5.txt
  Agreements/Airport/FF_6.txt
  Agreements/Airport/FF_8.txt
  Agreements/Airport/TE_6.txt
  Agreements/Internal/23_25.txt
  Agreements/Internal/23_TCCPT.txt
  Agreements/Internal/23_TCSW.txt
  Agreements/Internal/23_TCVAT.txt
  Agreements/Internal/25_23.txt
  Agreements/Internal/5_S29.txt
  Agreements/Internal/5_Wallasey.txt
  Agreements/Internal/TCCPT_23.txt
  Agreements/Internal/TCSW_23.txt
  Airports/EGCC/Stars.txt
  Airports/EGFF/Fixes.txt
  Airports/EGFF/Sids.txt
  Airports/EGFF/Stars.txt
  Airports/EGGD/Fixes.txt
  Airports/EGGD/Sids.txt
  Airports/EGGD/Stars.txt
  Airports/EGGP/Stars.txt
  Airports/EGGW/Fixes.txt
  Airports/EGGW/Sids.txt
  Airports/EGGW/Stars.txt
  Airports/EGKB/Stars.txt
  Airports/EGKK/Stars.txt
  Airports/EGLC/Stars.txt
  Airports/EGLL/Stars.txt
  Airports/EGNR/Stars.txt
  Airports/EGSC/Stars.txt
  Airports/EGSS/Stars.txt
  Airports/EGWU/Stars.txt
  Navaids/FIXES_Old.txt
Labels: enhancement

#5621 Fixes #5617 - Syerston (EGXY) AGCS freq change
  .github/CHANGELOG.md
  Airports/EGXY/Basic.txt
  Airports/EGXY/Positions.txt
Labels: airac

#5627 Fixes #5618 - Topcliffe (EGXZ) freq change
  .github/CHANGELOG.md
  Airports/EGXZ/Basic.txt
  Airports/EGXZ/Positions.txt
Labels: airac

#5634 Fixes #5630 - Change Gloucester approach callsign
  .github/CHANGELOG.md
  Airports/EGBJ/Positions.txt
Labels: enhancement, controller-pack-change

#5626 Fixes #5612 - Add Marham (EGYM) RNP fixes
  .github/CHANGELOG.md
  Airports/EGYM/Fixes.txt
Labels: airac

#5625 Fixes #5623 - Fix compile script running unnecessarily
  .github/workflows/compile.yml
Labels: bug

#5614 Fixes #5611 - Add Little Rissington (EGVL) radio frequency
  .github/CHANGELOG.md
  Airports/EGVL/Basic.txt
  Airports/EGVL/Positions.txt
Labels: airac, controller-pack-change

#5629 Fixes #5595 - Amend ATS Route(s) L60, M604 and N866 and create ATS Route Z150
  .github/CHANGELOG.md
  ATS Routes/RNAV/Lower/L60.txt
  ATS Routes/RNAV/Lower/Z150.txt
  ATS Routes/RNAV/Upper/L60.txt
  ATS Routes/RNAV/Upper/M604.txt
  ATS Routes/RNAV/Upper/N866.txt
  ATS Routes/RNAV/Upper/Z150.txt
Labels: airac

#5638 Fixes #5637 - Change to Bremen (EDWW) frequency
  .github/CHANGELOG.md
  Area Positions/4 External.txt
  Navaids/FIXES_Old.txt
Labels: procedure-change

#5632 Fixes #5631 - Add standing agreements for EGNX SAPCO-LUXTO outbounds
  .github/CHANGELOG.md
  Agreements/Internal/TCCOW_23.txt
  Agreements/Internal/TCWEL_TCCOW.txt
Labels: procedure-change

#5643 Fixes #5642 - Remove Puckeridge VRP from Gatwick Profile
  .github/CHANGELOG.md
  Airports/EGKK/VRPs.txt
Labels: bug, controller-pack-change

#5628 Fixes #5601 - Changes to Clacton standing agreements (2503)
  .github/CHANGELOG.md
  Agreements/Internal/10_12.txt
  Agreements/Internal/12_10.txt
  Agreements/Internal/TCDAG_12.txt
  Agreements/Internal/TCRED_12.txt
Labels: procedure-change
