Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2025-04, with the labels that each got.

#5613 Fixes #5610 - Add Kirknewton (EGKT) Radio frequency
  .github/CHANGELOG.md
  Airports/EGKT/Basic.txt
  Airports/EGKT/Positions.txt
Labels: airac, controller-pack-change

#5655 Fixes #5650 - Update EGNH SMR parking to AIRAC (2413)
  .github/CHANGELOG.md
  Airports/EGNH/SMR/Geo.txt
  Airports/EGNH/SMR/Labels.txt
  _data/SMR Files/EGNH/EGNH.kmz
Labels: bug

#5664 Fixes #5646 - Change Halton (EGWN) frequency
  .github/CHANGELOG.md
  Airports/EGWN/Basic.txt
  Airports/EGWN/Positions.txt
Labels: airac

#5663 Fixes #5662 - Remove Dieppe (DPE) VOR
  .github/CHANGELOG.md
  ATS Routes/Conventional - Non-UK/Lower/R50.txt
  Navaids/Fixes_Non-UK/FIXES_France.txt
  Navaids/VOR_Non-UK.txt
Labels: bug

#5657 Fixes #5649 - Draw Kirknewton (EGKT) Circuit / Soaring areas
  .github/CHANGELOG.md
  ARTCC/Danger Areas/DGA-Kirknewton.txt
Labels: airac, controller-pack-change

#5656 Fixes #5653 - Tingwall (EGET) Apron changes
  .github/CHANGELOG.md
  Airports/EGET/SMR/Geo.txt
  Airports/EGET/SMR/Regions.txt
  _data/SMR Files/EGET/EGET.kmz
Labels: airac

#5660 Fixes #5651 - Benbecula (EGPL) Runway 17/35 removed
  .github/CHANGELOG.md
  Airports/EGPL/Runway.txt
  Airports/EGPL/SMR/Geo.txt
  Airports/EGPL/SMR/Labels.txt
  Airports/EGPL/SMR/Regions.txt
  _data/SMR Files/EGPL/EGPL.kmz
Labels: airac
