Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2025-05, with the labels that each got.

#5684 Fixes #5683 - admin: Change name of Gal_Tay.txt
  .github/CHANGELOG.md
  Agreements/Internal/Galloway_Tay.txt
Labels: bug, enhancement

#5680 Fixes #5679 - Remove Stands 9A, 10A & 209 at Edinburgh
  .github/CHANGELOG.md
  Airports/EGPH/SMR/Geo.txt
  _data/SMR Files/EGPH/EGPH.kmz
Labels: bug

#5670 Fixes #5668 - Update Stansted (EGSS) Ground Network
  .github/CHANGELOG.md
  Airports/EGSS/Ground_Network.txt
Labels: enhancement, ground/air-network

#5669 Fixes #5652 - Add Gloucestershire (EGBJ) Heli spot
  .github/CHANGELOG.md
  Airports/EGBJ/SMR/Geo.txt
  Airports/EGBJ/SMR/Labels.txt
  _data/SMR Files/EGBJ/EGBJ.kmz
Labels: airac

#5659 Fixes #5654 - Add Manchester (EGCC) Pier 2
  .github/CHANGELOG.md
  Airports/EGCC/SMR/Geo.txt
  Airports/EGCC/SMR/Labels.txt
  Airports/EGCC/SMR/Regions.txt
  _data/SMR Files/EGCC/Manchester - EGCC.kmz
  _data/SMR Files/EGCC/Old KMZs/EGCC_SMR_25-04.kmz
Labels: airac

#5697 Fixes #5696 - Fix EGBB airport agreement lines using WCO
  .github/CHANGELOG.md
  Agreements/Airport/BB_TCCOW.txt
  Agreements/Airport/TCCOW_BB.txt
Labels: bug

#5661 Fixes #5658 - Birmingham (EGBB) Elmdon apron changes
  .github/CHANGELOG.md
  Airports/EGBB/SMR/Geo.txt
  Airports/EGBB/SMR/Labels.txt
  Airports/EGBB/SMR/Regions.txt
  _data/SMR Files/EGBB/EGBB.kmz
Labels: airac, controller-pack-change

#5693 Fixes #5691 - Automations: Changelog change check script runs unnecessarily
  .github/workflows/changelog police.yml
Labels: bug, no-changelog

#5690 Fixes #5689 - Update fighter control positions
  .github/CHANGELOG.md
  Area Positions/1 UK Permanent.txt
Labels: procedure-change, controller-pack-change

#5692 Fixes #5667 - Update Edinburgh (EGPH) Ground Network
  .github/CHANGELOG.md
  Airports/EGPH/Ground_Network.txt
Labels: enhancement, ground/air-network

#5708 Fixes #5666 - Update Manchester (EGCC) Ground Network
  .github/CHANGELOG.md
  Airports/EGCC/Ground_Network.txt
Labels: enhancement, airac, ground/air-network

#5675 Fixes #5672 - Change Glasgow (EGPF) frequencies
  .github/CHANGELOG.md
  Airports/EGPF/Basic.txt
  Airports/EGPF/Positions.txt
Labels: airac, controller-pack-change

#5682 Fixes #5681 - Remove EGPE_A_APP
  .github/CHANGELOG.md
  Airports/EGPE/Positions.txt
Labels: airac, controller-pack-change

#5706 Fixes #5698 - Remove WCO NDB dependencies - replaced by WEZKO
  .github/CHANGELOG.md
  Airports/EGLL/Fixes.txt
  Airports/EGLL/Stars.txt
  Airports/EGWU/Stars.txt
  Navaids/NDB_All.txt
Labels: airac

#5705 Fixes #5704 - Update Guernsey (EGJB) SIDs
  .github/CHANGELOG.md
  Airports/EGJB/Sids.txt
  Navaids/FIXES_CICZ.txt
Labels: airac

#5711 Fixes #5710 - Removes Helgoland (DHE) VOR
  .github/CHANGELOG.md
  Navaids/VOR_Non-UK.txt
Labels: bug

#5720 Fixes #5717 - Change Heathrow (EGLL) planner frequency
  .github/CHANGELOG.md
  Airports/EGLL/Positions.txt
Labels: airac, controller-pack-change

#5725 Fixes #5724 - Remove Heathrow (EGLL) stands 611-613 on SMR
  .github/CHANGELOG.md
  Airports/EGLL/SMR/Geo.txt
  Airports/EGLL/SMR/Labels.txt
  _data/SMR Files/EGLL/EGLL-Helper.kmz
  _data/SMR Files/EGLL/EGLL.kmz
Labels: airac

#5735 Fixes #5728 - Update Jersey (EGJJ) SMR to remove hangar
  .github/CHANGELOG.md
  Airports/EGJJ/SMR/Regions.txt
  _data/SMR Files/EGJJ/EGJJ.kmz
Labels: airac

#5732 Fixes #5726 - Add EGD220 Marham danger areas
  .github/CHANGELOG.md
  ARTCC/Danger Areas/EGD220.txt
Labels: airac

#5731 Fixes #5729 - Update Shobdon (EGBS) SMR
  .github/CHANGELOG.md
  Airports/EGBS/SMR/Geo.txt
  Airports/EGBS/SMR/Labels.txt
  _data/SMR Files/EGBS/EGBS.kmz
Labels: airac

#5678 Fixes #5671 - Prestwick (EGPK) SID and STAR naming changes
  .github/CHANGELOG.md
  Airports/EGPK/Fixes.txt
  Airports/EGPK/Sids.txt
  Airports/EGPK/Stars.txt
Labels: airac

#5722 Fixes #5713 - Revise Berry Head CTA 6 definition and label
  .github/CHANGELOG.md
  ARTCC/High/Berry Head CTA.txt
  Misc Other/Freetext_Airspace Bases.txt
Labels: airac

#5737 Fixes #5736 - Define LEDGO RFC Area
  .github/CHANGELOG.md
  Radar Maps (Stars)/LEDGO RFC Area.txt
Labels: procedure-change
