Repository VATSIM-UK/UK-Sector-File, pull requests merged in 2025-01, with the labels that each got.

#5560 Fixes #5559 - Remove data withdrawn 2022/13 and prior
  .github/CHANGELOG.md
  Airports/EGBB/Sids.txt
  Airports/EGKB/Sids.txt
  Airports/EGLC/Fixes.txt
  Airports/EGLC/Sids.txt
  Navaids/FIXES_Old.txt
Labels: enhancement

#5543 Fixes #5520 - Update Rochester (EGTO) SMR
  .github/CHANGELOG.md
  Airports/EGTO/SMR/Labels.txt
  Airports/EGTO/SMR/Regions.txt
  _data/SMR Files/EGTO/EGTO.kmz
  _data/SMR Files/EGTO/Old KMZs/EGTO(pre2413).kmz
Labels: airac

#5563 Fixes #5561 - Add Cambridge (EGSC) Radar
  .github/CHANGELOG.md
  Airports/EGSC/Positions.txt
  Airports/EGSC/Positions_Mentor.txt
  Airports/EGSC/Sector_Ownership.txt
Labels: procedure-change

#5565 Fixes #5564 - Change EGNX SMR colour
  .github/CHANGELOG.md
  Airports/EGNX/SMR/Regions.txt
  Colours.txt
Labels: enhancement

#5569 Fixes #5566 - Update Cosford (EGWC) Frequencies
  .github/CHANGELOG.md
  Airports/EGWC/Positions.txt
Labels: airac, controller-pack-change

#5568 Fixes #5567 - Update Yeovilton (EGDY) ARP and Runway designators
  .github/CHANGELOG.md
  Airports/EGDY/Basic.txt
  Airports/EGDY/Runway.txt
Labels: airac

#5554 Fixes #5550 - Improve next sector prediction for PF/PH inbounds to APP
  .github/CHANGELOG.md
  Agreements/Airport/Tal_PF.txt
  Agreements/Airport/Tal_PH.txt
  Sector Ownership/TC - STC/Galloway.txt
Labels: bug

#5555 Fixes #5551 - Improve next sector prediction for ScTMA arrs Montrose -> Talla
  .github/CHANGELOG.md
  Agreements/Internal/Mon_Talla.txt
  Sector Ownership/ScAC - West/Deancross.txt
Labels: bug

#5556 Fixes #5552 #5553 - Improve agreement/COPX display for EGPN/QL inbounds
  .github/CHANGELOG.md
  Agreements/Internal/Dcs_Tal.txt
  Agreements/Internal/Gal_Tay.txt
  Agreements/Internal/Tal_Gal.txt
Labels: bug, enhancement
